### ISSUE TITLE
Address book tag sorting

### ISSUE THREAD

**Issue by it-boerner** [rustdesk/rustdesk-server-pro#10]
The sorting in the address book for the keywords does not work correctly. When new keywords are created, the keywords in the list are not sorted.

![image](https://github.com/rustdesk/rustdesk-server-pro/assets/118393600/4853edc6-3e4f-4219-855e-2d35a4acc58f)

----

- [ ] we will add an option for this, though default is not sorted.

**Comment by dinger1986** [comment]
These are tags, I don't think they are intended to be sorted.

**Comment by it-boerner** [comment]
If these tags aren't meant for sorting, you might want to reconsider, because when you have a lot of clients, you need an overview.

**Comment by dinger1986** [comment]
No, they are for tagging clients and sorting but I don't know if they were intended to be sorted in alphabetical order. 

Search should probably search the tags

**Comment by it-boerner** [comment]
That is already clear to me, but I think that this topic could also be interesting for other customers.

**Comment by rustdesk** [comment]
Sorting tag? Looks wierd for me. Let's keep watch and listen to the other voices first.

**Comment by it-boerner** [comment]
> Tag sortieren? Sieht für mich seltsam aus. Bleiben wir im Auge und hören uns zunächst weitere Stimmen an.

Ok, thanks :)

**Comment by dinger1986** [comment]
I wouldn't close this

**Comment by rustdesk** [comment]
Please keep this open and listen to more voices.

**Comment by IT-Betreuung** [comment]
It would be verry nice,
when the tags are sorted in alphabetical order.

**Comment by rustdesk** [comment]
we will add an option for this.

**Comment by rustdesk** [comment]
1.1.10
