### ISSUE TITLE
nginx: [emerg] invalid number of arguments in "proxy_set_header" directive in /etc/nginx/sites-enabled/rustdesk.conf

### ISSUE THREAD

**Issue by glennonline** [rustdesk/rustdesk-server-pro#101]
I'm trying to install Rustdesk pro, however I keep getting the following error:
Command may disrupt existing ssh connections. Proceed with operation (y|n)? y
Firewall is active and enabled on system startup
Firewall reloaded
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Error while running nginx -c /etc/nginx/nginx.conf -t.

nginx: [emerg] invalid number of arguments in "proxy_set_header" directive in /e                                                                                                                                                             tc/nginx/sites-enabled/rustdesk.conf:4
nginx: configuration file /etc/nginx/nginx.conf test failed

The nginx plugin is not working; there may be problems with your existing config                                                                                                                                                             uration.
The error was: MisconfigurationError('Error while running nginx -c /etc/nginx/ng                                                                                                                                                             inx.conf -t.\n\nnginx: [emerg] invalid number of arguments in "proxy_set_header"                                                                                                                                                              directive in /etc/nginx/sites-enabled/rustdesk.conf:4\nnginx: configuration fil                                                                                                                                                             e /etc/nginx/nginx.conf test failed\n')

I've simply issued the following command:
bash <(wget -qO- https://raw.githubusercontent.com/rustdesk/rustdesk-server-pro/main/install.sh)

I have tried with Debian Linux 12 and Ubuntu server 22.04

**Comment by rustdesk** [comment]
What time did you run above? since I put a fix several hours ago, https://github.com/rustdesk/rustdesk-server-pro/issues/100

**Comment by glennonline** [comment]
Yesterday, thanks for fixing it, will try it now.

**Comment by enoch85** [comment]
This can be closed.
