### ISSUE TITLE
Waiting for RustDesk Relay service to become active... Unit rustdesk-hbbr.service could not be found. keeps displaying

### ISSUE THREAD

**Issue by glennonline** [rustdesk/rustdesk-server-pro#107]
Hi,

Earlier I tried to install Rustdesk and encountered the error in https://github.com/rustdesk/rustdesk-server-pro/issues/101
I now tried to install it again on a fresh server, and I keep getting the following error:
Waiting for RustDesk Relay service to become active...
Unit rustdesk-hbbr.service could not be found.

When I ran the installation yesterday, I didn't notice any screen when starting the installation about root privileges, maybe that could be the cause? no matter if I do yes or no, the same issue still comes up.

Before the error above (that keeps repeating) I get this error:
Failed to enable unit: Unit file rustdesk-hbbs.service does not exist.
Failed to start rustdesk-hbbs.service: Unit rustdesk-hbbs.service not found.
Failed to enable unit: Unit file rustdesk-hbbr.service does not exist.
Failed to start rustdesk-hbbr.service: Unit rustdesk-hbbr.service not found.

**Comment by rustdesk** [comment]
@enoch85 could you confirm if it is related to https://github.com/rustdesk/rustdesk-server-pro/pull/96?

**Comment by enoch85** [comment]
I will have a look in around 1 hour.

**Comment by enoch85** [comment]
@glennonline which OS are you running?

**Comment by glennonline** [comment]
Tried with Debian 12 and Ubuntu 22.04 both had the same result

**Comment by enoch85** [comment]
Found the error, new PR is coming up soon.

**Comment by enoch85** [comment]
@glennonline Please confirm that it works for you now.

**Comment by jbhewitt** [comment]
I just tried it and it seems to be working now

**Comment by glennonline** [comment]
Yes, everything looks fine now.
