### ISSUE TITLE
Umlauts in the address book

### ISSUE THREAD

**Issue by it-boerner** [rustdesk/rustdesk-server-pro#11]
In the address book, when new entries are created, no umlauts can be used, as they are not considered or applied. I think this is a problem of UTF-8

**Comment by rustdesk** [comment]
something like `ä, ö, ü`?

**Comment by dinger1986** [comment]
Yes that's right 👍

**Comment by rustdesk** [comment]
@21-pages

**Comment by 21pages** [comment]
https://github.com/rustdesk/rustdesk/pull/5252
try nightly
