### ISSUE TITLE
Client Config Re-Deployment Script

### ISSUE THREAD

**Issue by AdrielleU** [rustdesk/rustdesk-server-pro#117]
With RustDesk Server Pro, I was successful installing the automatic client through EXE and Script for Batch/Powershell from docs https://rustdesk.com/docs/en/self-host/client-deployment/

First time setup was successful but if I change IP address of RustDesk Server IP Address or do a public token refresh, the Client Config Auto Deployment Script stops working and won't update new changes. rustdesk-licensed-XXXXXXXXX.exe (EXE) seems to be working perfectly with these changes accounted for but lacks setting a permanent password which is what I'm looking for.

I also realized if I re-use the Auto Client Config Script, it doesn't allow to change password after uninstalling RustDesk Client on local computer.

**Comment by dinger1986** [comment]
if the encrypted string correct?

**Comment by AdrielleU** [comment]
Are you talking about the config string that is provided in the Web Console? It is correct and placed in the script and the EXE file correctly. The EXE works perfectly fine with the in-line config string in the file name so I know it is correctly setting the Public Key and IP address.

**Comment by dinger1986** [comment]
ok, but if you edit the install scripts they dont work?

**Comment by AdrielleU** [comment]
Yes if I try to change the password install scripts don't work. If I try to change RustDeskServer Pro docker container itself to a different IP, it also doesn't work or doesn't update properly.

**Comment by dinger1986** [comment]
Ok, I dont know about docker sorry, but if you are using the powershell script its got a check in it for the client already being installed and exits if it is, you could remove that.

The alternative is if you dont want to reset the password but just change the config to a new server could just do (elevated powershell):

```
$rustdesk_cfg="configstring"
cd $env:ProgramFiles\RustDesk\
.\RustDesk.exe --config $rustdesk_cfg
```

**Comment by AdrielleU** [comment]
I have uninstalled RustDesk Client on Windows so the script can continue normally. The Password isn't updating

My RustDeskServer Pro is on Docker for context but I'm just stating I changed to a new IP Address/Port and refreshed Key.
And how the config string fails to have the correct newly updated server information with Powershell/Batch Script

**Comment by dinger1986** [comment]
is it the powershell or batch script?

you shouldnt need to uninstall just change the config.

Presumably the service isnt running when the config and password is attempted to be applied, how recently did you get the powershell scripts? maybe work looking at it as it was updated last week https://rustdesk.com/docs/en/self-host/client-deployment/#powershell

**Comment by AdrielleU** [comment]
I have been dealing with the new powershell script. It won't work on any of my clients if I try putting my custom config number or key. Batch script was working for me until I changed my RustDesk Server Pro machine with a different IP address and Public Key.

Powershell seems to just stop in the middle and I removed certain checks like Version and If installed.

**Comment by dinger1986** [comment]
I use the --config command all the time to change on the fly what servers I am using and works fine in both batch and powershell

What happens if you install manually and then run the commands via the commandline?

**Comment by AdrielleU** [comment]
Whoops, thanks for the help! I got it figured out with your test, I assumed it was already running in Administrator mode when I was running the script because I get a Windows pop up admin confirmation. I don't know if it was a timing issue or if the Windows prompt was for just one portion of the script.

So just "Run as administrator" when running these scripts in Windows. Got it.
