### ISSUE TITLE
Device-List in RustDeskPro

### ISSUE THREAD

**Issue by it-boerner** [rustdesk/rustdesk-server-pro#12]
Hello everyone,

- [x] I would like to be able to add a column with the notes entered when displaying the devices in the future.
- [x] It would also be nice if you could select the user via a dropdown box when editing a device.

![image](https://github.com/rustdesk/rustdesk-server-pro/assets/118393600/ea1e4199-cfa8-4092-9200-8d017b3c7bd6)

**Comment by rustdesk** [comment]
Noted with thanks.

**Comment by rustdesk** [comment]
@21pages let's add note (we have this field in this database, but somehow not shown and editable in frontend).
Also think about user dropdown box. It does not make sense to fetch all users, let's chatgpt and get a good solution, this is a very common use case, there should be mature solution.

**Comment by it-boerner** [comment]
Why doesn't the drop down box make sense? I currently have 67 clients in my RustDesk and had to manually assign the user to each ID / host. That is very complex

**Comment by rustdesk** [comment]
How about if there are 1000 users. We need a good solution.

**Comment by it-boerner** [comment]
But querying users via a select box or dropdown isn't bad code after all

**Comment by rustdesk** [comment]
I talked about implementation with my team member.

**Comment by it-boerner** [comment]
Perfect thank you

**Comment by 21pages** [comment]
How about a limited drop-down menu with a online search(inaccurate match)?

**Comment by it-boerner** [comment]
That would be a good idea too

**Comment by rustdesk** [comment]
> How about a limited drop-down menu with a online search(inaccurate match)?

Let's do it.

**Comment by rustdesk** [comment]
@21pages I have done this.

- [x] I would like to be able to add a column with the notes entered when displaying the devices in the future.

- [x] It would also be nice if you could select the user via a dropdown box when editing a device.

**Comment by rustdesk** [comment]
1.1.10
