### ISSUE TITLE
Isolated group

### ISSUE THREAD

**Issue by mycanaletto** [rustdesk/rustdesk-server-pro#129]
Hello,

How can I assign a device to a group that is not linked to a specific user in the console (and then allow this group to be accessed by two users)?

**Comment by rustdesk** [comment]
No, we chose to discard device group, but user group only.

**Comment by mycanaletto** [comment]
So does this mean that a user 1 will be able to access the devices of another user 2?

This doesn't make sense, as user 2 may have private devices he doesn't want to share.

The only solution I can think of right now is to create virtual users:

This way, virtual user 1's devices can be accessed by users 1 and 2 without them sharing their private devices. But that would mean buying a license with more users (don't become a TeamViewer I want to get rid of).

**Comment by mycanaletto** [comment]
It doesn't answer the need, except to create a virtual user... Are you going that way?
