### ISSUE TITLE
Log-List - RustDeskPro

### ISSUE THREAD

**Issue by it-boerner** [rustdesk/rustdesk-server-pro#13]
In the log list, only the ID and not the name of the host or the note stored is displayed. It's hard to understand just by having the ID to identify which device it is

----

- [x] device name added, it is hostname by default, but you can also edit in device page.

**Comment by rustdesk** [comment]
We tested google stmp and aws smtp.

**Comment by rustdesk** [comment]
Making sense, we need to polish this.

**Comment by it-boerner** [comment]
I think it's important that I share with you all the bugs I've found so you can create something productive out of them.

I believe in the great potential of RustDesk and will switch all my customers to RustDesk.

**Comment by rustdesk** [comment]
1.1.10
