### ISSUE TITLE
OIDC and Root CA

### ISSUE THREAD

**Issue by erikgenesis** [rustdesk/rustdesk-server-pro#130]
Hi,

We're having problems with an OIDC implementation. The token request gets stopped due to an invalid certificate authority.
How do we add Root certificates? Rustdesk Pro doesn't seem to use the system default certificates: /etc/ssl/certs/ca-certificates.crt

[2023-10-10 13:40:51.307374 +02:00] ERROR [src/oidc.rs:700] Failed to contact token endpoint, Request(Reqwest(reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("oidc.testserver.local")), port: None, path: "/token", query: None, fragment: None }, source: hyper::Error(Connect, Custom { kind: Other, error: Custom { kind: InvalidData, error: InvalidCertificate(UnknownIssuer) } }) }))

We're running on Debian 12

/Erik

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
@dinger1986 wondering if you have any input about this?

**Comment by erikgenesis** [comment]
It's our own server/implementation. But it halt in the handshake with the server because of the "Unknown Issuer" problem. I've tried looking at the hbbs service with strace and i can't see that it even tries to read the system root certificates. Are the certificates stored in the binary or in the sqlite database?

**Comment by dinger1986** [comment]
is it active directory?

**Comment by erikgenesis** [comment]
No. It's a custom internal website for OIDC authentication.
The token request from the Rustdesk Pro service rejects to post the token request because the certificate our server is presenting isn't signed by any of the root certificates that Rustdesk Pro accepts. How do i add other certificates to this list since it doesn't seem to use the system default certificates?

**Comment by dinger1986** [comment]
Sorry I dont know anything about custom OIDC

**Comment by rustdesk** [comment]
@fufesou https://github.com/seanmonstar/reqwest/issues/1554

**Comment by fufesou** [comment]
@erikgenesis Hi, I'm working on this issue.
I've added a custom `pemfile` field.


![b](https://github.com/rustdesk/rustdesk-server-pro/assets/13586388/bfce0244-6cb4-4b6b-8f4b-1c981e66ae50)


But I'm not sure if the implementation works on your machine.

Can you please run the simple test which will try to read the issuer will-known metadata?

![a](https://github.com/rustdesk/rustdesk-server-pro/assets/13586388/e53bc361-c9cc-415c-9c63-196249eb63ea)

[simple_test.tar.gz](https://github.com/rustdesk/rustdesk-server-pro/files/12909681/simple_test.tar.gz)

**Comment by erikgenesis** [comment]
$ dpkg-query -S '/usr/lib/x86_64-linux-gnu/libssl.so.3'
libssl3:amd64: /usr/lib/x86_64-linux-gnu/libssl.so.3

**Comment by erikgenesis** [comment]
It works great in 1.1.10-5. Thanks
