### ISSUE TITLE
Installation blocked on "Checking if public key is generated..."

### ISSUE THREAD

**Issue by skoky** [rustdesk/rustdesk-server-pro#131]
I purchased a license and started installation on my Linux server with `bash <(wget -qO- https://raw.githubusercontent.com/rustdesk/rustdesk-server-pro/main/install.sh)` command. As I setup unpriviledged user, installation started and got stucked on repeating message "Checking if public key is generated...". What should I do?
My Linux version:
```
 uname -a
Linux hugo-dev 5.15.0-1040-oracle #46-Ubuntu SMP Fri Jul 14 21:47:21 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
```

**Comment by skoky** [comment]
```

**Comment by rustdesk** [comment]
@enoch85

**Comment by enoch85** [comment]
The service is not starting as it should.

Could you please post the output of the service file, and also do a `cat` of /etc/passwd?

**Comment by enoch85** [comment]
Just tested and cannot reproduce this:

[Screencast from 2023-10-13 11:51:17.webm](https://github.com/rustdesk/rustdesk-server-pro/assets/4511254/3e546585-a0ea-4d28-ae00-68df332e36d0)

**Comment by skoky** [comment]
ok, once deleting my hand made service files it works. Anyway I hd troubles with nginx setup. Maybe the installation script should not touch this, just describe what should be done. Thanks

**Comment by enoch85** [comment]
@skoky The script assumes a clean server/VPS. 

You are welcome with a PR to change it. :)
