### ISSUE TITLE
Azure Users - username too long

### ISSUE THREAD

**Issue by slm-sean** [rustdesk/rustdesk-server-pro#139]
We have started using azure SSO with RustDesk and have run into an issue where some of our users' emails are more than 30 characters long. They can log in and the user is created in RustDesk, but we are unable to save any changes to their user because the username is over 30 characters.

Can the limit be increased to avoid this issue?

**Comment by rustdesk** [comment]
Please try out 1.1.10-5 https://github.com/rustdesk/rustdesk-server-pro/releases/tag/1.1.10-5

**Comment by slm-sean** [comment]
Thanks, we will upgrade and test!
