### ISSUE TITLE
SMTP - RustDeskPro

### ISSUE THREAD

**Issue by it-boerner** [rustdesk/rustdesk-server-pro#14]
I can't enter an SMTP server in the RustDesk Console. I have the feeling that German servers or the servers from German providers are not accepted.

After saving, there is always the error that a timeout has occurred.

![image](https://github.com/rustdesk/rustdesk-server-pro/assets/118393600/69f46fc9-5b3a-424d-869d-d59f970f3901)

**Comment by dinger1986** [comment]
Where's your server hosted? Is port 25 open on it?

**Comment by it-boerner** [comment]
No, port 465 or 587 is used and SSL/TLS must be used.

https://www.strato.de/faq/mail/so-lauten-die-strato-e-mail-server/

**Comment by dinger1986** [comment]
Port 25 was an example, can you telnet or connect from whatever your server is to the Mail server?

You need to answer questions ask as well if you want help!

**Comment by it-boerner** [comment]
Do the ports in the Linux firewall also have to be open for the connection to the SMTP server?

Could this be the problem?

**Comment by dinger1986** [comment]
They shouldn't need to be incoming but you need to test from the commandline using telnet or similar. Chances are your VPS provider blocks smtp and you need to ask them to unblock

**Comment by it-boerner** [comment]
Thanks for the help, I will check accordingly

**Comment by dinger1986** [comment]
I was going to add smtp setup to the docs today and testing anyways

**Comment by rustdesk** [comment]
We tested Google stmp and AWS SES.

**Comment by dinger1986** [comment]
It's most likely the vps provider

**Comment by it-boerner** [comment]
Yes, it is the VPS provider (Hetzner) and ports 25 and 465 are blocked there by default.

**Comment by dinger1986** [comment]
Please close. I'll write up for FAQs today anyway

**Comment by it-boerner** [comment]
I had my provider activate the SMTP port.

I have entered the data for the SMTP server in the settings and I am told: "Successful"

However, when I exit these settings, the data is gone.

**Comment by it-boerner** [comment]
Sorry, the problem was on my side. All good and it works perfectly :)
