### ISSUE TITLE
LDAP uses Attribute cn or displayName but should be changeable to sAMAccountName

### ISSUE THREAD

**Issue by devNull2and1** [rustdesk/rustdesk-server-pro#140]
As title says, got LDAP working, can login but only with Attribute cn / displayName. I did many ldap integrations with other software. Where can i configre that he take always Attribute sAMAccountName. How can i map this?

![image](https://github.com/rustdesk/rustdesk-server-pro/assets/144108510/80c6cc06-6276-4036-92cc-2c40bc3bb62f)

**Comment by devNull2and1** [comment]
@rustdesk please give me a hint 🔢

**Comment by rustdesk** [comment]
@fufesou please check if it is doable.

**Comment by fufesou** [comment]
@devNull2and1 Hi, thanks for your feedback. 

We do not use `sAMAccountName` in the previous version.

But I just did a search and find that `sAMAccountName` is more suitable as a username.
The next version will give priority to using this attribute as the username.

**Comment by devNull2and1** [comment]
hello @fufesou thx for reply. would be nice to configure it with a dropdown or just a text field from the webui. some customers maybe prefer `mail` or `principalName` or even `givenName` for login. We decided to take `sAMAccountName` cause it is the same way they login every morning when they start their pc's.

I have to wait till you release it but i would like to give them the gui to manage devices right now. Can i change it myself somewehre? Which container i have to mount, Which file i have to edit?

**Comment by rustdesk** [comment]
Agree, @fufesou make it configurable. cname as default.

**Comment by rustdesk** [comment]
givenName / userPrincipalName are unqiue?

**Comment by fufesou** [comment]
> I have to wait till you release it but i would like to give them the gui to manage devices right now. Can i change it myself somewehre? Which container i have to mount, Which file i have to edit?

Sorry, there's no configuration about it for now. You have to wait. I'll do it as soon as possible.

**Comment by devNull2and1** [comment]
@rustdesk  I don't know exactly. this is microsoft active directory. `givenName` is the first name of a person and `sn` ist the last name. `sAMAccountName` and `userPrincipalName` should be unique cause `userPrincipalName` always is `user.name@comany.domain` and  `sAMAccountName` is always first part of `userPrincipalName`before @.

**Comment by devNull2and1** [comment]
I'm surprised that no one has asked about this yet...

**Comment by devNull2and1** [comment]
> > I have to wait till you release it but i would like to give them the gui to manage devices right now. Can i change it myself somewehre? Which container i have to mount, Which file i have to edit?
> 
> Sorry, there's no configuration about it for now. You have to wait. I'll do it as soon as possible.

Ohhhh, okay, then i wait. Thank you for reply.

**Comment by willosof** [comment]
Yeah. This.

From other software - in the main LDAP config section it looks like this:
<img width="772" alt="image" src="https://github.com/rustdesk/rustdesk-server-pro/assets/426386/d57851e9-27a2-4d22-9a92-b0f42a441d64">

This covers the edge cases in this original topic for most people, so they can customize the fields used from LDAP.

On multiple other softwares I use LDAP for, I also have a per group query filter like this:

```(&(objectClass=Person)(memberOf:1.2.840.113556.1.4.1941:=CN=TheSecurityGroup,OU=Security Groups,DC=my,DC=activedirectory,DC=com))``` 

This is some active directory secret sauce to recursively search for group access, when we have groups that have other groups as members, to cascade access within departments/organisations etc easier. 

This could easily be just ```(memberOf:CN=TheSecurityGroup,OU=Security Groups,DC=my,DC=activedirectory,DC=com)``` as well, but then it wouldn't be recursive, something that makes this whole thing very, very nice.

And for the individual group filters; Optimally, if all
* Groups
* Strategies
* Source computers (not that important)
* Destination computers (not that important)

.. had an optional LDAP search filter, the entire access management could be handled and administered by the LDAP server.

So, if security group names in LDAP/AD looks like:
* ORG1-ADMIN (member of group ORG1-CLIENT)
* ORG1-CLIENT
* ORG1-ADMIN (member of group ORG2-CLIENT)
* ORG1-CLIENT
* DA-RUST-ADMIN (member of ORG1-ADMIN, ORG2-ADMIN)

Me as as a DA-RUST-ADMIN member could log into all ORG1 and ORG2
Users as ORG1-CLIENT member could only log in and be controlled by ORG1-ADMIN users
Users as ORG2-ADMIN member could log in and control devices logged in with ORG2-CLIENT users.
Users as DA-RUST-CLIENT can only be accessed by 
The users within the resources you don't have access to, should be completely hidden from the client applications. And optimally be refreshed from server within a admin-specified interval.

Sorry to just throw this at you like this, but it's something that would make my life SO much easier, and would be my tipping point for buying probably mutiple top tier licenses. (I have access to one today to review it)

Context; One LDAP for 15 companies, 200 employees, 2000 users (freelancers and clients), 100 security groups, some users are employed by us, some are also our clients, and some users work in multiple companies. LDAP solves this easily, and the users+groups are being administered by the different companies from a separate system. And admins/clients for ORG1 should NEVER see anything at all about ORG2 when they log in.)

NB: I see some holes in my theory - but in strategies alone, filters would be a REALLY good start.

Lastly I would like to thank you all for the work you do to challenge the expensive alternatives out there!

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk-server-pro/releases/tag/1.1.11

**Comment by MichaelF25** [comment]
I am always getting "I/O error: User not found" if I try to login to RustDesk Console after setting up LDAP with Active Directory 2019 server. I've did many other LDAP integrations with our AD server already, but with RustDesk Pro, I do net get it working.

I am using current version 1.1.14-3 (the welcome screen tells me there is a "newer" 1.1.14-1 available?):

![Screenshot from 2024-01-28 18-12-19](https://github.com/rustdesk/rustdesk-server-pro/assets/6987344/32b7dcfb-c174-4c88-8448-cf483e065b1a)

Do I have to also create the users additionally in the WebConsole?

**Comment by fufesou** [comment]
Hi, can you please try set `Scope` 'sub' or remove `Bind DN` and `Password`?

**Comment by MichaelF25** [comment]
@fufesou tried your suggestions: Settings `Scope` to `sub` did not change anything. Removing the `Bind DN` and it's `Password` generates another error if I try to login regarding missing permissions from our AD server which makes sense since anonymous access is not allowed. I am using this `ldap-bind` user also for other LDAP/AD integrations successfully, so it should not be a permission issue.

**Comment by rustdesk** [comment]
Can you try removing filter?

**Comment by MichaelF25** [comment]
@rustdesk tried removing the filter. User still not found. I guess the filter `(objectCategory=Person)` is nevertheless taken into account since it seems to be the default because it's displayed in grey font after clearing the filter field.

Is there a way to extend `hbbs` logging for LDAP? When I try to login with AD credentials, and getting the `User not found` error on UI, only

`[2024-01-30 07:36:59.834957 +00:00] INFO [src/ldap.rs:245] New LDAP connection: ldap://dc2019.XXXXX:389`

is logged. After some seconds following lines also appear in the log:
```
[2024-01-30 07:40:08.623863 +00:00] WARN [/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ldap3-0.11.3/src/conn.rs:728] socket receive error: Connection reset by peer (os error 104)
[2024-01-30 07:40:08.623925 +00:00] WARN [src/ldap.rs:247] LDAP connection error: I/O error: Connection reset by peer (os error 104)
```

**Comment by fufesou** [comment]
> it seems to be the default because it's displayed in grey font after clearing the filter field.

No, the grey font is just a placeholder here. If you left it empty, the server will not search the user, but just try verify a ldap account directly.

Maybe there's something wrong with the account name.
Can you give a screenshot of the login form with key information hidden?

**Comment by MichaelF25** [comment]
![image](https://github.com/rustdesk/rustdesk-server-pro/assets/6987344/a25616fc-561a-4470-907e-b0e188583f08)

**Comment by fufesou** [comment]
Is your account `cn=mforstner,cn=Users,dc=...` ?

**Comment by devNull2and1** [comment]
> https://github.com/rustdesk/rustdesk-server-pro/releases/tag/1.1.11 ![image](https://private-user-images.githubusercontent.com/71636191/288586185-063e7aac-caa6-4cd5-a019-23440f194db0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MDc5NDYsIm5iZiI6MTcwNjYwNzY0NiwicGF0aCI6Ii83MTYzNjE5MS8yODg1ODYxODUtMDYzZTdhYWMtY2FhNi00Y2Q1LWEwMTktMjM0NDBmMTk0ZGIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDA5NDA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNTRlODI5N2VmMmM4MDljYzBiODY4YTk4NzZmYTMzZDhhM2E0YjUzMmM4OWM5ZTcxNTBiMTA3OTBmY2Y2MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ddfz7InsghyvCkY7SN7iuVUfuXLij9oZbGgqs7pD-BM)

happy new year, been on vacation since the beginning of December due to overtime, thanks for the update, I'll test it!

**Comment by MichaelF25** [comment]
@fufesou it is `cn=mforstner,cn=Users,dc=...`

**Comment by fufesou** [comment]
Can you please try login with username "Michael Forstner" ?

**Comment by MichaelF25** [comment]
> Can you please try login with username "Michael Forstner" ?

That worked! My username however is displayed as `mforstner` if I go to my account settings after login.
So after all looks like a bug to me that LDAP Username Attribute is not taken into account for the login page, or?

**Comment by fufesou** [comment]
> 
> ![Screenshot from 2024-01-28 18-12-19](https://private-user-images.githubusercontent.com/6987344/300280678-32b7dcfb-c174-4c88-8448-cf483e065b1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MTQ0NTcsIm5iZiI6MTcwNjYxNDE1NywicGF0aCI6Ii82OTg3MzQ0LzMwMDI4MDY3OC0zMmI3ZGNmYi1jMTc0LTRjODgtODQ0OC1jZjQ4M2UwNjViMWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzBUMTEyOTE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWE3MzI1ZTVjMTVkMGIzYjlhYWQ0NTI1YjQwOTBmZmY2ZjE1ZThkODg1ZjAwZjg2YTMzODRlNWVhMDgwNzc3YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8HywtP_em9TAmog7qFG4IYs7g9SZR9Hy6JK3BNh4bR4)

Your username is set to "mforstner" because you have set the "Username attribute" to "sAMAccountName".

You may need to change it to another attribute.

**Comment by rustdesk** [comment]
> Your username is set to "mforstner" because you have set the "Username attribute" to "sAMAccountName".
> 
> You may need to change it to another attribute.

@MichaelF25 ignore this, this is our stupid bug.

**Comment by devNull2and1** [comment]
@fufesou i updated to 1.1.11 and changed `Username attribute` to `sAMAccountName` or `Bind sAMAccountName` i also get `I/O error: User Not found` that means bind is not working. Fallback `Bind CN` ist working.

I opened that issue, watch my Issue and Screenshot.
Login with Max Mustermann work.
Login with max.mustermann do not work.

So, i can confirm, `sAMAccountName` still not possible!

**Comment by rustdesk** [comment]
@devNull2and1 sorry for this. @fufesou understood the issue wrong, had a wrong fix.

**Comment by devNull2and1** [comment]
No Problem. Nice to see that you work on Issues 👍

**Comment by rustdesk** [comment]
@MichaelF25 In the other LDAP integrations, can both "mforstner" and "Michael Forstner" log in?

**Comment by devNull2and1** [comment]
> @MichaelF25 In your the other LDAP integrations, can both "mforstner" and "Michael Forstner" log in?

you did not ask me but we have other ldap integrations like icewarp. gitea, forgejo, jira, bitbucket, sonciwall, sophos, pfsense, opnsense....we can use `sAMAccountName` everywhere and login with `max.mustermann`

**Comment by rustdesk** [comment]
@devNull2and1 do you mean both names work?

**Comment by devNull2and1** [comment]
@rustdesk on most other integrations:

- when i user attribute `sAMAccountName` then only max.mustermann works
- when i choose atrtribute `cn` only `max mustermann` works without dot. 
- when i choose attribute `sn` only `mustermann` works. 
- when i choose attrribut `principalName` only `max.mustermann@domain.com` works.

**Comment by devNull2and1** [comment]
for example, have a look at this... gitea/forgejo (selfhosted sourcecode alternative to github):

![image](https://github.com/rustdesk/rustdesk-server-pro/assets/144108510/0793eea2-cc81-4866-a510-40d9cd1939e6)

**Comment by rustdesk** [comment]
@devNull2and1 In your picture, which field determine below?

> when i choose attribute sAMAccountName then only max.mustermann works
when i choose attribute cn only max mustermann works without dot.
when i choose attribute sn only mustermann works.
when i choose attribute principalName only max.mustermann@domain.com works.

**Comment by devNull2and1** [comment]
Username Attribute -> `sAMAccountName` then only `max.mustermann` works for login on gitea/forgejo

**Comment by rustdesk** [comment]
Got it

**Comment by MichaelF25** [comment]
> @MichaelF25 In your the other LDAP integrations, can both "mforstner" and "Michael Forstner" log in?

Usually I login with `mforstner` on other environments integrated via LDAP with our AD.

**Comment by rustdesk** [comment]
Thanks @MichaelF25

**Comment by rustdesk** [comment]
@devNull2and1 could you help confirm another thing? When you choose attribute cn, is this cn case sensitive?

**Comment by devNull2and1** [comment]
@rustdesk not case sensitive. with attribute `cn` i can login with `max mustermann` and with `Max Mustermann` i think it is in cause of microdoofy windoofy. not case sensitiv thingy

**Comment by rustdesk** [comment]
The fix is push to latest docker, https://hub.docker.com/r/rustdesk/rustdesk-server-pro/tags

**Comment by devNull2and1** [comment]
Thank you. Login is working now with `max.mustermann` when i choose user attribute `sAMAccountName`.

**Comment by jbarciat** [comment]
Hello,
As we have been discussing via email, I'm posting it here:

I have been following docs and that issue but haven't been able to make it work.
I have tried using cn, dn, sAMAccountName, and userPrincipalName as the username attribute, but it doesn't work. It keeps returning the same I/O error: User not found.
I have also been testing with ldapsearch to verify that the attributes are correct, and they indeed are.
I’m attaching some screenshots of my configuration in the RustDesk console, the ldapsearch results, and the error I get when trying to log in.
Thank you very much for your help.

RustDesk Console:
![image](https://github.com/user-attachments/assets/6aed06c2-9e67-439e-a862-dd7842d7337a)

Ldapsearch:
![image](https://github.com/user-attachments/assets/cef2a5af-406e-4048-a2f4-20238820702c)

Log In error:
![image](https://github.com/user-attachments/assets/4e22a319-dae2-4a2b-bf82-4bbf9378b3cd)

**Comment by fufesou** [comment]
@jbarciat Hi, how about removing the filter?

**Comment by jbarciat** [comment]
> @jbarciat Hi, how about removing the filter?

The problem was the filter.
I changed to (&(objectClass=user)(memberOf=CN=RUSTDESK,CN=Users,DC=<domain>,DC=local)) and now I can log in with AD user.

Thanks

**Comment by guillaumearnx** [comment]
Hi, rustdesk 1.4.8 on arch linux

Using this

![Image](https://github.com/user-attachments/assets/59358784-9fdb-4017-b69e-9802ea33c4b2)

cant login with my samaccountname

![Image](https://github.com/user-attachments/assets/6a696923-9ee0-42f9-bb87-e7dacd3300c2)

![Image](https://github.com/user-attachments/assets/3cfa0a35-9dc8-417c-9dcb-dc62d3296921)

but if i let default value (dn), i can login with my dn `cn=myname,ou=...,dc=...,dc=...`

thank's

**Comment by fufesou** [comment]
@guillaumearnx Hi, could you please try changing "Scope" to `sub`? Because I can't see `ou=...` in your "Base DN".

![Image](https://github.com/user-attachments/assets/24ee7133-8d6a-47fc-8d99-e2b96a0e92bd)

**Comment by guillaumearnx** [comment]
@fufesou thank's a lot <3
