### ISSUE TITLE
[FEATURE] DarkMode

### ISSUE THREAD

**Issue by devNull2and1** [rustdesk/rustdesk-server-pro#141]
Very simple :)

![image](https://github.com/rustdesk/rustdesk-server-pro/assets/144108510/53a17a23-2b1c-4ffd-b512-927879021daa)

**Comment by devNull2and1** [comment]
> Sorry for this, we will add ASAP for saving your eyes. :(
> 
> > ![image](https://user-images.githubusercontent.com/144108510/277902611-53a17a23-2b1c-4ffd-b512-927879021daa.png)

Im just joking. Love your project. Keep things up.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk-server-pro/releases/tag/1.1.12 has dark mode now.

**Comment by rustdesk** [comment]
![image](https://github.com/rustdesk/rustdesk-server-pro/assets/71636191/5199dd46-ba84-48b3-89ce-b88686da29d3)

**Comment by devNull2and1** [comment]
Thank you so much SIR!

**Comment by devNull2and1** [comment]
@rustdesk thank you so much SIR.

But i can't find it. Nowhere, where can i change to the dark side?

**Comment by devNull2and1** [comment]
> @rustdesk thank you so much SIR.
> 
> But i can't find it. Nowhere, where can i change to the dark side?
> 
> ![image](https://private-user-images.githubusercontent.com/144108510/300798026-da0e2ccd-c460-4cd0-8e5b-1e32d50753cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MTY1NjIsIm5iZiI6MTcwNjYxNjI2MiwicGF0aCI6Ii8xNDQxMDg1MTAvMzAwNzk4MDI2LWRhMGUyY2NkLWM0NjAtNGNkMC04ZTViLTFlMzJkNTA3NTNjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQxMjA0MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZDJlMmMyZjRkNWZiNmFhODYzNTkxMWJhNmM5ZDI0MzE3ZGZiMmUzMWQ1NWIxZThhMzFkMTgyM2U3ZjI1YjBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CRqtLu_Xha09KnICFiFudtPgTRh9FB-krwoKJYefWlc)

Forget it. My stupid misstake. I have 1.1.11 but i need 1.1.12. Sorry!
