### ISSUE TITLE
Okta  error

### ISSUE THREAD

**Issue by rustdesk** [rustdesk/rustdesk-server-pro#143]
> We have Okta OIDC setup for our management portal and have been able to login for the past few months.  I am now getting the error in the attached pic.  This leaves us unable to login as our IT group doesn’t have the admin password for the web console.  We do have SSH access to the box hosting Rustdesk.  How can we get back in?

![image](https://github.com/rustdesk/rustdesk-server-pro/assets/71636191/3c066266-8767-4071-aa3e-471413d735d5)

**Comment by jasonsimpson-alianza** [comment]
"Please go there and track the issue, Please append more detail to the issue, your version, when will it start? after upgrade? You'd better paste your oidc setting page on the issue."

Started yesterday, unable to check version or provide OIDC settings as I'm unable to log in at all.

**Comment by rustdesk** [comment]
Have you deleted `admin`? There are no other non-oidc account?

**Comment by rustdesk** [comment]
@fufesou

**Comment by fufesou** [comment]
@jasonsimpson-alianza Can you remember pro version do you use?

The latest version will tell the reason why "Failed to verify ID token", but the version of 3 moths ago will just report the error.

I though the OIDC server may return a token claims that we can't read.
But I've tried a version of 3 moths ago, the login auth is ok for me.

<img width="989" alt="1698381104659" src="https://github.com/rustdesk/rustdesk-server-pro/assets/13586388/c6ed0348-561f-4c06-8ac1-791f8093cedb">


Can you upgrade the version?

I'll also try to test upgrade to the lastest version if you tell me your version.

https://github.com/rustdesk/rustdesk-server-pro/releases/tag/1.1.10-5

**Comment by fufesou** [comment]
@jasonsimpson-alianza Can you please backup the db files `db.sqlite3` and `db.sqlite3-*`, and then upgrade the pro server?

Then we can see what the error is on login.

**Comment by rustdesk** [comment]
close since no response
