### ISSUE TITLE
Feature Request (device group)

### ISSUE THREAD

**Issue by MerryPickles** [rustdesk/rustdesk-server-pro#145]
Hi. I am using RustDesk and running my own server. I have the Business  self-hosting plan. I wish there was a way I could group all the devices  that belong to a single company or a single entity together. 

I provide IT support for a variety of businesses and am trying to move away from a competitor. This would make it much easier to look at all the  computers belonging to one company in one look. 

Also, I just found out the wildcard if you are looking for a computer on the Devices list is the percent sign (%). Not intuitive. Entering just a portion of the  name will not find the computer in the Device List. This is why allowing  grouping of computers/devices will make RustDesk much easier to use.

**Comment by rustdesk** [comment]
We are now working on this. We will make wildcard search to default. 
We are considering to add device group or device tag.

**Comment by rustdesk** [comment]
fuzzy search is enabled in https://github.com/rustdesk/rustdesk-server-pro/releases/tag/1.1.12-1

**Comment by MerryPickles** [comment]
This is excellent news! Thanks for letting me know.






Andrew Parkins
***@***.***

**Comment by rustdesk** [comment]
@ZetaWaves please post a seperate issue for this.
