### ISSUE TITLE
Permanent Password - RustDesk Client

### ISSUE THREAD

**Issue by it-boerner** [rustdesk/rustdesk-server-pro#15]
How can you set a permanent password for the clients in the future using a PowerShell script?

I manage my clients with RMM software and do a lot with PowerShell scripts.

Also updating the client software.

**Comment by dinger1986** [comment]
Use the `--password` string after the executable

**Comment by it-boerner** [comment]
Perfect thanks I will try this.

**Comment by dinger1986** [comment]
This is to do with rustdesk client and not pro anyway
