### ISSUE TITLE
make it so groups dont require a user + assing devices to mutiple users directly without groups

### ISSUE THREAD

**Issue by IzunaMoon** [rustdesk/rustdesk-server-pro#157]
hi so i like a we love de software so far but there is a issue with makes it hard to make things easy to manage so we have some users dat has access to all devices but also some dat should only see a have access to a few maybe a method to allow users to access only specific devices be amazing 

en make it so you can add multiple people or groups instead off only 1 group like it is now i get you can add 

here is a example
![image](https://github.com/rustdesk/rustdesk-server-pro/assets/132285275/37165572-a5c9-4751-9956-6df75e357270)
de one in red could be de user where devices show up dat are assign to dat specific user

but under it groups will appear dat are assign to de user 

personal devices:
my laptop or desktop

group:
servers a other devices where dat group off people have only access to

occurs personal devices should overwrite de perms off de group settings

it be amazing sins with how it is now we are essentially force to make none users accounts to than assign it to a device to add it to a group a than share de group with de real users with looks extremely messy a hard to manage in de console 

plus  maybe a user only need access to 1 or 2 device dat is in de group than it is far more easy to just assign a device to dat user so they can connect to there in store music system

than it does not main user off de device but dat person might need to connect sometime to get some files or do something or if de main user is sick it is far more easy a safer to assign than dat 1 device to user instead off de entire group off devices with is likely to have devices in it not meant for users eyes to see

------------------

we did find some work around at de moment as mention making none user accounts a assign e groups dat way but it is quite messy in all honesty it works but it is quite messy

we are quite a big company as well so making none users accounts is also quite a waste off resources for us as well

are there any plans to look into this to make things more easy for big companies it department te tool is perfect for if you are a it person like us a we are de only ones dat need to access de company devices remotely but it has it weak-points ones you start adding other people dat has only need to access some devices or dat you need to share a devices with a external company dat really only need access to there specific server  

ps English is not my best language so i hope it isnt to hard to read or understand

**Comment by IzunaMoon** [comment]
occurs having share address books will also fix this issue somewhat

**Comment by rustdesk** [comment]
share address books  is under dev

**Comment by IzunaMoon** [comment]
i know i just wanted to share some off de concurrent struggles we have sins we do like de software a lot

but yeah 

de address book plus having devices be able to assign to multiple groups or users be amazing 

most off all do thanks for making this software it has help us a lot with many things

**Comment by rustdesk** [comment]
Thanks

**Comment by rustdesk** [comment]
https://twitter.com/rustdesk/status/1777180459429986787
