### ISSUE TITLE
Error on OIDC Azure Connection

### ISSUE THREAD

**Issue by teraxionTI** [rustdesk/rustdesk-server-pro#164]
Hi,

I use RustDesk Server Pro (Self-hosted) on a Debian os with docker.
I need help for setup my connection with my azure (Microsoft).

I followed the steps in the documentation (https://rustdesk.com/docs/en/self-host/rustdesk-server-pro/oidc/azure/), but I get an error when I try to connect.

![oidc_azure](https://github.com/rustdesk/rustdesk-server-pro/assets/152305914/13ef1090-d09f-429b-a673-c43c8fefdef6)

![oidc_azure_2](https://github.com/rustdesk/rustdesk-server-pro/assets/152305914/27d7122e-ff22-4a68-ab6f-98fc0418fc1d)

do you have any idea what is blocking this connection?
Or What is the problem?

**Comment by dinger1986** [comment]
makes sense

**Comment by teraxionTI** [comment]
I have the same result as you. There doesn't seem to be any error on this side.
![image](https://github.com/rustdesk/rustdesk-server-pro/assets/152305914/74925461-6870-40ef-88a3-c7a1bc732e57)

**Comment by fufesou** [comment]
@teraxionTI Hi, can you please run the attached demo on your server?

Run the command with `-h` for help, or `-i` with the issue.

![image](https://github.com/rustdesk/rustdesk-server-pro/assets/13586388/9d5d59ab-f84a-4aef-b157-5a99104a9c31)


[oidc-discovery-demo.zip](https://github.com/rustdesk/rustdesk-server-pro/files/13510262/oidc-discovery-demo.zip)

**Comment by networkadminasai** [comment]
Did anyone figure this out?

**Comment by fufesou** [comment]
@networkadminasai Hi, do you have the same issue?
Can you please try https://github.com/rustdesk/rustdesk-server-pro/issues/164#issuecomment-1830172976 and https://github.com/rustdesk/rustdesk-server-pro/issues/164#issuecomment-1833299551?
The demo contains executable on Windows, Linux and MacOS.
