### ISSUE TITLE
username@device_name not working 100%

### ISSUE THREAD

**Issue by PVSJT** [rustdesk/rustdesk-server-pro#174]
First of all, thank's  for this great piece of software.

In our company we have been working with RustDesk Pro for a short time to help our users with problems. The server installation and deployment of the RustDesk client on the company's PCs (approx. 160 devices) went smoothly. We have different Branches in different Citys and also Home Office Workers.
If I am now logged in as a licensed user via the RustDesk Client, I can see all the clients installed in the company in the group menu.
I find it particularly helpful (if you don't have a user-specific PC) that the username@device_name is displayed under the ID.

Over the course of the days, however, I noticed that only about half display the user username@device_name, while the others only display the device_name. And which ones are like that changes from day to day.
When I compare my list to the server's web interface, others with the full username@devicename are displayed.
It has nothing to do with where the PC is located - one day it was just the room next door where only the device_name was displayed, the next day the complete username@device_name was displayed again.
I can connect to any of these devices without any problems. 

Any advise or is it a bug?

![08-12-2023_10-54-18](https://github.com/rustdesk/rustdesk-server-pro/assets/153274427/dc291e17-806e-4261-95c8-e283699f924f)
![08-12-2023_11-03-14](https://github.com/rustdesk/rustdesk-server-pro/assets/153274427/ae7f64ef-cb4f-4ee0-bd47-cb89372803e1)

**Comment by 21pages** [comment]
Thanks for your feedback, I reproduced this on the client, and found the database record contains username, the username appears after clicking the refresh button.

**Comment by rustdesk** [comment]
Yes, it is a bug

**Comment by DMSnz** [comment]
> Yes, it is a bug. We just put a fix in RustDesk client, [rustdesk/rustdesk@6003003](https://github.com/rustdesk/rustdesk/commit/6003003228eb935a12610c9b5f772ee579a297eb)

You mention RustDesk client, but you are talking about Pro Console server side code correct?
If so, which release contains the fix?
I am running 1.1.14-1 currently and most of my clients still have no username showing in device column (clients on 1.2.3)

**Comment by rustdesk** [comment]
1.2.4 the nightly build

**Comment by rustdesk** [comment]
1.2.4 current nightly, https://github.com/rustdesk/rustdesk/releases/tag/nightly
