### ISSUE TITLE
How to delete clients from pro console?

### ISSUE THREAD

**Issue by DMSnz** [rustdesk/rustdesk-server-pro#176]
Is there any way to remove/delete a client no longer active / in commission from the devices list in pro console?

If say a machine is retired, or was running rustdesk on demand only, then its ID changes when installed as a service, the old host is still there and seemingly unable to be removed / tidied up.

Cheers

**Comment by rustdesk** [comment]
Disable first, then you can see `delete` button.

**Comment by DMSnz** [comment]
Thanks, is it also therefore normal to not be able to delete active/online devices?
See below, 8 devices 7 of which are online, only the bottom last device is offline and able to be deleted?

![image](https://github.com/rustdesk/rustdesk-server-pro/assets/139725889/8feba520-5130-4651-94e5-0414442032f4)

**Comment by rustdesk** [comment]
Yes
