### ISSUE TITLE
Empty box on "Get Relay Server" after update to 1.1.12-1

### ISSUE THREAD

**Issue by pdifeo** [rustdesk/rustdesk-server-pro#178]
When press on "Get Relay Server" the dialog box show only the icon

<img width="726" alt="image" src="https://github.com/rustdesk/rustdesk-server-pro/assets/8618744/70c90af1-683c-4445-bd85-2742c53dae35">

Regards
PDF

**Comment by rustdesk** [comment]
Thanks

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk-server-pro/releases/tag/1.1.12-2
