### ISSUE TITLE
Device List - assign names to devices without registering as a user

### ISSUE THREAD

**Issue by DMSnz** [rustdesk/rustdesk-server-pro#19]
Maybe I am missing something but with RustDesk Pro Web Console -> Device List

I have a list of devices that have RustDesk client installed, all listed via ID number.
I would like a column for a friendly name to assign to each device which is searchable as it grows.

I believe from a quick look today, that unless a user is added (with password and so on), I can not assign any user to a device.
For clarity this is not a user in any way expected to use RustDesk in any purpose other than being the client whom I connect to for support. It would simply be a friendly name to give a device.

We have 200 or so devices in our company that I intend to support via RustDesk, I need an easy way to assign all those IDs to names of people or names of device, that is also searchable.

I did see the other issue raised about device list, wanting notes column added, worst case a friendly name could be put in the notes field but I do not believe this is the correct use case for that.

Thanks

**Comment by DMSnz** [comment]
Maybe I misunderstand this.
Is this intended to have everyone/device registered, so that controls can be applied via groups and strategies?
Either way I feel a generic field to name devices with a friendly name would be beneficial.

**Comment by rustdesk** [comment]
Renaming on client side does not require user assigned. We are adding note (https://github.com/rustdesk/rustdesk-server-pro/issues/12).

I am also considering to allow rename from the web console.

**Comment by DMSnz** [comment]
Ahhh if we can rename via client that may be enough, but I guess if the install is automated that might be where console side is beneficial.

**Comment by rustdesk** [comment]
Yes, installation automation is quite important. Before with open source self-host, we did ignore this. But now, we need to emphasize on it.

Any suggesions about automiated installation, please propose. I am collecting feedback about this, and decide how to do it in good direction.

@it-boerner  @dinger1986

**Comment by DMSnz** [comment]
Should we start a new issue tracker for installation automation side of things?

**Comment by rustdesk** [comment]
Ok, please

**Comment by it-boerner** [comment]
I think you should be able to have two applications, especially in the pro area.

Once the classic client, with which you can also register.

In addition, there should be a host client that cannot connect to others, but simply displays the ID and password.

This host client should also install using a PowerShell script.

**Comment by rustdesk** [comment]
> In addition, there should be a host client that cannot connect to others, but simply displays the ID and password.

This is called `quick support` version for TeamViewer.

**Comment by rustdesk** [comment]
> In addition, there should be a host client that cannot connect to others, but simply displays the ID and password.

This is called `quick support` version for TeamViewer.

**Comment by it-boerner** [comment]
> > Darüber hinaus sollte es einen Host-Client geben, der keine Verbindung zu anderen herstellen kann, sondern lediglich die ID und das Passwort anzeigt.
> 
> Dies wird als `quick support`Version für TeamViewer bezeichnet.

Yes, that's right, TeamViewer has three different clients.

There is the normal client, then the quick support and finally the host.

**Comment by dinger1986** [comment]
Yes a QS option would be good on the future

**Comment by DMSnz** [comment]
Sounds great, should we yet again start a new thread, possibly a wishlist thread?

**Comment by dinger1986** [comment]
I guess threads per suggestions etc

**Comment by dinger1986** [comment]
adding this here https://github.com/rustdesk/rustdesk/discussions/5007#discussioncomment-6477980 as I think its fitting

**Comment by RichardBurt65** [comment]
I'd like to see endpoint hostnames appear in the Device List. ID number don't help to work out who's machine is who's.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk-server-pro/issues/12

**Comment by DMSnz** [comment]
Commenting here but close again if I am off course ...

I was hoping to get device names (computer hostname) and user that is logged in to those machines, populating in to the RustDesk Pro Console.
I have updated our Console to 1.1.9 and have started rolling out installed versions of RustDesk Client 1.2.2
But yet again these devices just show up with ID numbers and nothing else populated in the Device Name or User columns.
Is this still to come or have I not explained properly what I wanted originally?

The only devices that have device name/user filled out are the ones where I logged in with my Console user/pass which is my own laptop and a server I tested on, all others are blank.

Thanks again

**Comment by rustdesk** [comment]
To make it work, you need to make sure.

- [ ] running 1.2.2
- [ ] the device can access API server.

**Comment by DMSnz** [comment]
Ahh too true think I left API server blank 😆

**Comment by DMSnz** [comment]
Ok device names are now populating
But I guess my bigger issue/request as my comment above, was to have the clients domain / windows / linux? user name in the "User" field
This User field is currently clearly linked to a RustDesk technician/user account.
I was unsure originally as my windows user was the same format as my RustDesk user, so I just created a "test" user and of course instantly in the console my device name now has "User" test.
Sorry to bang on about it, but can we please get a OS user populating in the web console?
The client side address book / discovered tab, shows the windows user name already.

**Comment by User35123** [comment]
@DMSnz What exactly did you to to populate device names without login? im facing the same problem: I only see the name after logging in. The API should work because i can log without any problems. API website is accessible from client device (using https)

**Comment by DMSnz** [comment]
> @DMSnz What exactly did you to to populate device names without login? im facing the same problem: I only see the name after logging in. The API should work because i can log without any problems. API website is accessible from client device (using https)

I believe at the time we updated our docker version to 1.1.9 but with the docker re-creation our license bombed out, so when I initially checked I think it was unlicensed, once fixed that and verified client version was 1.2.2 minimum and API addresses, it all started working.

But to this day I still have issues where the username of the user is not showing 85% of the time, some machines run nearly 24/7 always logged in, shows these hosts online but simply refuses to show username.
Others is works fine so you get user@device showing up nicely.

**Comment by User35123** [comment]
@DMSnz Your current problem sounds like this one: https://github.com/rustdesk/rustdesk-server-pro/issues/174 (fixed) - Maybe you are not using the latest version?

I think i also found the reason for my problem. It _seems_ that RustDesk absolutely do not like TLS connections below version 1.3. That means if your API Server Address is encrypted by TLS_1.2 it will not work. You can log in to your account via the client but all API requests doesnt seem work. Same for secured LDAP connections btw.

-> If this is true, you are doomed if you are running RustDesk Server Pro (for Windows) on a version older than **Windows Server 2022**.

**Comment by DMSnz** [comment]
@User35123 Thanks for that info will indeed be my issue, had not looked into it let alone found that bug and fix.

Good to hear you also seem on track with your issue
