### ISSUE TITLE
Some of My Sites Show As Not Available on RustDesk While Other Sites are Fine

### ISSUE THREAD

**Issue by MerryPickles** [rustdesk/rustdesk-server-pro#191]
Hi. I am running RustDesk on Windows Server 2016 Essentials. I have several client companies with RustDesk installed on all their client computers (Windows environments). As of this last weekend, some of the sites are entirely unavailable for me to remote-control them while other sites are fine. Really odd! I have restarted firewalls all around but problem remains.

**Comment by rustdesk** [comment]
We have a similar report from another user. Eventually they migrated to Linux. Honestly, it is hard for us to give suggestions for networking issue like this.

> It’s quite odd – we can establish a connection only once every few hours. Otherwise, it says we cannot connect to the rendevouz server. The Pro runs on Windows Server 2022.

> I have, however, installed it on a Debian VM and it runs smoothly there, I believe the issue lies in the Windows implementation of the service.

**Comment by rustdesk** [comment]
Can you post your log in C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\log\server\rustdesk_rCURRENT.log?

**Comment by rustdesk** [comment]
Close since no response
