### ISSUE TITLE
RustDesk program no Azure login

### ISSUE THREAD

**Issue by lapetooos** [rustdesk/rustdesk-server-pro#198]
Unfortunately, we no longer have the option of logging into the rust desk windows program with the azure account.

![rustdesk-windows-no-azure-login](https://github.com/rustdesk/rustdesk-server-pro/assets/98172810/b4c78f52-cad0-4c5b-8282-c0a702c14f15)

**Comment by rustdesk** [comment]
@fufesou follow up

**Comment by fufesou** [comment]
@lapetooos Hi, thanks for your feedback. Have you only configured Azure's oidc?

It seems your RustDesk sever does not start successfully or you cannot connect to the server.

**Comment by lapetooos** [comment]
@fufesou yes we only have Azure's OIDC configured.

What can I check to test if my RustDesk server does not start successfully or if I cannot connect to the server?

**Comment by fufesou** [comment]
Can you login the webconsole?

You can find the server `ip:port` here.

![image](https://github.com/rustdesk/rustdesk-server-pro/assets/13586388/fd00d04a-0c52-4904-9386-3574e60a432f)

And then check the connection state.

<img width="593" alt="1707290102017" src="https://github.com/rustdesk/rustdesk-server-pro/assets/13586388/2ad5e0f6-e3a1-4183-93c1-61b92f71ac65">

If the connection state is not ready, please:

1. Check if the server is running on the server machine.
2. Check if network connection is permitted. You can also run `nc <ip> <port>` or `telnet <ip> <port>`

If the connection is ready, please login the web console as user "admin". To check if OIDC configuration is missed.

**Comment by rustdesk** [comment]
Also make sure `API Server` is set correctly.

https://rustdesk.com/docs/en/self-host/client-configuration/#set-api-server
