### ISSUE TITLE
Adding -- to the end of the license config string, makes the license unrecognized

### ISSUE THREAD

**Issue by AlvaroNieto** [rustdesk/rustdesk-server-pro#204]
A per stated in https://rustdesk.com/docs/en/self-host/client-configuration/#add----to-the-name 

_rustdesk-licensed--{encrypted string}--.exe_ 

The license doesn't get applied following that instructions. If I remove the -- from the end, the license works. Tested in 1.2.3 and 1.2.3-1, Windows.

In the docs, there are 2 diferent strings (the first and generated by the server, and the second, written in the docs), tested both:

_rustdesk-licensed-{encrypted string}--.exe
rustdesk-licensed--{encrypted string}--.exe_

Using the host and key method with the comma works fine.

**Comment by rustdesk** [comment]
Per the source code, the doc is wrong.

https://github.com/rustdesk/rustdesk/blob/09325fadaff53b82ae6f2e5e66d9e0a6cf2e3104/src/license.rs#L87

`--` works if there is no `-licensed-`
