### ISSUE TITLE
Passwort Reset - Verification Code

### ISSUE THREAD

**Issue by Tygera** [rustdesk/rustdesk-server-pro#206]
Hi all, 

when trying to reset the password, the provided authentication code is not working. 

This is the error displayed:
![grafik](https://github.com/rustdesk/rustdesk-server-pro/assets/44202761/5f94bc3e-5d2d-4362-88ab-94139919fdb3)

The E-Mail arrives quickly. I assured the clocks are synced in the docker containers and that SMTP works. Everything else works so far. 
Couldn't find anything in the logs either. Any way to debug this further?

Best 
Pascal

**Comment by rustdesk** [comment]
@fufesou follow up

**Comment by rustdesk** [comment]
@Tygera Thanks for your report, I can reproduce it.

**Comment by rustdesk** [comment]
Fixed, https://github.com/rustdesk/rustdesk-server-pro/releases/tag/1.1.14-7
