### ISSUE TITLE
Some questions and problems

### ISSUE THREAD

**Issue by Apashh** [rustdesk/rustdesk-server-pro#21]
Hello,

If you want, I'll let you create multiple issues for all the different requests below.
I purchased Rustdesk Pro (personal).

- STRATEGY: Who does the default strategy apply to? If it's for equipment without a group, it doesn't work when modified default strategy.
- STRATEGY: Creating a strategy: when we include a group in it, if a new equipment arrives in that group, the strategy is not applied even though it belongs to the group. It is necessary to manually check the equipment in the strategy. It should be done automatically as soon as we add it to the group.
- Created STRATEGY: Even though we add an equipment to the strategy, it doesn't apply, it doesn't work.
- EQUIPMENT: When an equipment arrives, it should be possible to assign a default group and user instead of User: - and Group: -.
- GLOBAL: Being able to connect to a public Rustdesk ID not hosting it on our servers while remaining connected to our hosted server.
- GLOBAL: Auto-configuration and QR code don't work, or maybe I don't understand how they work. I tried renaming the EXE file as indicated on the web interface, but it doesn't work. Similarly, with a smartphone running iOS and Android, I scanned the QR code, but it doesn't lead to anything.
- API: What does it consist of? Does its port work with TCP/UDP? Both?
- LOG: Does it use a specific port? Personally, since upgrading to the license, I don't have any connection or file transfer logs. I only have those from the console. I tried putting all the equipment in the same group, but no logs appear.
- SMTP: I can't configure my SMTP (with OVH) with port 465 or 25. It might be worth considering allowing SSL/TLS?
- GROUPS: If we allow Group A to access Group B, Group A cannot access Group B. However, if I remove my equipment from Group B, Group A can access it.
- GLOBAL: As an admin, we can't modify our own assigned group. If we create a secondary admin, we can modify it.

Thank you for reading. If necessary, I can provide screenshots and logs.
Best regards,

Apash

**Comment by 21pages** [comment]
https://rustdesk.com/docs/en/self-host/pro/strategy/
> Who does the default strategy apply to

If enabled, applied to devices not belong to any other strategies; if not enabled, not applied to any device.

> when we include a group in it

Can't apply to device group, device group is used for filter, it's applied to devices.

> Even though we add an equipment to the strategy, it doesn't apply, it doesn't work.

When you create a new one, it's not enabled at first, you need to enable it.

**Comment by rustdesk** [comment]
> * API: What does it consist of? Does its port work with TCP/UDP? Both?

API is the 21114 port, the web console you are using.

**Comment by rustdesk** [comment]
> LOG: Does it use a specific port? Personally, since upgrading to the license, I don't have any connection or file transfer logs. I only have those from the console. I tried putting all the equipment in the same group, but no logs appear.
> GROUPS: If we allow Group A to access Group B, Group A cannot access Group B. However, if I remove my equipment from Group B, Group A can access it.

@dinger1986 Could you help test and confirm this?

**Comment by rustdesk** [comment]
> * GLOBAL: Being able to connect to a public Rustdesk ID not hosting it on our servers while remaining connected to our hosted server.

A lot of discussion about this, we have no plan to support this yet. Also we may close public servers one day because I receive scammer report every week.

**Comment by rustdesk** [comment]
> * EQUIPMENT: When an equipment arrives, it should be possible to assign a default group and user instead of User: - and Group: -.

I do not think this make sense, but I am willing to listen to more voice about this. Since this is Pro, we will develop it based on users' feedback.

**Comment by rustdesk** [comment]
> * GLOBAL: Auto-configuration and QR code don't work, or maybe I don't understand how they work. I tried renaming the EXE file as indicated on the web interface, but it doesn't work. Similarly, with a smartphone running iOS and Android, I scanned the QR code, but it doesn't lead to anything.

Please use the latest apk on github, the ones on google play or apple store are old.

**Comment by dinger1986** [comment]
> > LOG: Does it use a specific port? Personally, since upgrading to the license, I don't have any connection or file transfer logs. I only have those from the console. I tried putting all the equipment in the same group, but no logs appear.
> 
> > GROUPS: If we allow Group A to access Group B, Group A cannot access Group B. However, if I remove my equipment from Group B, Group A can access it.
> 
> 
> 
> @dinger1986 Could you help test and confirm this? I did test before publish.

Sure I'll check

**Comment by rustdesk** [comment]
> * GLOBAL: As an admin, we can't modify our own assigned group. If we create a secondary admin, we can modify it.

Will fix

**Comment by rustdesk** [comment]
> * GLOBAL: Auto-configuration and QR code don't work, or maybe I don't understand how they work. I tried renaming the EXE file as indicated on the web interface, but it doesn't work. Similarly, with a smartphone running iOS and Android, I scanned the QR code, but it doesn't lead to anything.

Also please test this one, though I did test before.

**Comment by rustdesk** [comment]
> * LOG: Does it use a specific port? Personally, since upgrading to the license, I don't have any connection or file transfer logs. I only have those from the console. I tried putting all the equipment in the same group, but no logs appear.

The API (21114) you mentioned is for this. You have to make sure the controlled device can access this port.

**Comment by dinger1986** [comment]
> > > LOG: Does it use a specific port? Personally, since upgrading to the license, I don't have any connection or file transfer logs. I only have those from the console. I tried putting all the equipment in the same group, but no logs appear.
> > 
> > 
> > > GROUPS: If we allow Group A to access Group B, Group A cannot access Group B. However, if I remove my equipment from Group B, Group A can access it.
> > 
> > 
> > @dinger1986 Could you help test and confirm this? I did test before publish.
> 
> Sure I'll check

Logs work fine for me, just tested transferring files etc and all shows up as it should.

**Comment by Apashh** [comment]
> > > > LOG: Does it use a specific port? Personally, since upgrading to the license, I don't have any connection or file transfer logs. I only have those from the console. I tried putting all the equipment in the same group, but no logs appear.
> > > 
> > > 
> > > > GROUPS: If we allow Group A to access Group B, Group A cannot access Group B. However, if I remove my equipment from Group B, Group A can access it.
> > > 
> > > 
> > > @dinger1986 Could you help test and confirm this? I did test before publish.
> > 
> > 
> > Sure I'll check
> 
> Logs work fine for me, just tested transferring files etc and all shows up as it should.

21114 is open, my client is connected to API, any block on my firewall, and i have this : 
![image](https://github.com/rustdesk/rustdesk-server-pro/assets/83477029/6d5757ee-7653-47b8-8f5b-96cb5ac678a9)

**Comment by Apashh** [comment]
> > * GLOBAL: As an admin, we can't modify our own assigned group. If we create a secondary admin, we can modify it.
> 
> Will fix

Ok ! :)

**Comment by Apashh** [comment]
> 

Ok! But how work QR Code for iphone or android ? And EXE we just need to rename exe ?

**Comment by Apashh** [comment]
> > * GLOBAL: Auto-configuration and QR code don't work, or maybe I don't understand how they work. I tried renaming the EXE file as indicated on the web interface, but it doesn't work. Similarly, with a smartphone running iOS and Android, I scanned the QR code, but it doesn't lead to anything.
> 
> Please use the latest apk on github, the ones on google play or apple store are old.

Ok! But how work QR Code for iphone or android ? And EXE we just need to rename exe ?

**Comment by dinger1986** [comment]
> > * GLOBAL: Auto-configuration and QR code don't work, or maybe I don't understand how they work. I tried renaming the EXE file as indicated on the web interface, but it doesn't work. Similarly, with a smartphone running iOS and Android, I scanned the QR code, but it doesn't lead to anything.
> 
> @dinger1986 Also please test this one, though I did test before.

Working fine for me, tested Android App (1.2.1) and scanned QR code and it showed up the settings.

For windows, I needed to make sure any old configs were gone before it worked but otherwise fine and installs and takes the settings fine, this to me should be resolved and something I raised before

**Comment by Apashh** [comment]
> 

Ok but my strategy "default" is active and when i edit it don't apply on all devices...
So, we can't add auto a device to group and group apply strategy for all new device ?

**Comment by Apashh** [comment]
> https://rustdesk.com/docs/en/self-host/pro/strategy/
> 
> > Who does the default strategy apply to
> 
> If enabled, applied to devices not belong to any other strategies; if not enabled, not applied to any device.
> 
> > when we include a group in it
> 
> Can't apply to device group, device group is used for filter, it's applied to devices.
> 
> > Even though we add an equipment to the strategy, it doesn't apply, it doesn't work.
> 
> When you create a new one, it's not enabled at first, you need to enable it.
> 
> By the way, did you set the api server on the client?

Ok but my strategy "default" is active and when i edit it don't apply on all devices...
So, we can't add auto a device to group and group apply strategy for all new device ?

**Comment by Apashh** [comment]
> > > > > > LOG: Does it use a specific port? Personally, since upgrading to the license, I don't have any connection or file transfer logs. I only have those from the console. I tried putting all the equipment in the same group, but no logs appear.
> > > > > 
> > > > > 
> > > > > > GROUPS: If we allow Group A to access Group B, Group A cannot access Group B. However, if I remove my equipment from Group B, Group A can access it.
> > > > > 
> > > > > 
> > > > > @dinger1986 Could you help test and confirm this? I did test before publish.
> > > > 
> > > > 
> > > > Sure I'll check
> > > 
> > > 
> > > Logs work fine for me, just tested transferring files etc and all shows up as it should.
> > 
> > 
> > 21114 is open, my client is connected to API, any block on my firewall, and i have this : ![image](https://user-images.githubusercontent.com/83477029/253952259-6d5757ee-7653-47b8-8f5b-96cb5ac678a9.png)
> 
> are you using http://IPADDRESS or DNSADDRESS:21114 for your API server address on RustDesk?

I use DNS record https://mydns:21114

**Comment by Apashh** [comment]
> Is OVH maybe blocking smtp?
> 
> Have you tested from the terminal?

I use OVH for multiple app, tested in command line with SSL : port 465 : ssl0.ovh.net with username and pass :)

**Comment by rustdesk** [comment]
> So, we can't add auto a device to group and group apply strategy for all new device ?

This logic we learn from splashtop，we did consider adding group, but late we decide not over design and follow splashtop. But we keep open this, we may change after receiving enough feedback from Pro users.

**Comment by rustdesk** [comment]
> https://mydns:21114

works on machine's browser ?

**Comment by rustdesk** [comment]
> the newer config should overwrite the old config or, the configs in the exe should work for a one time purpose

renaming in exe does not write new config.

**Comment by rustdesk** [comment]
> Working fine for me, tested Android App (1.2.1) and scanned QR code and it showed up the settings fine

How about GROUPS?

**Comment by dinger1986** [comment]
> > > > > > > LOG: Does it use a specific port? Personally, since upgrading to the license, I don't have any connection or file transfer logs. I only have those from the console. I tried putting all the equipment in the same group, but no logs appear.
> > > > > > 
> > > > > > 
> > > > > > > GROUPS: If we allow Group A to access Group B, Group A cannot access Group B. However, if I remove my equipment from Group B, Group A can access it.
> > > > > > 
> > > > > > 
> > > > > > @dinger1986 Could you help test and confirm this? I did test before publish.
> > > > > 
> > > > > 
> > > > > Sure I'll check
> > > > 
> > > > 
> > > > Logs work fine for me, just tested transferring files etc and all shows up as it should.
> > > 
> > > 
> > > 21114 is open, my client is connected to API, any block on my firewall, and i have this : ![image](https://user-images.githubusercontent.com/83477029/253952259-6d5757ee-7653-47b8-8f5b-96cb5ac678a9.png)
> > 
> > 
> > are you using http://IPADDRESS or DNSADDRESS:21114 for your API server address on RustDesk?
> 
> I use DNS record https://mydns:21114

how are you handling https?

**Comment by dinger1986** [comment]
> > the newer config should overwrite the old config or, the configs in the exe should work for a one time purpose
> 
> renaming in exe does not write new config, it writes to regedit after installing. config has higher priority than renaming in exe.

Yeah I know :), but it should have a higher priority!

**Comment by rustdesk** [comment]
> the rename should have a higher priority!

I do not think so.

**Comment by dinger1986** [comment]
> > the rename should have a higher priority!
> 
> I do not think so.

so how are you dealing with people using it as a one off? like my example https://github.com/rustdesk/rustdesk-server-pro/issues/17

**Comment by Apashh** [comment]
> > https://mydns:21114
> 
> works on machine's browser ?

Work when open 21114 but it open also the wbesite, we can't access api with other port and deny web console to local network ?

**Comment by rustdesk** [comment]
> so how are you dealing with people using it as a one off?

Frankly I never thought about this when I design renaming exe.

**Comment by Apashh** [comment]
> > > * GLOBAL: Auto-configuration and QR code don't work, or maybe I don't understand how they work. I tried renaming the EXE file as indicated on the web interface, but it doesn't work. Similarly, with a smartphone running iOS and Android, I scanned the QR code, but it doesn't lead to anything.
> > 
> > 
> > @dinger1986 Also please test this one, though I did test before.
> 
> Working fine for me, tested Android App (1.2.1) and scanned QR code and it showed up the settings fine
> 
> For windows, I needed to make sure any old configs were gone before it worked but otherwise fine and installs and takes the settings fine, this to me should be resolved, the newer config should overwrite the old config or, the configs in the exe should work for a one time purpose, thats my thoughts anyways @21pages @rustdesk probably is the same on windows, linux and mac

Can you give me a tutorial to setup exe and android ?

**Comment by dinger1986** [comment]
> > Working fine for me, tested Android App (1.2.1) and scanned QR code and it showed up the settings fine
> 
> How about GROUPS?

yeah didnt work for me either 
![image](https://github.com/rustdesk/rustdesk-server-pro/assets/7244447/aedfd576-e2db-4dbd-bc04-6f11703cb235)

**Comment by rustdesk** [comment]
> Yeah I know :), but the rename should have a higher priority!

When you let renaming has higher priority, the other people will ask why I can not change server on GUI.

**Comment by dinger1986** [comment]
> > > > * GLOBAL: Auto-configuration and QR code don't work, or maybe I don't understand how they work. I tried renaming the EXE file as indicated on the web interface, but it doesn't work. Similarly, with a smartphone running iOS and Android, I scanned the QR code, but it doesn't lead to anything.
> > > 
> > > 
> > > @dinger1986 Also please test this one, though I did test before.
> > 
> > 
> > Working fine for me, tested Android App (1.2.1) and scanned QR code and it showed up the settings fine
> > For windows, I needed to make sure any old configs were gone before it worked but otherwise fine and installs and takes the settings fine, this to me should be resolved, the newer config should overwrite the old config or, the configs in the exe should work for a one time purpose, thats my thoughts anyways @21pages @rustdesk probably is the same on windows, linux and mac
> 
> Can you give me a tutorial to setup exe and android ?

I am going to write this up for FAQs but basically do the following:

1. Download the clients from https://github.com/rustdesk/rustdesk/releases/tag/1.2.1
2. click on Windows EXE (this should be renamed to configs)
3. Fill in the info in the boxes required 
4. Scan QR code on Android and rename exe to what it says

![image](https://github.com/rustdesk/rustdesk-server-pro/assets/7244447/31a681be-d4c3-4570-af13-8c6be23ab141)

**Comment by dinger1986** [comment]
> > Yeah I know :), but the rename should have a higher priority!
> 
> When you let renaming has higher priority, the other people will ask why I can not change server on GUI.

if its not installed and run as a one time then the rename should take priority, either way it should be able to overwrite the toml files with new configs, otherwise you need to remove old configs and then install which is a bit messy

**Comment by rustdesk** [comment]
> if its not installed and run as a one time then the rename should take priority, either way it should be able to overwrite the toml files with new configs, otherwise you need to remove old configs and then install which is a bit messy

Does this discussion have this problem?

**Comment by rustdesk** [comment]
> > > the rename should have a higher priority!
> > 
> > 
> > I do not think so.
> 
> so how are you dealing with people using it as a one off? like my example #17

I just tested it works. But I know the reason. The controlling side's group is decided by the user you logged in not by the user you assign from web console, you believe you have not logged in yet. We design so, because some controlling side deos not have device id, e.g. iOS client and web client.

**Comment by dinger1986** [comment]
I logged in as those users on both devices, not the web console

**Comment by rustdesk** [comment]
> I logged in as those users on both devices, not the web console

Have you assigned cross-group?

**Comment by it-boerner** [comment]
> > Wir können also nicht automatisch ein Gerät zur Gruppe hinzufügen und die Gruppenstrategie nicht auf alle neuen Geräte anwenden?
> 
> Neue Geräte werden automatisch zur Standardstrategie hinzugefügt.

However, this does not yet work in the current version of RustDesk-Pro (1.1.8). I had to add all clients manually.

**Comment by it-boerner** [comment]
> > > > > * GLOBAL: Autokonfiguration und QR-Code funktionieren nicht, oder vielleicht verstehe ich nicht, wie sie funktionieren. Ich habe versucht, die EXE-Datei wie auf der Weboberfläche angegeben umzubenennen, aber es funktioniert nicht. Ebenso habe ich mit einem Smartphone mit iOS und Android den QR-Code gescannt, aber er führt zu nichts.
> > > > 
> > > > 
> > > > @dinger1986Bitte testen Sie auch dieses, obwohl ich es schon vorher getestet habe.
> > > 
> > > 
> > > Funktioniert bei mir einwandfrei, ich habe die Android-App (1.2.1) getestet und den QR-Code gescannt und die Einstellungen wurden einwandfrei angezeigt. 
> > > Unter Windows musste ich sicherstellen, dass alle alten Konfigurationen entfernt waren, bevor es funktionierte, aber ansonsten funktionierte es einwandfrei und die Installation und die Einstellungen wurden einwandfrei übernommen , das sollte für mich gelöst sein, die neuere Konfiguration sollte die alte Konfiguration überschreiben oder die Konfigurationen in der Exe sollten für einen einmaligen Zweck funktionieren, das ist jedenfalls meine Meinung@21pages @rustdeskWahrscheinlich ist es unter Windows, Linux und Mac dasselbe
> > 
> > 
> > Können Sie mir ein Tutorial zum Einrichten von Exe und Android geben?
> 
> Ich werde dies für die FAQs aufschreiben, aber im Grunde gehe ich wie folgt vor:
> 
> 1. Laden Sie die Clients von [https://github.com/rustdesk/rustdesk/releases/tag/1.2.1 herunter](https://github.com/rustdesk/rustdesk/releases/tag/1.2.1)
> 2. Klicken Sie auf Windows EXE (dieses sollte in configs umbenannt werden)
> 3. Geben Sie die Informationen in die erforderlichen Felder ein
> 4. Scannen Sie den QR-Code auf Android und benennen Sie die EXE-Datei entsprechend um
> 
> ![Bild](https://user-images.githubusercontent.com/7244447/253961707-31a681be-d4c3-4570-af13-8c6be23ab141.png)

With the current version of the app on iOS, no registration or QR code works. It always shows that the QR code is wrong.

**Comment by rustdesk** [comment]
> iOS

We have not updated iOS yet.

**Comment by it-boerner** [comment]
> > iOS
> 
> Wir haben iOS noch nicht aktualisiert.

I know I'm just giving you the hint of the problems ;)

**Comment by dinger1986** [comment]
> > I logged in as those users on both devices, not the web console
> 
> Have you assigned cross-group correctly?

sorry missed that step! works fine now, shall be adding afew things to the docs from this thread :)

1. Add new Groups
2. Click Edit 
3. Select the relevant groups you want access (it automatically adds them in the corresponding group).
![image](https://github.com/rustdesk/rustdesk-server-pro/assets/7244447/b4610e06-86c4-4295-babc-a7c3ac0bfc52)

**Comment by dinger1986** [comment]
> > > iOS
> > 
> > 
> > Wir haben iOS noch nicht aktualisiert.
> 
> I know I'm just giving you the hint of the problems ;)

there is no problem other than I need to write up more docs to make it easier for people

**Comment by rustdesk** [comment]
> > > Yeah I know :), but the rename should have a higher priority!
> > 
> > 
> > When you let renaming has higher priority, the other people will ask why I can not change server on GUI.
> 
> if its not installed and run as a one time then the rename should take priority, either way it should be able to overwrite the toml files with new configs, otherwise you need to remove old configs and then install which is a bit messy

Yes, it messy. The renaming was implemented very early, at that time, I do not need to consider these problems as an open source maintainer. But now, we need to serve Pro users, so it is time to change.

**Comment by it-boerner** [comment]
I agree with you because the process has already started with the Pro version and certain performances are expected. That's always the problem
