### ISSUE TITLE
Add setting: Require account login to connect on remote control end

### ISSUE THREAD

**Issue by ZetaWaves** [rustdesk/rustdesk-server-pro#226]
Please add a setting on the server that will require anyone connecting to another machine to be logged in first.

Specific feature request:
-Add a way to require a user to be logged in, in order to connect to other computers.

**Comment by rustdesk** [comment]
No problem.

**Comment by ZetaWaves** [comment]
This has been completed: https://github.com/rustdesk/rustdesk-server-pro/releases/tag/1.3.5

Thank you, @rustdesk  :)
