### ISSUE TITLE
Add setting: Ability to log in on Incoming Only custom clients

### ISSUE THREAD

**Issue by alt-st0rm** [rustdesk/rustdesk-server-pro#232]
We've been testing the custom clients in our environment and the customization and branding options make for a great support tool experience for the average user, adding a layer of trust of branded remote support tools while distrusting non-corparetly branded remote tools.

However, we've noticed that the "Incoming Only" custom client setting disables the user account login by default, with no way to alow an user to log in. 

### **USE CASE**
I think having the option to log in would be benefitial for the following use case:

- There are different "receiving" user types. For example, a normal employee pc and a pc connected to a machine.
- The IT helpdesk group should only be able to connect to the employees, while a **technician group** would be able to connect to the pc connected to the machine.

This way the machine's client is incoming only, has branding and is limited to the **technician group**.
This would let the normal client's granularity to be applied to custom clients with the incoming only mode.

### **WORKAROUND**
The current workaround is creating a **bidirectional** client and limiting access via a strategy (applied to the user that's logged on the receiving client) that limits the incoming IPs to those of the technicians.

**Comment by rustdesk** [comment]
Yes, it is our fault.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk-server-pro/releases/tag/1.3.1
