### ISSUE TITLE
Auto delete of offline devices

### ISSUE THREAD

**Issue by itxpress** [rustdesk/rustdesk-server-pro#234]
Just got our server upgraded to v1.3 to get custom clients and wow. Impressive setup. Easy to use and manage! Plus we finally get easy to use Mac capability. We're an MSP and use RustDesk primarily as our 'Plan B' remote access for clients that we don't manage with our RMM systems or if we can't connect via our RMM to a contracted client. Think Teamviewer QuickSupport (which we used to use until their prices went off the charts). They download off our website and we can login. When we're done. We're done. Our custom client is setup just like that. Incoming only, no install option, just the ID and PW. But have a question about managed devices. Initially I thought that was related to actively connected devices. But suddenly this week, anytime someone downloaded our client, we couldn't connect 'Remote device is disabled'. Under devices, all recent devices were disabled. Then almost by accident playing around with API logins, I actually got a device limit reached error. OK - that makes sense. We had 117 devices in the list. I disabled and deleted some devices, and all was well. So what is the best way for us to manage this? We do have a handful of devices that have RustDesk installed as a service, but the vast majority are quick support connections. I could group the 24x7 access devices and then filter the list, select all, and disable. But then the problem is if someone calls us back a month later - we'll be blocked from connecting to them until we manually enable them. I could delete them - but you can't mass delete and have to enter the device ID in a popup to delete (which I understand the goal there). Is there any way for a quick support like device connection to be temporary and then fall off the list? We don't care if someone who called back a month later got a new ID. Or am I missing something obvious? I realize this is a side use case for, say, managing an infrastructure of machines - but figured I'd see if anyone else had run into this.

Maybe add the ability to auto delete offline devices after X days?

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk-server-pro/discussions/182
