### ISSUE TITLE
Custom client MSI missing branding logo after installation

### ISSUE THREAD

**Issue by ZetaWaves** [rustdesk/rustdesk-server-pro#239]
Custom client MSI missing branding logo after installation. The icon after installation is the default RustDesk icon, but should be the branded logo like the normal executable.

UPDATE: This is still a problem. I did a new build, still has regular icon and now the service isn't started after installation.

**Comment by rustdesk** [comment]
You  can install on another machine, it is probably because of icon cache.

**Comment by ZetaWaves** [comment]
> You can try install new msi on another machine, it is probably because of icon cache.
> 
> About service, how do you install? fresh install / repair / uninstall+install?

I uninstalled previous, then installed new one.

**Comment by alt-st0rm** [comment]
> You can try install new msi on another machine, it is probably because of icon cache.
> 
> About service, how do you install? fresh install / repair / uninstall+install?

I've attempted the install on 3 different machines and I have the same issue. (Having an MSI is extremely helpful, since the deployment via GPO doesn't need the powershell script anymore)
It has happened on:

- A fresh install on a fresh computer that had nothing else installed (blank canvas we use for testing)
- A fresh install on a computer with other programs
- A fresh install on a computer with the default RustDesk client

The default RustDesk icon is shown in:

- The Control Panel
- The Desktop Shortcut
- The TaskBar icon once it's running

Otherwise, curiously, the custom icon is present on the top left of the executable's window once it's running.

**Comment by rustdesk** [comment]
Please follow this https://www.howtogeek.com/687096/how-to-extract-an-icon-from-a-windows-exe-file/ to tell which one is default.

**Comment by alt-st0rm** [comment]
> Please help follow this https://www.howtogeek.com/687096/how-to-extract-an-icon-from-a-windows-exe-file/ to find out which one is default.

The icon shown by IconViewer is the same as the one I use to generate the client, I think the issue could be in the Shortcut generation.

However, I am able to see using [Orca ](https://learn.microsoft.com/en-us/windows/win32/msi/orca-exe) and exploring the .MSI that the **Icon** table's binary data contains the default RustDesk icon. To reproduce this:

- Open the .MSI file with Orca
- Access the Icon table
- On the AppIcon row, double click Binary Data
- Select Write binary to filename
- Save the resulting binary as a .ico on whichever folder you wish

The resulting .ico is the default RustDesk icon.
![2](https://github.com/rustdesk/rustdesk-server-pro/assets/152306147/913693fc-c9d1-4489-b9ba-0eb4d3254682)

When the MSI generates the shortcuts, it appears to use the  **Shortcut** table, which in of itself references the **AppIcon** on the **Icon_** column. 
![1](https://github.com/rustdesk/rustdesk-server-pro/assets/152306147/f89f9d8d-85cf-4890-92ea-f582e61f3101)

I don't have much experience with MSI generation, hopefully that helps a bit at least :) .

**Comment by rustdesk** [comment]
Thank you so much, you may find the cause, I will fix the msi icon.

**Comment by fufesou** [comment]
@ZetaWaves @alt-st0rm Hi, this issue is fixed. Please try again when you are free.

**Comment by alt-st0rm** [comment]
> @ZetaWaves @alt-st0rm Hi, this issue is fixed. Please try again when you are free.

Thank you for the quick update :)

I generated a couple of clients, a fresh one and rebuilt one of the ones I already had:

- **Fresh**: Generated with no issues, icon and logo are correctly set up.
- **Rebuilt**: MSI Fails and returns error code **2753**. However, by changing the **Application Name** on the RustDesk control panel and building the client again this issue was **fixed**. Unsure what's going on with that error.

Otherwise, I am able to correctly build, install and deploy the .msi without any issue.

Thanks for the fix!

**Comment by fufesou** [comment]
> MSI Fails and returns error code 2753.

Can you please help reinstall with the command to find the error?
```
msiexec /i package.msi /l*v install.log
```

It will record the errors in install.log.

**Comment by alt-st0rm** [comment]
> > MSI Fails and returns error code 2753.
> 
> Can you please help reinstall with the command to find the error?
> 
> ```
> msiexec /i package.msi /l*v install.log
> ```
> 
> It will record the errors in install.log.

Certainly. I've attached it here.

[install.log](https://github.com/rustdesk/rustdesk-server-pro/files/15126687/install.log)

**Comment by fufesou** [comment]
@alt-st0rm Thanks

The error log says

> DEBUG: Error 2753:  The File 'App.exe' is not marked for installation.
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2753. The arguments are: App.exe, , 
MSI (s) (C8:D0) [09:02:29:860]: Product: My-Remote-Support -- The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2753. The arguments are: App.exe, , 

You can delete attachments to avoid any private information being revealed.

I can't figure out why, but I found an answer that might help https://stackoverflow.com/a/64974912/1926020

I don’t know if the application with the same name was not totally uninstalled.

Can you please help check? Thanks.

**Comment by fufesou** [comment]
Maybe there are some clues in "Event Viewer" too

<img width="851" alt="1714117924315" src="https://github.com/rustdesk/rustdesk-server-pro/assets/13586388/68ef592f-2097-463d-825d-ff5dddfa8d82">

**Comment by alt-st0rm** [comment]
@fufesou 
I ran the tool listed in the stackoverflow link and it seems to have fixed it. When ran, it detected that the application was still installed somehow, I've also removed the files on AppData\Roaming to be sure and restarted the PC again. After all of this, it installed correctly.

As for the event viewer, I couldn't really see anything that the install.log didn't already tell us.
![msierror2](https://github.com/rustdesk/rustdesk-server-pro/assets/152306147/d5a458b5-47c5-4d6d-b55c-40507bc371dc)

I'm not sure what happened, as you mentioned it may be possible it wasn't fully uninstalled for some reason.

**Comment by fufesou** [comment]
> I've also removed the files on AppData\Roaming to be sure and restarted the PC again.

The data in `AppData\Roaming` should not affect.

Maybe restarting solves the issue.

Thanks for you help again.

**Comment by rustdesk** [comment]
@ZetaWaves @alt-st0rm msi still can not install the service?

**Comment by alt-st0rm** [comment]
> @ZetaWaves @alt-st0rm msi still can not install the service? Do you run directly or via Ansible etc?

I was able to install the MSI after the steps I mentioned above, ran it directly from the MSI and via GPO.

**Comment by ZetaWaves** [comment]
This has been resolved. Thank you.
