### ISSUE TITLE
How should LDAP be setup?

### ISSUE THREAD

**Issue by dinger1986** [rustdesk/rustdesk-server-pro#24]
LDAP – I’m not sure what’s needed here. I don’t have the option to set a bind DN/password, and regardless of what base DN I set I get the following error:
LDAP operation result: rc=49 (invalidCredentials), dn: "", text: "80090308: LdapErr: DSID-0C090439, comment: AcceptSecurityContext error, data 52e, v4563"
I’ve tried several versions with DNs for groups, DNs for various user-containing OU, and just using the root DN but it’s all the same. Is there any way I could get some assistance or further information on this? Additionally, are there plans to implement (if it’s not already?) a more fleshed out filtering option? We generally utilize security group filtering for our LDAP-Enabled services to i.e., only allow users added to the “RustDesk Users”  group to authenticate, and “RustDesk Admins” to administer?

**Comment by rustdesk** [comment]
Will add bind DN / password  field on LDAP settings page in next version.

**Comment by rustdesk** [comment]
> a more fleshed out filtering option? We generally utilize security group filtering for our LDAP-Enabled services to i.e., only allow users added to the “RustDesk Users” group to authenticate, and “RustDesk Admins” to administer?

We need to collect more feedback before taking actions.

**Comment by dinger1986** [comment]
> Will add bind DN / password fields on LDAP settings page in next version.

Great, I am happy to test this with active directory later today if theres some rough guides

**Comment by rustdesk** [comment]
I tested with LDAP server on Linux, I do not know how to use it with Active Directory.

**Comment by dinger1986** [comment]
ok, do you have a rough guide for linux ldap? I can figure out AD hopefully :)

**Comment by rustdesk** [comment]
No guid, it is very basic LDAP knowledge.

**Comment by dinger1986** [comment]
this is how freenas does it for Linux LDAP:
![image](https://github.com/rustdesk/rustdesk-server-pro/assets/7244447/ca7ab46a-ee7b-425b-9c47-3979d6ce30f8)

This is how its done for Active Directory:
![image](https://github.com/rustdesk/rustdesk-server-pro/assets/7244447/e3bf6398-56e2-4402-b065-4d9e1c436efd)

**Comment by rustdesk** [comment]
<img width="617" alt="image" src="https://github.com/rustdesk/rustdesk-server-pro/assets/71636191/d2b4d963-ceeb-452f-bf68-8d9479d410d0">

**Comment by rustdesk** [comment]
<img width="640" alt="image" src="https://github.com/rustdesk/rustdesk-server-pro/assets/71636191/2e69542e-3e97-46ec-a42f-aa912aa12daf">

**Comment by dinger1986** [comment]
yeah I know that :) but yeah it needs a password

**Comment by dinger1986** [comment]
thats all freenas is doing but calling it Active directory, LDAP after all is LDAP

**Comment by rustdesk** [comment]
Frankly, I have very limited knowledge on LDAP, the only my expeirencne is log in to company's computer with AD account.

**Comment by dinger1986** [comment]
I am happy to help as always

**Comment by rustdesk** [comment]
Please test AD, and write a guide for AD user.

**Comment by dinger1986** [comment]
so I have setup on a customers site which has AD, I have configured the cn, ou and dc as it should be, this command `dsquery user -name test1` gets the correct details and I get this 

![image](https://github.com/rustdesk/rustdesk-server-pro/assets/7244447/531f9a9b-855c-4189-98b3-b4adfa89afbd)

**Comment by dinger1986** [comment]
I have tested and it definitely checks the dns name and port but the cn, ou and dc can literally be anything and it doesnt verify

**Comment by DMSnz** [comment]
I would expect most if not all LDAP servers to demand authentication by default, this would then certainly need a password provided, else you are making an unauthenticated / anonymous call to LDAP which is not secure and therefore reasoning most of the time disabled.
We run Samba emulating AD and it demands a user and pass, I can not see how to provide that in the web console LDAP set up

Also search filters could be beneficial if using LDAP, to filter by Users only, ignoring Groups or other use cases.

**Comment by todaysoftware** [comment]
Are you able to confirm that the LDAP connection is encrypted (using the STARTTLS extension)?

**Comment by rustdesk** [comment]
STARTTLS added in 1.1.9
