### ISSUE TITLE
Custom Android client build ends in ErrNo2

### ISSUE THREAD

**Issue by DMSnz** [rustdesk/rustdesk-server-pro#240]
As per screen snip, custom android client, upon build it completes with an ErrNo2 No Such File or Directory "apk name"
RustDesk Server: 1.3.2 on Docker

![image](https://github.com/rustdesk/rustdesk-server-pro/assets/139725889/b02a384c-ac53-41fe-b7a8-4878d88f0aa5)

**Comment by rustdesk** [comment]
Try again please.

**Comment by DMSnz** [comment]
> Try again please.

Tried build same test1 again - failed
Tried a completely new android build, also failed same errors.

**Comment by rustdesk** [comment]
Please use a valid package name, e.g. `a.b.c` rather than `a.b.c.d`. I will add more check on th web.

**Comment by DMSnz** [comment]
First attempt had package name com.dms.rustdesk
second had same but .ck65 at the end

**Comment by rustdesk** [comment]
Please do not use rustdesk in the package name.

**Comment by DMSnz** [comment]
> Please do not use rustdesk in the package name.

Success haha my bad
