### ISSUE TITLE
Client deployment, exe vs MSI

### ISSUE THREAD

**Issue by mmallejac** [rustdesk/rustdesk-server-pro#241]
Hello !

I am trying to deploy the rustdesk pro client, using ansible.

Using the .exe is ok for the installation, including the service, but I am not able to set up a script for the uninstall.

So using the MSI sounds like a better plan here, but unfortunately - as stated in #239 - the service is then not installed / started.
I've tried with the `--install-service` but no luck (that is for the .exe ?).

Another question: if not using a preset password, is the random generated password communicated when the client announce itself to the Rustdesk Console ? 

Many thanks in advance !

**Comment by rustdesk** [comment]
1, `rustdesk.exe --uninstall`
2, https://github.com/rustdesk/rustdesk-server-pro/issues/239#issuecomment-2082837342
3, I can not get you.

**Comment by mmallejac** [comment]
With ansible, 1 doesn't work. 
Not sure why, but I've checked the code and saw that a cmd bat file is run. Maybe ansible (or I) do not know how to deal with that. I could mimic with ansible what the uninstall bat does, but this is not easy to maintain.

2, ok !

3 should I try to reformulate or ?

Thanks !

**Comment by rustdesk** [comment]
> is the random generated password communicated when the client announce itself to the Rustdesk Console ?

We do not do this magic, and for security concern we will never do this  though you thought it is convenient for you.

**Comment by rustdesk** [comment]
> So using the MSI sounds like a better plan here, but unfortunately - as stated in #239 - the service is then not installed / started.

Could you confirm if it is ok if you do not use ansible?

**Comment by mmallejac** [comment]
Ok, doing it manually the client starts, but :
- no password appears, only a `-`
- the bottom area says that the service is not running, and offer to start it

When pressing this option, a password is generated and the service is added and started.

So with an MSI an action must be done on the machine before it gets fully functional. Not ideal for mass deployment.

So far, using the .exe along with a preset password has been the closest to ideal, for me. 
We're not using GPO/strategies here. 

I've just done a quick test, and I am under the impression that using an MSI _containing a preset password_ does the job, I mean in that case the service is installed and started ! Could it be a leftover of a previous installation ?

I also notice that uninstalling the MSI (using the Windows apps in the control panel) stops the service but does not remove it, while the install folder is actually removed.

**Comment by fufesou** [comment]
> the bottom area says that the service is not running, and offer to start it

@mmallejac Hi, have you mannually stopped the RustDesk before uninstalling it?

If the msi detects that RustDesk service has been manually stopped and not previously started, it will not attempt to install and start the service.

**Comment by mmallejac** [comment]
Yes, very possible. I've just done another test : manual MSI install and all went fine, the service is running.

Also done another test with ansible and MSI... all went fine as well.

So most probably the system wasn't clean enough in between each test, sorry ! At least it allow to see that service is not deleted after MSI removal.

**Comment by mmallejac** [comment]
For the MSI uninstall part, I think something is missing in the registry
`HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\[rustDeskProductName]`

The `UninstallString` value is:
`MsiExec.exe /X {61FF4832-A09F-4F45-85B3-0D9F5AD02237}`

Another string should be present: `QuietUninstallString` which value could be:
`MsiExec.exe /qn /X {61FF4832-A09F-4F45-85B3-0D9F5AD02237}`

Without the `/qn` ansible is unable to remove rustdesk, since a confirmation dialog is shown. 
Ansible does unattended work and therefore this dialog is not visible and the uninstall is never run.

Ansible is able to deal with `QuietUninstallString`, see https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_package_module.html#notes

**Comment by rustdesk** [comment]
We had a fix for this, please rebuild a msi and test.

**Comment by mmallejac** [comment]
Good, thanks, I confirm that now the service gets stopped and removed when uninstalling the MSI.

The `QuietUninstallString` would really be great, since it would allow a complete unattended deployment / removal.

**Comment by rustdesk** [comment]
> QuietUninstallString

@fufesou will follow up

**Comment by mmallejac** [comment]
Great !!

The unattended uninstall works just fine now, many thanks :+1:
