### ISSUE TITLE
Reconnecting when trying to press buttons

### ISSUE THREAD

**Issue by CryOnics1** [rustdesk/rustdesk-server-pro#242]
Hello! 

I have 2 mac m2 (sonoma) with custom RustDesk build v1.2.4 from pro console

When i connect to a remote computer, I can control the mouse, but when I click a button I get an error and reconnect
<img width="959" alt="erroor" src="https://github.com/rustdesk/rustdesk-server-pro/assets/20219355/1748b59a-8ba2-4290-8227-f9b287b45083">

I downloaded not custom build RustDesk v1.2.3 and everything works fine! i can press button...

**Comment by rustdesk** [comment]
Could you also test https://github.com/rustdesk/rustdesk/releases/tag/nightly? the custom client is based on the nightly build.

**Comment by CryOnics1** [comment]
> Could you also help test https://github.com/rustdesk/rustdesk/releases/tag/nightly? the custom client is based on the nightly build.

nightly build work good
but in the custom version, the default keyboard setting is set to **Input source 2** and i can't change. 
<img width="254" alt="screen" src="https://github.com/rustdesk/rustdesk-server-pro/assets/20219355/eb44e5b8-9957-4d21-9a26-8c0dbc9753b5">

When i changing input source in nightly build i have the same error. 
How do I change the input source in a custom build?

**Comment by rustdesk** [comment]
@fufesou follow this up.

**Comment by rustdesk** [comment]
@fufesou two issues
- [ ] intput source 2 is default in custom and can not change
- [ ] why input source 2 trigger the connection issue.

**Comment by rustdesk** [comment]
@CryOnics1 do you have this issue https://rustdesk.com/docs/en/client/mac/#enable-permissions? Can you see "input monitor permission" warning on your main window?

**Comment by CryOnics1** [comment]
> @CryOnics1 do you have this issue https://rustdesk.com/docs/en/client/mac/#enable-permissions? Can you see `input monitor permission` warning on your main window?
> 
> ![image](https://private-user-images.githubusercontent.com/71636191/326768510-2ea5b381-79d2-423d-b237-2dad25ff90d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NzQ4MzcsIm5iZiI6MTcxNDQ3NDUzNywicGF0aCI6Ii83MTYzNjE5MS8zMjY3Njg1MTAtMmVhNWIzODEtNzlkMi00MjNkLWIyMzctMmRhZDI1ZmY5MGQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDEwNTUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3MDdlZjQyOTUwNWIzOTM3NmEzYTA4ZWEyNmMwMDA0ZDM3NWRjZGE0OGYxNjM2MGNlM2UyYTA1ZTEyYTQ2ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tCQmYYqtUULOtxG-Zrjke9m-XCuVzavdUV5eTQ6zENA)

no, i don't see warnings, permissions were set, anyway it works in not custom build

**Comment by rustdesk** [comment]
Could you also confirm in system settings?

![image](https://github.com/rustdesk/rustdesk-server-pro/assets/71636191/eb6ad368-7653-4352-860e-b3b770e5b9b0)

**Comment by CryOnics1** [comment]
> Could you also confirm in system settings?

hm.. there was not, i added the custom build manually and program was crashed and then it wouldn't start

I stopped the service manually and replaced the old program the it works. I still can't change the source, but I can press button. 

thanks

**Comment by CryOnics1** [comment]
> If possible, you can try out my custom build, https://rustdesk.com/build/tasks/51844aeb-7dcc-432e-81c5-a994a465f5fc/files/mydesk-arm64.dmg

i use my server

**Comment by rustdesk** [comment]
You can use my serve for test if you are ok

**Comment by fufesou** [comment]
@CryOnics1  Hi, can you please send me your custom client dmg file?  Maybe I can get more clues by running the dmg.

This is my email in base64. c2h1YW5nbG9uZ2NoZW5AeWVhaC5uZXQ=

**Comment by fufesou** [comment]
@CryOnics1 Hi, can you please give a screenshot of the Custom Client in the web console? Please hide the privacte informations.

> nightly build works good
but in the custom version, the default keyboard setting is set to Input source 2 and i can't change.

Maybe custom client configuration affects that.

**Comment by CryOnics1** [comment]
> @CryOnics1 Hi, can you please send me your custom client dmg file? Maybe I can get more clues by running the dmg.

sent

**Comment by CryOnics1** [comment]
> @CryOnics1 Hi, can you please give a screenshot of the Custom Client in the web console? Please hide the privacte informations.

![image](https://github.com/rustdesk/rustdesk-server-pro/assets/20219355/f30f1cff-4f3a-4ab1-810f-745f2ae477ae)

**Comment by fufesou** [comment]
@CryOnics1 Hi, thanks for your reply.

I've tried your dmg file.
But I cannot reproduce the issue of selecting input source.

1. I can see the card of "Input Monitoring".

<img width="251" alt="1714532307383" src="https://github.com/rustdesk/rustdesk-server-pro/assets/13586388/a24d3a6b-45c3-41f1-ab17-461437ba1d6e">

2. I can't select "Input Source 1" until I enable it. But after enabling it, I can select "Input Source 1".

The behavior is the same to the RustDesk nightly build.

**Comment by CryOnics1** [comment]
> @CryOnics1 Hi, thanks for your reply.
> 
> I've tried your dmg file. But I cannot reproduce the issue of selecting input source.
> 
> 1. I can see the card of "Input Monitoring".
> 
> 2. I can't select "Input Source 1" until I enable it. But after enabling it, I can select "Input Source 1".
> 
> The behavior is the same to the RustDesk nightly build.

Hi, hm interesting.. okay when i added it manually it works, i still can't select "Input Sorce 1", but can work
thanks!
