### ISSUE TITLE
small feature request for custom clients (Hide groups in costum client)

### ISSUE THREAD

**Issue by IzunaMoon** [rustdesk/rustdesk-server-pro#244]
Hello,

I noticed that you've added custom address books and included an option to hide the address book in costum clients. 
I would appreciate similar features for the groups section.

The address book is easier to filter and share with people, so we primarily use the groups feature now to allow access to certain devices.

would be helpful if a button could be added with the option to hide groups. Here’s the image indicating where this could be implemented:
![image](https://github.com/rustdesk/rustdesk-server-pro/assets/132285275/585e7a47-e3c5-40aa-8fc1-6d6a6a23b6b1)
with de option hide groups in costum clients dat be great to have sins groups is difficult to filter

if this can already be done with a overwrite
![image](https://github.com/rustdesk/rustdesk-server-pro/assets/132285275/8b84c7eb-83a5-447e-acad-0fad0f80ec5e)
can you let me know how or where i can find de right setting to change with de overwrite 

it be a very nice thing to have for us.

thanks from hour entire department already for de good software

**Comment by rustdesk** [comment]
Will add in next version.

**Comment by rustdesk** [comment]
You can do this.

![image](https://github.com/rustdesk/rustdesk-server-pro/assets/71636191/aaa25c61-811d-4ae3-8752-9b9bc1e4a46b)

**Comment by fufesou** [comment]
> with de option hide groups in costum clients dat be great to have sins groups is difficult to filter

I can't understand clearly.

Does this also explain the ability to hide the entire group panel?

**Comment by ZetaWaves** [comment]
> You can do this. `Advanced options` can also implement this, but currently, it is not tested and documented yet, #212
> 
> ![image](https://private-user-images.githubusercontent.com/71636191/326773106-aaa25c61-811d-4ae3-8752-9b9bc1e4a46b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMjg1MTYsIm5iZiI6MTcxNjIyODIxNiwicGF0aCI6Ii83MTYzNjE5MS8zMjY3NzMxMDYtYWFhMjVjNjEtODExZC00YWUzLTg3NTItOWI5YmMxZTRhNDZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDE4MDMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjMmYyNjA5NGZlNmE3NTQ2NTYzMTQ5MWY2NjBkYTVjYzBhZGQyNzI5OWZjOTM3ZDFjODAxMjYzZTU5ZDZlNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F53KgAEK8T2JcodHD54xiT0lTKddbW1cG2JIgU7O7D4)

Can you add a server-side option to not allow the group list to show to anyone?

That way, logged in users can connect to anyone, but they won't be given a list of ID's which can reduce security. (We don't want users just trying to connect to random ID's that they now know) ie. add some slight security by obscurity to prevent problematic users.

**Comment by ZetaWaves** [comment]
> Hello,
> 
> I noticed that you've added custom address books and included an option to hide the address book in costum clients. I would appreciate similar features for the groups section.
> 
> The address book is easier to filter and share with people, so we primarily use the groups feature now to allow access to certain devices.
> 
> would be helpful if a button could be added with the option to hide groups. Here’s the image indicating where this could be implemented: ![image](https://private-user-images.githubusercontent.com/132285275/326769602-585e7a47-e3c5-40aa-8fc1-6d6a6a23b6b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMzEyMTgsIm5iZiI6MTcxNjIzMDkxOCwicGF0aCI6Ii8xMzIyODUyNzUvMzI2NzY5NjAyLTU4NWU3YTQ3LWUzYzUtNDBhYS04ZmMxLTZkNmE2YTIzYjZiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQxODQ4MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMmU3Nzg0MWFiODVmYmU5ZmJkMzhhN2Q1OWFkMGI0NDIyMzgwNmU0YjY4MjNmZDFiMjQ2ODQ5N2IxNTEwM2FlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OMgmCRWY4ngWonzq3__te9x8mQHJWRahYtHUCSN5loY) with de option hide groups in costum clients dat be great to have sins groups is difficult to filter
> 
> if this can already be done with a overwrite ![image](https://private-user-images.githubusercontent.com/132285275/326769879-8b84c7eb-83a5-447e-acad-0fad0f80ec5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMzEyMTgsIm5iZiI6MTcxNjIzMDkxOCwicGF0aCI6Ii8xMzIyODUyNzUvMzI2NzY5ODc5LThiODRjN2ViLTgzYTUtNDQ3ZS1hY2FkLTBmYWQwZjgwZWM1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQxODQ4MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTcxYWEyODY2NjUxYjNhYTM3NTM4NTJmZjJiNTM5YmZiYzNkN2FiNzU3NDNlNDMxMWFhMWI2ZjcyN2UxNWU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LQuZEg2Z7K6h_xiRQCUBSKYTITlLtk5OV6Ghv7gWoTg) can you let me know how or where i can find de right setting to change with de overwrite
> 
> it be a very nice thing to have for us.
> 
> thanks from hour entire department already for de good software

A server-side option would be better than a client-side option. Mainly so the server isn't just giving the information out. Simply kidding it from the client-side will not fix the information being given out.

**Comment by ZetaWaves** [comment]
@IzunaMoon you can set under advanced settings > overrides:
peer-tab-visible=[true,true,true,true,false]

This will gray out that section and disable that panel.

However, @rustdesk isn't there a way to disable the panel as even showing up under the right-click menu as well?
For example, if you choose to disable logins, it will remove the panel altogether from the build. Maybe just add a checkbox on the custom client page to disable the groups panel by itself, but allow logins under settings?
