### ISSUE TITLE
Requested feature : Support for Custom Clients with Preset Groups

### ISSUE THREAD

**Issue by Helphyy** [rustdesk/rustdesk-server-pro#245]
Hi, I'm a RustDesk Pro Server user and I'd like to know if it's possible to create custom clients with preset groups.

**Goal:**
The goal is to use a client per customer without registering each computer into their respective groups.

**Features Requested:**
  * Custom Clients: Enable creating clients with preset groups to streamline setup.
  * Automatic Assignment: Ability to specify group assignment during client creation.

**Additional Info:**
  * RustDesk Pro Server Version: 1.3.3
  * Platform: Debian 12

Thank you!

**Comment by rmundel** [comment]
+1

**Comment by rustdesk** [comment]
You can assign users via command line https://rustdesk.com/docs/en/self-host/rustdesk-server-pro/console/#assign-device-usersgroupsstrategies-to-devices

**Comment by rustdesk** [comment]
we will add preset addressbook to custom client. Preset user will be a big vulnerable bug, because hacker can modify code to assign user and get access permission without token.

**Comment by rustdesk** [comment]
https://x.com/rustdesk/status/1796114741116469643
