### ISSUE TITLE
Address books no longer selectable

### ISSUE THREAD

**Issue by isential-gmbh** [rustdesk/rustdesk-server-pro#247]
Over the weekend, I noticed that I can create more than just 10 address books. As a result, I created 8 more, bringing the total to 18 address books.

Today, I noticed on the client side that I no longer have the option to select an address book.

Is this related to having more than 10 address books, or has another error occurred?

I noticed this on the client side: The address books cannot be selected anymore. However, since the address books can only be used in conjunction with the 'server-pro' version, I described the issue here.

Thank you and regards.

René

**Comment by rustdesk** [comment]
A picture please?

**Comment by isential-gmbh** [comment]
![image](https://github.com/rustdesk/rustdesk-server-pro/assets/68383884/510a85a5-28f3-436b-a0d6-3fbab14c954e)

**Comment by rustdesk** [comment]
Click on # please
![image](https://github.com/rustdesk/rustdesk-server-pro/assets/71636191/d4e57454-ca36-43f8-8336-4e3880334a03)

**Comment by isential-gmbh** [comment]
"No problem, and thank you! My mistake..."
