### ISSUE TITLE
Device permission issues with self-built server Pro version

### ISSUE THREAD

**Issue by 754628709** [rustdesk/rustdesk-server-pro#248]
Customized console software allows you to access the device without the need for an address book or login as long as you know a controlled terminal ID and password. This is very unsafe and address book permissions will be meaningless. (And leaking customized control software is likely to cause losses to the enterprise)

**Comment by rustdesk** [comment]
I would suggest you set up your backup/restore strategy, do not trust any other 3rd HA solution, we have been seeing so many failures of biggest companies in the world.

Here are backup/restore script in https://github.com/rustdesk/rustdesk-server-pro written by our contributors, please write some cron job to do it repeatly. Once your hbbs server fails, you can start a new hbbs with the backup file, migrate the license to the new server, modify dns to new ip, after dns ttl time, yout rustdesk clients will connect to new hbbs automatically.

**Comment by rustdesk** [comment]
@21pages please add this.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/8069

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk-server-pro/releases/tag/1.3.5
