### ISSUE TITLE
Feature request / change: Please remove device limit

### ISSUE THREAD

**Issue by ZetaWaves** [rustdesk/rustdesk-server-pro#251]
This is a feature request to remove the device limit. All of our users connect to random machines to support other's. Now, it has gotten to the point where the software is installed and runs at startup on many computers which whom we rarely connect to. This is filling up our device list and we are hitting the limit daily. 

This has become a larger problem / concern now as each time a user's computer is booted up, it creates another device on our device list. Some of these devices were one-time support requests where we installed the client for a one-time use, but it's still installed on the machines as a service by default so it starts automatically every time device is booted. 

Simply purging devices isn't cutting it anymore. We need another solution.

**Comment by rustdesk** [comment]
Apologize, I am stick to https://github.com/rustdesk/rustdesk-server-pro/discussions/182

**Comment by ZetaWaves** [comment]
@rustdesk No plans to offer a plan that better fits our needs? 
Like an unlimited device plan that doesn't cost too much. 

The problem is that when you go to support a remote user, they instal the software and now you can't uninstall it without getting booted. It's now going to start every time they start their machine. This will re-register their machine on the server device list each time. We support 40+ machines per day, but only once, and then we never see them again. 

The current plan just doesn't fit. It's disabling users and deleting a machine to free up another just isn't working anymore. 

The free version of RustDesk doesn't have this limitation, why does the paid version? It's already a paid subscription on a yearly basis. I just don't understand. RustDesk Pro is so close to being perfect for our needs, this is the last hurdle. :(

**Comment by rustdesk** [comment]
> We support 40+ machines per day, but only once, and then we never see them again.

That's why I give you https://github.com/rustdesk/rustdesk-server-pro/discussions/182#discussioncomment-9083837

**Comment by ZetaWaves** [comment]
@rustdesk I understand. I'm currently using that script, however, it seems I'm hitting the limit daily even when clearing out entries every 3 hours. The problem is that the devices cannot be cleared if they're actively connected. Many of the user's we have supported in the past have never removed the client so when their machine is booted up, it's connected. 

The script really helped for quite awhile, but now it seems the problem is the device limit. 

I have the script set now to remove devices every 15 mins and even then it is not enough. I'm still getting disabled device entries.

**Comment by rustdesk** [comment]
If it is used only once, why do you ask them install it? why not given them a quick-support version having installation disabled?

**Comment by ZetaWaves** [comment]
@rustdesk installation is required for UAC to work properly unattended. 
We have issues installing our software for users when UAC is prompted, so our process has always been to install the client.

**Comment by rustdesk** [comment]
not installed version can also elevate for UAC. The user can click on "Accept and Elevate" on  incoming connection window, the control side can also request elevation from the menu of remote window.

**Comment by ZetaWaves** [comment]
@rustdesk Many times the user on the other end is not in front of the machine so we almost always use ID & password authentication. For some reason this doesn't appear to elevate properly.

**Comment by rustdesk** [comment]
This is not one time use case.

**Comment by ZetaWaves** [comment]
It is. They send us the information and then usually walk away and do other things.
It would be a problem to bother them every time we need to elevate which is why we have always had the user install the client. 

TeamViewer is what we used to use and it elevated automatically regardless of being installed or not. That's what we have been used to. 

We install our software that we make on the user's machine and then they take the machine and sell it. We usually never see it again unless the user wants something else which is rare.

**Comment by rustdesk** [comment]
> We install our software that we make on the user's machine and then they take the machine and sell it. We usually never see it again unless the user wants something else which is rare.

$0.01 per month is too expensive for you in this case? Or you can find cheaper solution for your case in the market?

**Comment by ZetaWaves** [comment]
@rustdesk It's not too expensive. Actually, I find your pricing very fair. 
However, in this case, the amount of devices will just grow over time and we are still making the same amount of money. 

For example, we are supporting more and more devices on a temporary basis over time. Eventually I'd be at a 1000+ device license which would be way out of the price bracket for what I do. 

So, in context, $0.01 per device is very affordable, but these devices are not managed devices, they're temporary support devices. So I will continue to pay for them over time forever even though I never connect back to them again. 

That's why I was asking for a different solution. I'm not opposed to paying for a different plan that makes more sense for the use-case that I'm in.

**Comment by rustdesk** [comment]
The problem is, there is no way to know it is managed or temporray support in your case.

**Comment by ZetaWaves** [comment]
I know, that's the problem I'm facing. 

Your product is great, much better and faster than TeamViewer. I just wish it fit our use case.
I feel like it's very close to fitting how we use it, but this was one thing that was missing.

Re-enable operation? What do you mean by that?

**Comment by rustdesk** [comment]
> Re-enable operation? What do you mean by that?

You can disable these devices with the script. When you need to support it, you enable it.

**Comment by rustdesk** [comment]
You can also make these devices connected to free OSS version.

**Comment by ZetaWaves** [comment]
@rustdesk I have 5 other coworkers who have the "controlling" part of the client. 
They are the ones who remote in most of the time to support our customers.
Problem is, I don't always know which ID's are still being used and which one's are not.
They're connecting to so many daily that it's hard to keep track. 

I may try to disable devices over time, but that has already caused a problem with someone who had to jump back on to fix a mistake. The device was disabled and I received a call in the middle of the night. 

So yes, it is possible to disable the devices. I have been doing that the last few weeks. 

I'm just wondering though, why does OSS have no device limit but pro does? 

I can understand a user limitation, but why a device limitation? 

Is this product really meant for businesses who manage their own machines? 

Teamviewer is advertised as mainly a remote support tool that's what I thought RustDesk was. 

I used the free version in the past, but I wanted to support the developers and company here, plus I love the web interface and custom clients are great. 

I just wish you guys had a plan with no device limit or had a way to mark devices as managed or not managed.

**Comment by rustdesk** [comment]
How TeamViewer handle your case?

**Comment by ZetaWaves** [comment]
@rustdesk We had a Teamviewer Business plan. A step down from the Premium Plan.
For managed devices, it was 300. However, you can connect and install the custom client on unlimited machines and connect to any of them anytime with no limitation. The only limitation they have that you guys do not is the simultaneous connections. 

TeamViewer defined a "managed device" as a device that is stored in the address book for ease of access. It also had other features, such as, patching windows clients with windows updates remotely and other things like that for managed devices only.

However, for us, we didn't use any of those features. We just used it for remote support. 
The amount of connections was the limitation we had the largest problem with. 
The price was slightly higher than yours for a similar package. 

For example, Teamviewer was $21.90/month for the plan I had where yours is $19.90/month. 
I believe TeamViewer at this current time is priced higher than when I first signed up.

I believe RustDesk is a superior product overall though. TeamViewer is more expensive and slower for everyday use.

**Comment by rustdesk** [comment]
Thanks, I will evaluate my decision again.

**Comment by ZetaWaves** [comment]
@rustdesk Thank you for taking the time to talk to me as well. I really appreciate it. :)

**Comment by rustdesk** [comment]
We do not have concurrent connection limit, so we add device limit. We can not take user limit as concurrent connection limit, because compared with concurrent connection limit, our user is too cheap.

**Comment by ZetaWaves** [comment]
@rustdesk Yes, not having the concurrent connection limit is one of the best things about RustDesk.

**Comment by Mhalkyo** [comment]
Hello, is this post still relevant. Because I have the same problem, we use a lot of devices but we connect very rarely to some. Is there a solution to not have certain workstations in the list? Maybe with an option in the executable to disable the addition in the managed devices. A bit like what anydesk can offer in its custom client by disabling the addition of certain devices in the address book.

**Comment by Mhalkyo** [comment]
Hello, we use a lot of devices but we connect very rarely on some. Is there a solution to not have certain posts in the list? Maybe with an option in the executable to disable the addition in the managed devices. A bit like what anydesk can offer in its personalized client by disabling the addition of certain devices in the address book.

This is one of the only things I have a problem with on rustdesk, because otherwise the application is great and brings together exactly the elements that my company wants.
