### ISSUE TITLE
Feature request: Add a setting for custom clients to allow automatic elevation on run.

### ISSUE THREAD

**Issue by ZetaWaves** [rustdesk/rustdesk-server-pro#252]
Is it possible to add a setting for automatic elevation on run? 
I would like to not install the client, but still have elevation on run. 

It seems it works when renaming the executable with _QS.exe at the end, however, is there a setting for this currently? 

Also, it seems "Privacy Mode" and "Block User Input" do not work regardless unless the client is installed. Is there a way to fix this?

**Comment by rustdesk** [comment]
ok, we will add to custom client

**Comment by rustdesk** [comment]
https://x.com/rustdesk/status/1796114741116469643
