### ISSUE TITLE
Address Book

### ISSUE THREAD

**Issue by DaliborS89** [rustdesk/rustdesk-server-pro#257]
When will it be possible to add the device after installation to the directory automatically ( in the msi package) now I can only manually add to addres. It's not a nice thing for admins to have to manually add all devices.

We are a large company and I would like to solve the problem well and quickly so that everything is efficient and not all equipment is added manually.

It would be good if you put the option in Override and I could set the following example: device_add=%address_book_name%.

Thank you,
Have nice day.

**Comment by DaliborS89** [comment]
@rustdesk Hello When will the be problem  resolved?

**Comment by rustdesk** [comment]
We are on it, maybe tomorrow.

**Comment by DaliborS89** [comment]
> We are on it, testing, maybe release tomorrow.

Hi this is perfect thank you very much.

**Comment by DaliborS89** [comment]
Hello if I understand correctly so you have added the configuration to the program now waiting for the new version of the program is that correct ?

**Comment by rustdesk** [comment]
https://x.com/rustdesk/status/1796114741116469643

**Comment by Trouble123** [comment]
Hi, can you explain how this is supposed to be setup? I upgraded my pro server to 1.3.6, i went into the custom client and added these 2 lines. I wasnt sure if the =name should be the name of the PC or just name, so i left it as is.
pre-elevate-service=Y
preset-address-book-name=name
Re-built custom client, uninstalled the custom client on my laptop and ran it (no install).
I dont see anything in my address book in the client (on another device logged in), and i dont see anything in the addressbook (shared or personal) in the Web console.
I installed the client, again same results.

I have previously (an hour ago) set a custom ID using the previous client, and i see that ID come through when i run or install the new versions on the laptop, but i see nothing anywhere.

Like others,i plan on deploying the Windows client, to about 800 devices and also to about 80 android devices, but i cant ask the user for their ID as we will need to do a silent install, and android devices will be in kioks mode.
Thanks

**Comment by DaliborS89** [comment]
> Hi, can you explain how this is supposed to be setup? I upgraded my pro server to 1.3.6, i went into the custom client and added these 2 lines. I wasnt sure if the =name should be the name of the PC or just name, so i left it as is. pre-elevate-service=Y preset-address-book-name=name Re-built custom client, uninstalled the custom client on my laptop and ran it (no install). I dont see anything in my address book in the client (on another device logged in), and i dont see anything in the addressbook (shared or personal) in the Web console. I installed the client, again same results.
> 
> I have previously (an hour ago) set a custom ID using the previous client, and i see that ID come through when i run or install the new versions on the laptop, but i see nothing anywhere.
> 
> Like others,i plan on deploying the Windows client, to about 800 devices and also to about 80 android devices, but i cant ask the user for their ID as we will need to do a silent install, and android devices will be in kioks mode. Thanks

Hello,
I think you can just go to the Custom Client Settings, located under Advanced ->Override, and enter the default directory name=<directory name>. 
Then have the settings to download the custom client and then try to see if everything works as shown above or here:

https://rustdesk.com/docs/en/self-host/client-configuration/advanced-settings/#preset-address-book-name--preset-address-book-tag.

**Comment by nicedevil007** [comment]
@DaliborS89 can you share information about on what is needed to give any client a shared to everyone addressbook with the instalaltion? I guess it is mandatory that a user logs in to the client with its credentials right? Right now there was/is no benefit for us having users to log in (we are not a huge company, 30 clients and thats it).

**Comment by Trouble123** [comment]
Hi, thanks for replying but it it wasnt clear, but i have worked it out.  The value in <address book name> should match the Address Book Name that is created in the Rustdesk Web Setup.
I changed the value in the Overide to preset-address-book-name=Support (which is the name of the phone book).

I would suggest improving the docs so its clear for all

**Comment by DaliborS89** [comment]
> @DaliborS89 can you share information about on what is needed to give any client a shared to everyone addressbook with the instalaltion? I guess it is mandatory that a user logs in to the client with its credentials right? Right now there was/is no benefit for us having users to log in (we are not a huge company, 30 clients and thats it).
this is correct setting in advanced option in Custome Client.
preset-address-book-name=address book name 
@nicedevil007

**Comment by DaliborS89** [comment]
> > @DaliborS89můžete sdílet informace o tom, co je potřeba k tomu, aby měl každý klient sdílený adresář s instalací? Myslím, že je povinné, aby se uživatel přihlásil ke klientovi pomocí svých přihlašovacích údajů, že? Právě teď pro nás nebylo/není žádný přínos mít přihlášení uživatelů (nejsme velká firma, 30 klientů a basta). 
> > toto je správné nastavení v rozšířené možnosti v Custom Client. 
> > preset-address-book-name=název adresáře
> > @nicedevil007

I think that not only my company, but all administrators in the world who use RustDesk saw this. Not everyone wants to manually click on machines one by one etc. Now I'll just put a key to automatically connect to the address book. So this is really cool. I tried it today and everything is ok. We just need to play around with the FW to be able to automatically assign to each directory even without internet.

**Comment by nicedevil007** [comment]
My question to this is still, if it is needed that the user on the device is logged into the RustDesk client or not. My setting is that the addressbook entries are for everyone. My expection is that this is then builtinto the client that I build via webgui and install on the clients. Right now it seems not to work with this on my site.

Yes the setting for addressbook was copy pasted and there is no spelling error on the name of the addressbook itself.

**Comment by 8899kkA** [comment]
Hey guys, sorry for reviving this thread. I'm battling with this feature, and I have varying results. Assigning a custom client using tags, is not working for me whatever I try. Using the name of the addressbook does work in some cases. I have it working on a customer client for windows, but for the life of me I can't get it to work on a linux client.

I was considering using this feature to compensate for the lack of device groups, as I could generate a client for a customer and have them register with an addressbook automatically, so ITsupporters in the company can se all devices as soon as a client is installed.

The client it worked for, was NOT logged in with a user.

**Comment by 8899kkA** [comment]
Apologies... I just worked out, that you need to delete the device from the server, for the address book feature to work. So if there previously was a client installed on the client, which registered with the server, then installing a new custom client with the addressbook name specified does not place it in the addressbook. Only when the device is deleted from the server, and basically comes in as a new device it will be registered with the correct addressbook. So at least by name seems to work.
