### ISSUE TITLE
 Proxy-Only Configuration for Custom Client

### ISSUE THREAD

**Issue by MPalatucciEng** [rustdesk/rustdesk-server-pro#263]
With our company, in order to offer support to customers, we customised the client, with the web console. Many times, users are behind proxies. In order to allow users behind proxies to connect to our servers, we need to give them access to the network settings, so that they can set the proxy configuration. Is it possible to insert some setting to only allow the proxy configuration options to be displayed, hiding all the network settings? (Server ID, Relay server, API Server and Key) so as to avoid exposing this data. Perhaps with an advanced setting in the Custom client generator. Or by separating the proxy settings from the network settings, so that the user does not have access to the network settings but only to the proxy settings.

**Comment by MPalatucciEng** [comment]
![sample](https://github.com/rustdesk/rustdesk-server-pro/assets/171362211/339a2a1a-59e7-42d8-893a-bd1547a8510e)

**Comment by rustdesk** [comment]
Ready now, https://rustdesk.com/docs/en/self-host/client-configuration/advanced-settings/#hide-security-settings--hide-network-settings--hide-server-settings--hide-proxy-settings
