### ISSUE TITLE
New build agent V1.2.7 error connection with login

### ISSUE THREAD

**Issue by maxihoster** [rustdesk/rustdesk-server-pro#267]
Hello!

I have builded new agent windows and impossible to connect with my login on it! The version builded automatically is 1.2.7!

Of course we can't choose the version of the agent builded into the console (custom build)! So it's an issue!

When I try to connect with old version 1.2.3 there is no problem!

I have the error about socket exception and semaphore time out!

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk-server-pro/issues/266
Open "Settings" -> "network" on rustdesk client to confirm if api server correct.

**Comment by maxihoster** [comment]
Hello! Of course the value is correct! I have checked multiple times and same issue

**Comment by rustdesk** [comment]
If possible, show me their Settings -> network, you can hide critical info, only display partly.

**Comment by maxihoster** [comment]
![image](https://github.com/rustdesk/rustdesk-server-pro/assets/96882409/86ebfe21-5ffb-4f49-88c7-7f4f5a027427)

I have removed a big part of the key for this screenshot!

**Comment by maxihoster** [comment]
![image](https://github.com/rustdesk/rustdesk-server-pro/assets/96882409/6ae9eeed-2845-44f1-84a0-b962307d001a)

**Comment by rustdesk** [comment]
Could you show me the custom client page of this build?

**Comment by maxihoster** [comment]
![image](https://github.com/rustdesk/rustdesk-server-pro/assets/96882409/492b4ddc-936b-43b9-a60f-55c368766862)

![image](https://github.com/rustdesk/rustdesk-server-pro/assets/96882409/66915039-1c65-4e72-9c16-a4c8b28f1b2b)

**Comment by rustdesk** [comment]
Remove `21114` here please.

![image](https://github.com/rustdesk/rustdesk-server-pro/assets/71636191/bf6cb57f-55b5-4723-8791-6d5ab2a736c7)

**Comment by maxihoster** [comment]
I have removed as your instruction!
Rebuilded the exe
uninstall my old agent and reinstall with new agent!

NOW IT WORK PERFECTLY!!!! THANK YOU!!!!
