### ISSUE TITLE
Script fails to upgrade server from open source to Pro

### ISSUE THREAD

**Issue by RichardBurt65** [rustdesk/rustdesk-server-pro#28]
### Bug Description

Following instructions from [here](https://rustdesk.com/docs/en/self-host/pro/installscript/#convert-from-open-source) the script fails to upgrade my server from open source to Pro. 

```
Creating /var/log/rustdesk-server
Created symlink /etc/systemd/system/multi-user.target.wants/rustdesk-hbbs.service → /etc/systemd/system/rustdesk-hbbs.service.
Created symlink /etc/systemd/system/multi-user.target.wants/rustdesk-hbbr.service → /etc/systemd/system/rustdesk-hbbr.service.
RustDesk Relay not ready yet...
Tidying up install
rm: cannot remove 'rustdesk-server-linux-amd64.zip': No such file or directory
```

Server - Ubuntu 20.04 (LTS) x64

### How to Reproduce

.

### Expected Behavior

Upgrade to Pro version

### Operating system(s) on local side and remote side

Ubuntu 20.04 (LTS) x64

### RustDesk Version(s) on local side and remote side

Server Pro

### Screenshots

.

### Additional Context

.

**Comment by dinger1986** [comment]
Strange, I have tested on ubuntu 20.04, can you run and share the output of `sudo systemctl status rustdesk-hbbs` and `sudo systemctl status rustdesk-hbbr`

**Comment by RichardBurt65** [comment]
`sudo systemctl status rustdesk-hbbs
● rustdesk-hbbs.service - RustDesk Signal Server
     Loaded: loaded (/etc/systemd/system/rustdesk-hbbs.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2023-07-21 12:06:05 UTC; 26s ago
   Main PID: 2292 (hbbs)
      Tasks: 10 (limit: 512)
     Memory: 2.8M
     CGroup: /system.slice/rustdesk-hbbs.service
             └─2292 /usr/bin/hbbs

Jul 21 12:06:05 rust systemd[1]: Started RustDesk Signal Server.`



`sudo systemctl status rustdesk-hbbr
● rustdesk-hbbr.service - RustDesk Relay Server
     Loaded: loaded (/etc/systemd/system/rustdesk-hbbr.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2023-07-21 12:06:07 UTC; 1min 10s ago
   Main PID: 2379 (hbbr)
      Tasks: 4 (limit: 512)
     Memory: 592.0K
     CGroup: /system.slice/rustdesk-hbbr.service
             └─2379 /usr/bin/hbbr

Jul 21 12:06:07 rust systemd[1]: Started RustDesk Relay Server.`

**Comment by dinger1986** [comment]
ok, did you install with IP or DNS? if IP please go to http://IPADDRESS:21114 if DNS please go to https://DNSADDRESS

Does that work?

**Comment by RichardBurt65** [comment]
I wasn't given the option to install via IP or hostname during the upgrade.

Server is at rust.pc-support.uk.com

**Comment by dinger1986** [comment]
so after this point the script stoppped? `rm: cannot remove 'rustdesk-server-linux-amd64.zip': No such file or directory`

**Comment by RichardBurt65** [comment]
Correct

**Comment by dinger1986** [comment]
Sorry yes, I know what it is, let me write a script that will fix that for you and Ill link it here very shortly!

**Comment by dinger1986** [comment]
would you like to use nginx @RichardBurt65? you will need to open port 80 and 443 on your firewall not port 21114, the script will take care of the local firewall

**Comment by RichardBurt65** [comment]
I don't care as long as it works and requires minimal input from me

**Comment by RichardBurt65** [comment]
Just remember it's the open source version with webpage already.

**Comment by dinger1986** [comment]
The webpage is removed as it serves no purpose as configs are available via the new console :)

Please run the below which will give you the option to work with IP (using port 21114) or web with https (using port 443 and 80 needs to be opened to get the ssl cert with certbot)

`bash <(wget -qO- https://raw.githubusercontent.com/dinger1986/rustdesk-server-pro/dinger1986-fix-for-failed-out-script/fixforfailedoutscript.sh)`

**Comment by RichardBurt65** [comment]
Install script worked till the last line where:

`Your IP/DNS Address is rust.pc-support.uk.com
Your public key is `

Public key is blank and going to rust.pc-support.uk.com gives me a 520 Bad Gateway error.

**Comment by dinger1986** [comment]
strange, any chance you can email sales@rustdesk.com and I can get on remotely and take a look to resolve this for you?

**Comment by RichardBurt65** [comment]
Done.

**Comment by dinger1986** [comment]
please close this, sorted now

**Comment by rustdesk** [comment]
You did not remove another `set -e`.

**Comment by rustdesk** [comment]
> strange, any chance you can email [sales@rustdesk.com](mailto:sales@rustdesk.com) and I can get on remotely and take a look to resolve this for you?

What is the final solution？

**Comment by dinger1986** [comment]
> > strange, any chance you can email [sales@rustdesk.com](mailto:sales@rustdesk.com) and I can get on remotely and take a look to resolve this for you?
> 
> What is the final solution？

ssh on and rerun the script after a snapshot restore
