### ISSUE TITLE
Show DeviceName without username

### ISSUE THREAD

**Issue by MerryPickles** [rustdesk/rustdesk-server-pro#284]
Would be great if we could see the DeviceName in the list of Devices **without showing the username@.**
The DeviceName that I assign to each device when installing RustDesk is meaningful. Currently, it shows the username@DeviceName, which just means I have to look harder to find the DeviceName. Also, if the username is long enough, it obstructs most of the DeviceName.

**Comment by rustdesk** [comment]
Will be ready soon.
![image](https://github.com/rustdesk/rustdesk-server-pro/assets/71636191/63dcd246-09fe-4feb-aa1b-842bb46ab61e)

**Comment by andrewheberle** [comment]
Will there be a similar option in the RustDesk client to hide the username in the list of devices?

If that can be configured via a strategy that would be great.

**Comment by rustdesk** [comment]
client side https://github.com/rustdesk/rustdesk/commit/8a370e640a972cf2595331b67f893e667de7ee68 will be released together with 1.2.7 release.

**Comment by rustdesk** [comment]
Ready now, https://rustdesk.com/docs/en/self-host/client-configuration/advanced-settings/#hide-username-on-card

**Comment by C-Duv** [comment]
> client side [rustdesk/rustdesk@8a370e6](https://github.com/rustdesk/rustdesk/commit/8a370e640a972cf2595331b67f893e667de7ee68) will be released together with 1.2.7 release.

How do I enable it on my client (Linux, v1.2.7)?

I did not find any related settings in the GUI, so I added `hide-username-on-card = 'Y'` to my `~/config/rustdesk/RustDesk2.toml` file (in the `[options]` part).

But after a restart, the usernames are still shown in _connect cards_.

(Note: Feature of hiding user names in the server's GUI using the checkbox works fine)

**Comment by romanad** [comment]
Is this option available for free version?
