### ISSUE TITLE
Criei Aplicativo Personalizado

### ISSUE THREAD

**Issue by jsfsolucoes** [rustdesk/rustdesk-server-pro#309]
Criei o APlicativo personalizado do Rustdesk e agora ao acessar o outro pc esta dando esse erro 
![image](https://github.com/user-attachments/assets/49491a77-b194-4f45-98c9-662b196d8c10)

**Comment by rustdesk** [comment]
Please log in.

![image](https://github.com/user-attachments/assets/993cf061-cb4e-4094-9797-7b78ac8ae91f)
