### ISSUE TITLE
Cannot set persistent password on client

### ISSUE THREAD

**Issue by RichardBurt65** [rustdesk/rustdesk-server-pro#31]
FAQ script [here](https://rustdesk.com/docs/en/self-host/pro/faq/#how-can-i-set-a-persistent-password-on-an-agent-on-my-network-or-using-an-rmm-type-system) seem to generate a random password but doesn't set it.

**Comment by dinger1986** [comment]
What do you mean? I have tested it and it does work

**Comment by dinger1986** [comment]
How are you running it? I have tested this with my rmm and works fine, just spinning up a test PC to try it directly with powershell

**Comment by RichardBurt65** [comment]
Ah, that's the fix. Thanks. Sent from my iPhoneOn 21 Jul 2023, at 19:00, dinger1986 ***@***.***> wrote:﻿
tested, so the command works from SYSTEM but not as an administrator

**Comment by RichardBurt65** [comment]
Working perfectly now through my RMM.

Suggestion for the powershell script (deploying RD) - change the download URL to something like:

`https://github.com/rustdesk/rustdesk/releases/download/**_latest_**`
