### ISSUE TITLE
Can't access "Custom client" page

### ISSUE THREAD

**Issue by darnasii** [rustdesk/rustdesk-server-pro#311]
After update to 1.4 using update.sh script, I get error like below:

![Zrzut ekranu 2024-07-19 124101](https://github.com/user-attachments/assets/b1897935-bb56-4656-bcf7-bdcdbefb9f2e)

**Comment by rustdesk** [comment]
click on browser refresh please

**Comment by darnasii** [comment]
All right, I've restored snapshot of server, did update one more time and it's working now.
