### ISSUE TITLE
Unknown custom clients downloads and executions

### ISSUE THREAD

**Issue by AlvaroNieto** [rustdesk/rustdesk-server-pro#312]
Everytime I create a new custom client, I see new and unknown devices that download the custom client and executed it in the following seconds. I always remove the custom client after I download it becase of this, but sometimes it still happens.

I have Rustdesk Server Pro version 1.4.0 but has been happening since the launch of the custom client. 

Is there any possibility that thirth parties are able to access the custom client files from Rustdesk's backend? That would be kind of an important issue.

My server is not accesible from the internet so my infrastructure should no be the problem.

**Comment by pdifeo** [comment]
Similar problem reported by me in  &A https://github.com/rustdesk/rustdesk-server-pro/discussions/307

**Comment by rustdesk** [comment]
@21pages follow it up.

**Comment by rustdesk** [comment]
We have put a fix to enforce the download security on server side a moment ago.

**Comment by pdifeo** [comment]
> We have put a fix to enforce the download security on server side a moment ago.

Thank you for your consideration.

is it advisable to change the key ?

**Comment by rustdesk** [comment]
> is it advisable to change the key ?

I advise build a new client with chaning an IP to verify if it is really downloaded by others.

**Comment by rustdesk** [comment]
It is quite similar to this https://docs.tacticalrmm.com/faq/#help-ive-been-hacked-and-there-are-weird-agents-appearing-in-my-tactical-rmm

**Comment by AlvaroNieto** [comment]
> [](https://docs.tacticalrmm.com/faq/#help-ive-been-hacked-and-there-are-weird-agents-appearing-in-my-tactical-rmm)

Yep, it really looks just like that. The thing is, we do not have full control of all the devices that uses our Rustdesk Server. So we can't disable the Automatic sample client-wide. I am going to create a new custom client to see if they do not appear after your fix deployment.

**Comment by rustdesk** [comment]
My fix can not handle this case.

**Comment by AlvaroNieto** [comment]
> My fix can not handle this AV case.

As long as the only "ghost" connections that appear are from the AV samples, we are confortable with it. We have random passwords and monitor new devices that connect to the server. Should not be an issue. 

I left a new custom client created ready to be downloaded (but never executed), I will check tomorrow if new IDs have appeared. If not, I will close the issue. 

Thank you!

**Comment by AlvaroNieto** [comment]
No unknown IDs!
