### ISSUE TITLE
Add extra number/digit to version for custom client builds

### ISSUE THREAD

**Issue by andrewheberle** [rustdesk/rustdesk-server-pro#314]
When deploying a custom client MSI build via Intune the version number of the client is extracted, which is great, however rebuilding the same custom client version with different settings means the resulting MSI has the same version number, such as the current `1.2.7` version, which is a problem as Intune does not allow you to replace the current version of an App with what is detected as the exact same version (error below):

![image](https://github.com/user-attachments/assets/f24e969d-8b6b-45ba-a37e-236559379397)

Would it be possible to add an additional "field" to the version number of the custom client so it has `<MAJOR>.<MINOR>.<PATCH>.<BUILD>`?

It would be great if this was incremented for each configuration change of the custom client, so the `1.2.7` for my latest setup would end up being something like `1.2.7.5` as I have probably made five changes to my custom client config.

Another option may be to add the date and time, maybe something like `<MAJOR>.<MINOR>.<PATCH>.<DATE>.<TIME>`, for example `1.2.7.20240722.154405`, which would be a custom client based on `1.2.7` that was built on 22/07/2024 at 3:44pm.

I cannot find any documentation that Microsoft publish regarding version numbers of MSI packages, however PowerShell can correctly distinguish between higher/lower version numbers using either of the above options.

**Comment by rustdesk** [comment]
Close as fix has been released
