### ISSUE TITLE
Minor typo in SMTP settings

### ISSUE THREAD

**Issue by andrewheberle** [rustdesk/rustdesk-server-pro#315]
Just a very minor issue with what looks like a typo on the SMTP settings page in the RustDesk Pro web UI:

![image](https://github.com/user-attachments/assets/f8b32d54-e54b-4844-9193-f0dc04d87089)

I believe the placeholder should be `no-reply@example.com` instead of `no-replay@example.com`

**Comment by rustdesk** [comment]
Thanks, we have put a fix. Will release with next version.
