### ISSUE TITLE
Custom Client not downloadable

### ISSUE THREAD

**Issue by ReneGoetz** [rustdesk/rustdesk-server-pro#317]
If i create a new Custom Client in Server Pro 1.4.0 i can't download

I can create the Client.
If i try to download, i get an error:

{"error":"Bad request"}

**Comment by rustdesk** [comment]
And below in red rectangle are the same, we enhance this download for security.

![image](https://github.com/user-attachments/assets/fec05e32-30be-47aa-98ed-f555eabb381b)

**Comment by ReneGoetz** [comment]
OK, you're right. I used allways the internal IP, with the external it works,

Thanks

**Comment by djagoo** [comment]
I have RustDesk behind a tls proxy so I access the admin console via https://rustdesk.example.com and since I don't expose port 21114 I used https://rustdesk.example.com as API too. When I create a custom client I get "bad request" when I click on the download link.

> And below in red rectangle must be the same, we enhance this download for security concern [#312 (comment)](https://github.com/rustdesk/rustdesk-server-pro/issues/312#issuecomment-2242133191).
> 
> ![image](https://private-user-images.githubusercontent.com/71636191/350942515-fec05e32-30be-47aa-98ed-f555eabb381b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4OTEwNzUsIm5iZiI6MTcyMTg5MDc3NSwicGF0aCI6Ii83MTYzNjE5MS8zNTA5NDI1MTUtZmVjMDVlMzItMzBiZS00N2FhLTk4ZWQtZjU1NWVhYmIzODFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDA2NTkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiYjU2ZDk4MTczNzMwOTY5NGRlNjIxYjcxY2EwZjJlZDRmOTcyNjQwNmFmOWFiODkzMjRmMGViN2U0MWRjZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t6f_EDCiMZulkJkmdTZV5EhI8MV39eFWMFHvuolvhOw)

I have RustDesk behind a tls proxy so I access the admin console via https://rustdesk.example.com and since I don't expose port 21114 I used https://rustdesk.example.com as API too. When I create a custom client I get "bad request" when I click on the download link.

**Comment by rustdesk** [comment]
It has nothing to do with 21114. You must make sure the host in `API` is same to the host in url on browser. If you do not understand, please paste your screenshot of custom client page (the page you see above), I will help you figure out.

**Comment by djagoo** [comment]
It is exactly the same in my url and in the API field, I don't want to paste a screenshot of our production environment, how can I send it to you?

**Comment by rustdesk** [comment]
info@rustdesk.com

**Comment by thorti79** [comment]
I have the exact same problem.

Setup: Rustdesk-Pro with docker-compose behind traefik for incoming traffic. Outgoing traffic goes via a squid proxy.

**Comment by thorti79** [comment]
Problem solved for me.
I used a different browser (Firefox) without add-ons.

**Comment by djagoo** [comment]
When I use Firefox it's not working, in Chromium the download works.

**Comment by Quildar** [comment]
Have tried downloading through web console on multiple different browsers and different computers Win/Mac. 

My browser address I am using to access the console matches the API box: https://rust.example.net
the host box also matches minus the "https://"

I am using Traefik with the rust server behind it

**Comment by rustdesk** [comment]
I temporarily loose the limit since so many browser have the issue.

**Comment by kirawang** [comment]
This is really a terrible update, it completely affects the usability. I can only roll back to the previous version and use it.

**Comment by rustdesk** [comment]
this has nothing to do with the update, your rollong back did do nothing. this is totally controlled on our side.

**Comment by kirawang** [comment]
I also agree that。
this is not a good update. In order to prevent client leakage for fraudulent activities and other issues, we prefer to have internal control endpoints use IP addresses or internal domain names, while external controlled endpoints use external domain names. This update completely hinders our usage.

**Comment by THarmon77** [comment]
Is there a fix for this? I purposely bought the pro server so we can deploy quick support agents and this is the ONE thing that is hampering our widescale deployment. Is there a work around? When is this bug going to be repaired?

**Comment by nate-dash** [comment]
same problem

**Comment by coverageandrew** [comment]
are there any updates on this? i did not have any issues when my server was running on a linux machine, but i moved to a mac studio in docker and now im running into the same issue. we also use rustdesk with our tailscale network. 
my host url is the exact same as the api i have set? 

it seems to be random as one was downloaded but none of my other four that i need to download will come through. and now i cant get that one to redownload either.
