### ISSUE TITLE
Addressbook's no longer appearing

### ISSUE THREAD

**Issue by andrewheberle** [rustdesk/rustdesk-server-pro#321]
After upgrading our RustDesk Pro server to 1.4.0 and rebuilding our custom client based on 1.2.7, and now I no longer see any address books in the client.

![image](https://github.com/user-attachments/assets/f49d887f-348a-4cf9-9fc6-ad8d577605c7)

I can see and edit shared address books in the Web UI and also add a recently used device to a shared address book from the "Recent sessions" page and that will then be visible in the Web UI.

I can see the HTTP requests from the client to the RustDesk API to retrieve the address book(s), but this is not displayed in the client.

Unfortunately, I am unsure if this occurred only after the server update, or only after the custom client was updated as I did both before testing out things (we are currently running an evaluation license, so this is not production)

**Comment by 21pages** [comment]
try below, maybe in an empty address book

https://github.com/user-attachments/assets/152cf573-c217-4aa1-ac32-e1c4467ab442
