### ISSUE TITLE
Hide CM window strategy doesn't work - Client 1.2.7 / server 1.3.12

### ISSUE THREAD

**Issue by NickCQMSRazer** [rustdesk/rustdesk-server-pro#326]
**Description:**
Even when setting the strategy to use a permanent password and to hide the connection management window, the connection management window is still visible on the remote client side.

**How to Reproduce:**
1. Create a computer with a new Windows 10 IoT Enterprise install
2. Create a custom msi installer in the server that only accepts incoming connections, disable settings, disable TCP listen port, disable user account, set a preset password.
3. Set the default strategy to use permanent password and hide the connection management window
4. Install on the client
5. Remote in
6. Optionally, do some TCP forwarding, or file transfer

** Expected behaviour:**
* The remote connection works and the CM window is never visible
*  Remote file transfer, TCP tunnels etc work and the CM window is never visible

**Actual behaviour:**
* The remote connection works and the CM window is visible. 
* A file transfer session or TCP tunnel is established in the background, but the CM window is visible.
* If a custom full screen UI is in use, then this will be minimised interrupting the user experience

**OS on local and remote side**
Windows 11 Enterprise -> Windows 10 IoT enterprise

![image](https://github.com/user-attachments/assets/481cecfc-d955-4b59-b553-5e9b9062f30b)

https://github.com/user-attachments/assets/3c9f8c4c-64e6-4901-8c0f-b2b5a8f2a750

https://github.com/user-attachments/assets/7c7112d0-def3-4579-bdd3-a58652446398

EDIT: Typo

**Comment by 21pages** [comment]
Is the setting of the controlled side like this?
![1721780561745](https://github.com/user-attachments/assets/8ff75bf1-ae02-48c9-a756-d2ba2baa3e4d)

**Comment by NickCQMSRazer** [comment]
In our strategy settings we have "Enable remote configuration modification" disabled, and the msi installer has the "disable settings" option checked, so we can not see that screen on the controlled side.

**Comment by 21pages** [comment]
https://github.com/21pages/rustdesk/releases/download/nightly/rustdesk-1.2.7-x86_64-log-hide-cm.exe

Could you run this on the controlled side, connect to it and send log `C:\Users\sun\AppData\Roaming\RustDesk\log\cm\rustdesk_rCURRENT.log` to my email, `c3VuYm9lYXN5QGdtYWlsLmNvbQo=`, base64.

**Comment by NickCQMSRazer** [comment]
Thanks 21pages. I was able to review the logs and determined that it is an issue with the synchronisation of the strategy settings when the time on the remote is incorrect.

If the time on the remote is very different to the server, then the strategy settings don't seem to work. Fixing the time on the remote resolves the issue.

**Comment by 21pages** [comment]
Are all you doing is synchronizing the time on the controlled side? I can't reproduce it with a big time difference. Before this, are other strategies other than hide cm in effect?

**Comment by NickCQMSRazer** [comment]
Yes, reboot of the controlled side after making any time changes. I set the time 2 years into the past to test, I don't know how tolerant it is to the time difference without more testing.  I don't think any of the strategies were synching, but I wasn't looking for the other settings in particular.
