### ISSUE TITLE
clients from other groups

### ISSUE THREAD

**Issue by IT-Betreuung** [rustdesk/rustdesk-server-pro#329]
I have seen with great horror
that clients from other groups
are displayed in the client software
if the client is “logged into its group”.

**Comment by 21pages** [comment]
https://rustdesk.com/docs/en/self-host/rustdesk-server-pro/permissions/#cross-group-settings

Group tab show all accessible users and devices, please check cross group rules.

**Comment by IT-Betreuung** [comment]
![Screenshot 2024-07-24 131442](https://github.com/user-attachments/assets/1f998322-b4b2-4417-a8ab-85a613443c41)
I have checked, deleted, ...  cross group rules,
clients from other groups are displayed.

In my "service- group" now is 1 Client.

**Comment by IT-Betreuung** [comment]
![Screenshot 2024-07-24 134050](https://github.com/user-attachments/assets/66bb67e0-7906-48f6-ba3d-8bddae0c8323)
There are 148 Devices registerd on my server.

40 in no group

6 groups with own strategie and user


The picture shows a group with 14 devices,
but there are 52??!

The other 38 devices come from different/ several  groups.

Server version 1.4.0

**Comment by 21pages** [comment]
Displays devices that the  logged-in user's group does not have permission to access to?

**Comment by IT-Betreuung** [comment]
Thank you!!!

My fault,
i created a new user, group and strategie,
in which "default/ new clients" have to be moved
and activated "Only admin can access unassigned devices".

But it would be verry usefull,
when the clients in the default group are not
allowed to establish connections within group,
at least the “Default group” should be editable.

**Comment by 21pages** [comment]
find one device that belongs to another user.

> So this doesn't happen?

> But it would be verry usefull,
when the clients in the default group are not
allowed to establish connections within group,
at least the “Default group” should be editable.

Yes

**Comment by IT-Betreuung** [comment]
The “little math tutoring session”
has helped,
It was a wonderful text task:

1 user has 14 devices,
52 devices are displayed,
40 devices are not assigned
and
2 devices are disabled

So nobody from other groups had access.
