### ISSUE TITLE
Unable to add anymore endpoints to address book

### ISSUE THREAD

**Issue by RichardBurt65** [rustdesk/rustdesk-server-pro#33]
100 device licence, currently sitting at 95 endpoints.

I can no longer add devices to the address book. 

Does Purslane offer pro-rata upgrades from Personal to Business plan? Maybe offer extra 100 device "add ons" ?

**Comment by rustdesk** [comment]
How many devices can you see in "device list" page on web console?

**Comment by rustdesk** [comment]
> upgrades from Personal to Business plan

We will add this soon once we release RustDesk 1.2.2 and Pro 1.1.9.

**Comment by RichardBurt65** [comment]
95

**Comment by rustdesk** [comment]
Actually, there is no unmanaged endpoint (device) limits. Exceeded device can not be assigned to user, but can still occurs in devices page as unmanaged device.

**Comment by RichardBurt65** [comment]
May be true but still unable to add to address book!

**Comment by rustdesk** [comment]
> only 71 devices

I am refactoring address book right now, I will check this.
