### ISSUE TITLE
Feature Request: Custom Client Generator "--no-tray"

### ISSUE THREAD

**Issue by xBr0th3rx** [rustdesk/rustdesk-server-pro#332]
Hello everyone,

We have the Rustdesk Server Pro and use the Custom Client generator.

We would like to have the option to disable the tray icon in the systray.

So as usual with the option "--no-tray"

Greetings

**Comment by rustdesk** [comment]
https://rustdesk.com/docs/en/self-host/client-configuration/advanced-settings/#hide-tray
