### ISSUE TITLE
Feature/Change Request - Shared Address Book "Sharing" Options

### ISSUE THREAD

**Issue by cturnerffs** [rustdesk/rustdesk-server-pro#333]
Currently, when you select "Share" on a shared address book, there is no filtering of the user/group options. This means that any user on the system can see the full list of all other usernames. **This is a security and privacy concern.**

Suggested Resolution:
If not logged in as an admin user, only allow sharing to Users and only within your group.

**Comment by rustdesk** [comment]
@21pages

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk-server-pro/releases/tag/1.4.1

**Comment by cturnerffs** [comment]
This does not seem to be resolved. 
When logged in as a user that is not an admin, and is a member of a single group...
When selecting type=User: I can then see all users on the server.
When selecting via type=Group: I can see all groups on the server.
I haven't tested the "everyone" as I am out of licensed users and can't fully test that portion.
