### ISSUE TITLE
In the Pro version, the Rustdesk login username is displayed remotely instead of the operating system username

### ISSUE THREAD

**Issue by 754628709** [rustdesk/rustdesk-server-pro#334]
Because in the scenarios we use, there are usually 5-6 people connecting to a device at the same time, but we cannot distinguish who is connecting based on the system username. We cannot prevent the other party from forcefully operating the mouse, which can lead to mouse grabbing situations, and it is unclear who is operating the mouse, causing us great trouble.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/commit/fd9b5f3c57cb8b9928c99532892af32bc78ee8c2

**Comment by 754628709** [comment]
@rustdesk How do I set the username to display Rutdesk in the advanced options.

**Comment by 754628709** [comment]
> [rustdesk/rustdesk@fd9b5f3](https://github.com/rustdesk/rustdesk/commit/fd9b5f3c57cb8b9928c99532892af32bc78ee8c2)

How do I set the username to display Rutdesk in the advanced options.

**Comment by rustdesk** [comment]
With the latest nightly build, when you login, your login username will be display on remote side.
Sorry, it is not ready in custom client yet, we will only update custom client with next release.

**Comment by 754628709** [comment]
> With the latest nightly build, when you login, your login username will be display on remote side. Sorry, it is not ready in custom client yet, we will only update custom client with next release.

So we need to wait until the 1.4.2 update to solve this problem?

**Comment by rustdesk** [comment]
RustDesk client 1.3.0
