### ISSUE TITLE
Feature request / change : Do not add some devices in managed device

### ISSUE THREAD

**Issue by Mhalkyo** [rustdesk/rustdesk-server-pro#337]
Hello, I have the same problem as on the post below, we use a lot of devices but we connect very rarely on some. Is there a solution to not have certain posts in the list? Maybe with an option in the executable to disable the addition in the managed devices. A bit like what anydesk can offer in its personalized client by disabling the addition of certain devices in the address book.

https://github.com/rustdesk/rustdesk-server-pro/issues/251

This is one of the only things I have a problem with on rustdesk, because otherwise the application is great and brings together exactly the elements that my company wants.

**Comment by rustdesk** [comment]
please no duplicate
