### ISSUE TITLE
Script for removing devices is not working anymore.

### ISSUE THREAD

**Issue by De4dm4sterBR** [rustdesk/rustdesk-server-pro#338]
Hi,

This script (https://raw.githubusercontent.com/rustdesk/rustdesk/master/res/devices.py) used for removing devices is not working anymore.

The output is:

![image](https://github.com/user-attachments/assets/dd1f6e60-a69f-45e5-b923-1a643acf8851)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/commit/9f91eada898d28d13bd7707190aeb7936dcf02e1
