### ISSUE TITLE
Custom “outgoing only” client still runs service

### ISSUE THREAD

**Issue by andrewheberle** [rustdesk/rustdesk-server-pro#339]
We have a customised client that only allows outgoing connections, however this still creates and starts a service that runs as “Local System”.

This doesn’t seem to be required as I can stop the service and there is no effect on being able to make outgoing connections. 

Is it possible to skip the setup of the service when the client is configured for outgoing connections only? Or is there some functionality that is lost without the service despite my tests?

**Comment by rustdesk** [comment]
Please use the `exe` rather than `msi`.

**Comment by rustdesk** [comment]
@fufesou `msi` does have this problem. Please fix.

**Comment by fufesou** [comment]
Got it, I'll fix it

**Comment by rustdesk** [comment]
Remember to remove old service when reinstallation.

**Comment by rustdesk** [comment]
msi outgoing has no service now.
