### ISSUE TITLE
Erro ao acessar pagina de catalago

### ISSUE THREAD

**Issue by jsfsolucoes** [rustdesk/rustdesk-server-pro#358]
<img width="499" alt="image" src="https://github.com/user-attachments/assets/af90e728-4be2-4877-af71-c5e62e13bbc1">

nesse caso quando da esse erro como resolve?

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/wiki/FAQ#failed-to-log-in-with-custom-client-build-or-public-release-with-wrong-api-settings
