### ISSUE TITLE
OIDC Callback stuck in http mode

### ISSUE THREAD

**Issue by jpasley** [rustdesk/rustdesk-server-pro#361]
Hey all,

So I ma having an issue with Azure AD integration. I setup per the instructions provided online and Microsoft call back URL has to be https. The problem is the default callback URL that is not editable in Rust Server is "http". This is causing an error when attempting to authenticate with our M365 credentials because the call back urls do not match.

**Comment by rustdesk** [comment]
The callback follows the address bar schema when you update oidc config.

![image](https://github.com/user-attachments/assets/876cf660-b78e-4be1-8faf-7679e2fc9739)

**Comment by networkadminasai** [comment]
if you access it via https by putting in an application gateway in the front to handle the https to http wrapping it will clear it up.

**Comment by QuigonJohnn** [comment]
> screenshot (display your browser addressbar also) of Settings -> OIDC page please.

<img width="1419" height="1117" alt="Image" src="https://github.com/user-attachments/assets/e9a98cd7-66dd-450c-a9b4-ec5ab080a2e1" />

**Comment by rustdesk** [comment]
Your screenshot is not our Pro.
