### ISSUE TITLE
cannot login using windows client to server account

### ISSUE THREAD

**Issue by jpasley** [rustdesk/rustdesk-server-pro#362]
I cannot get the client to allow me to login to my server account.

![image](https://github.com/user-attachments/assets/5d6a9fe2-18f0-4cbc-9bf7-aa1a0773fb35)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/wiki/FAQ#failed-to-log-in-with-custom-client-build-or-public-release-with-wrong-api-settings
