### ISSUE TITLE
Windows 11 Clients keep getting disabled in RustDesk Server Console

### ISSUE THREAD

**Issue by MerryPickles** [rustdesk/rustdesk-server-pro#394]
This keeps happening on Windows 11 clients, and is driving me crazy! 
I have uninstalled and reinstalled RustDesk on these client PCs and they show up just fine in the RD Server Console, but they don't show up in the RD app in Windows. 
When I look in the console, these clients keep getting disabled. I can enable them, but they just get disabled again.
Need help! Ths is a live production environment, and this is slowing me down. Thanks in advance.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk-server-pro/discussions/182
