### ISSUE TITLE
[Feature] Add version information to .msi-file

### ISSUE THREAD

**Issue by LarsK1** [rustdesk/rustdesk-server-pro#411]
Hi everyone,
currently the msi-file is unusable for intune managment, because the version string is missing.
Should:
![image](https://github.com/user-attachments/assets/0bb75034-26a8-486d-8044-4bcd26ff1b51)

Is:
![image](https://github.com/user-attachments/assets/784f1cb1-9fbd-400a-b097-9d5d41402e12)

Can you please fix that quickly?

**Comment by rustdesk** [comment]
@fufesou

**Comment by fufesou** [comment]
@LarsK1 Thanks for your feedback.

I cannot find a version property for the msi file. https://wixtoolset.org/docs/schema/wxs/bundle/

I've checked mariadb https://mariadb.org/download/?t=mariadb, inkscape and a file named `MSI Development Tools-x86_en-us.msi`, they also do not provide the property.

![image](https://github.com/user-attachments/assets/991c8f5d-341a-46cd-b51f-6e705ee62f02)

![image](https://github.com/user-attachments/assets/98b89499-0054-4b74-b054-5b25c31def2e)

![image](https://github.com/user-attachments/assets/8ccd41c4-020f-4ccf-8806-e39baae02a22)

Could you please double confirm you really need this property for intune managment?
Sorry I'm not familiar with intune management.

Maybe this property is not needed. Maybe the perperty is needed, I should find some other ways to specify the version of the msi.

**Comment by LarsK1** [comment]
@fufesou Hi,
we opened a support ticket at Microsoft and they told us so.
Maybe this will help you:
https://stackoverflow.com/questions/626033/how-can-i-set-the-wix-installer-version-to-the-current-build-version

**Comment by fufesou** [comment]
Yes, we do use `Package/@Version`(v4), `Product/@Version`(v3) 

https://github.com/rustdesk/rustdesk/blob/22c84bbbd19d85e4064355f94e48921893e909b3/res/msi/Package/Package.wxs#L7

But the value is set to the exe extracted from the `msi` package.

<img width="531" alt="a" src="https://github.com/user-attachments/assets/e0a32921-b448-474c-9957-5000b7f1e1c3">

**Comment by fufesou** [comment]
https://www.reddit.com/r/Intune/comments/hat1r6/comment/fv71x1d/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

> If the .msi's have the right version metadata (most do) then all you have to do is re-upload the new msi into the same App profile you created for the old msi. 

Could you please try "re-upload the new msi"

**Comment by LarsK1** [comment]
It works, as soon as I toggle the button "ignore version" to Yes
![image](https://github.com/user-attachments/assets/af029328-4e75-4ade-8579-207d9c798000)

**Comment by fufesou** [comment]
Or try "Ignore app version" like this?

https://support-splashtopbusiness.splashtop.com/hc/en-us/articles/360039523631-Deploy-using-Microsoft-Intune-with-MSI-file
