### ISSUE TITLE
username@device_name not showing up

### ISSUE THREAD

**Issue by chileocat** [rustdesk/rustdesk-server-pro#416]
Some time ago there was this big https://github.com/rustdesk/rustdesk-server-pro/issues/174. And it should be resolved since version 1.2.4 of RustDesk.

We're running RustDesk Server Pro 1.4.4 with custom clients, which have the version 1.3.1.28815005 and still have  this problem. It shows neither the devicename not the logged in user.

![grafik](https://github.com/user-attachments/assets/a7dcd4ed-bce0-4d6c-971e-7c5fe88e0cc5)

What we already tried: uninstalling the Client, deleting the ID from the server and reinstalling the client again.

**Comment by rustdesk** [comment]
https://rustdesk.com/docs/en/self-host/rustdesk-server-pro/faq/#why-are-my-logs--device-names-are-empty

**Comment by chileocat** [comment]
Thanks, found the problem. Do clients update the information from time to time?

**Comment by rustdesk** [comment]
Please try login, if login works, this will work.

**Comment by chileocat** [comment]
I checked this and it's working. But restarting the rustdesk host/client on my machine won't update any informations. If I enable debug logging, do I see any updates with datas from clients?

**Comment by rustdesk** [comment]
Restart service, not restart the gui. If it is windows, please restart rustdesk service from task manager.

**Comment by chileocat** [comment]
Rebooting the service isn't the problem - even a simple windows reboot should do the job. The problem is still, I get no informations about the device name and logged in user. But the ID shows green/red according to the notebook status.

**Comment by rustdesk** [comment]
please fix https://github.com/rustdesk/rustdesk-server-pro/issues/417 first

**Comment by chileocat** [comment]
Agree, I post an update here later.

**Comment by chileocat** [comment]
As in here https://github.com/rustdesk/rustdesk-server-pro/issues/417 - using direct connection to Rustdesk server and everything works.
