### ISSUE TITLE
Azure oidc login not working in desktop app (tls failure)

### ISSUE THREAD

**Issue by chileocat** [rustdesk/rustdesk-server-pro#417]
While it's working perfektly in with the webconsole, trying to login with azure in the desktop app, leads to an error:

![grafik](https://github.com/user-attachments/assets/e5a2490b-d6ba-4a4c-8e68-60e7ba14a620)

**Comment by rustdesk** [comment]
@fufesou

**Comment by fufesou** [comment]
> The error message "Das Format der empfangenen Nachricht war unerwartet oder fehlerhaft." translates to "The format of the received message was unexpected or invalid." The accompanying OS error code -2146893018 typically indicates an issue related to security or encryption.

> This specific error code is often associated with problems in secure communications, such as SSL/TLS handshake failures. Here are some common causes:

> **Certificate Issues**: The server's certificate might be invalid, expired, or not trusted by the client.
**Protocol Mismatch**: The client and server may not support the same versions of TLS/SSL.
**Message Corruption**: The data being sent or received could be corrupted or improperly formatted.
**Configuration Problems**: There could be incorrect settings in the client or server configuration regarding security protocols.

> To resolve this issue, you may want to check the validity of the SSL certificate, ensure that both client and server support compatible security protocols, and verify there are no network issues causing message corruption.

From chatgpt

It seems your SSL is not correctly configurated. But you can login in the web console.

@chileocat Hi, could you please agian?

Or could you please try `curl https://rustdesk.convalere.ch/api/login-options` on your command line?

I've tried the above command, and get 
```
curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by fufesou** [comment]
Have you trusted the certificate on the client machine?

**Comment by chileocat** [comment]
@fufesou I'm investigating this ssl problem - our IT partner got some certificates from certum. Looks like these are not complete trustet by default. At the moment I'm searchting the right root certificates for installing. Normal webconsole logins from the client machine already works, also the azure login.

I think my other issue https://github.com/rustdesk/rustdesk-server-pro/issues/416 is also related to this.

**Comment by chileocat** [comment]
@fufesou Can you verify again? My linux machine gives me the following:

`curl https://rustdesk.convalere.ch/api/login-options
["oidc/azure","common-oidc/[{\"name\":\"azure\"}]"]`

**Comment by fufesou** [comment]
> Can you verify again?

Now it's Ok. It also gives me ` ["oidc/azure","common-oidc/[{\"name\":\"azure\"}]"]`

Can you login in the desktop app now?

**Comment by chileocat** [comment]
Got still the same error. From another issue I found your oidc.exe tool, this is the output when I check my tenant url:
![grafik](https://github.com/user-attachments/assets/d992dd33-8d0c-4fb5-a4db-47511c6ec935)

still my other issue isn't resolved. Maybe I have to switch to a LE installation for checking, it the certum ssl is the problem

**Comment by chileocat** [comment]
@fufesou Yep, still this os error.

**Comment by fufesou** [comment]
The oidc.exe directly test the OIDC Provider url, not our server.

> the certum ssl is the problem

Yes, maybe still the strange issue.

Could you please execute `curl https://rustdesk.convalere.ch/api/login-options` on the desktop app machine?

**Comment by chileocat** [comment]
Works like on the linux machine

`PS C:\Users\benjamin> curl https://rustdesk.convalere.ch/api/login-options
["oidc/azure","common-oidc/[{\"name\":\"azure\"}]"]`

**Comment by fufesou** [comment]
Same reason, not sure if it is related to the certum ssl is the problem.

https://github.com/seanmonstar/reqwest/discussions/2411#discussioncomment-10582105

https://github.com/seanmonstar/reqwest/issues/2004

**Comment by chileocat** [comment]
this would meanI ha e to compile the client by myself? Or would it be possible to add this as a feature in the costum builder on the webconsole?

I first migrate to LE and check it again.

**Comment by fufesou** [comment]
> I first migrate to LE and check it again.

Yes. Please do it first.

We have to use "native tls" to make sure it works in most cases. https://github.com/rustdesk/rustdesk-server-pro/issues/189

**Comment by chileocat** [comment]
Okay, I switched to LE and the webconsole is now running with a LE certificate. I can successfully login with the local admin user. But trying the azure login button, stills gives me this os error.

**Comment by fufesou** [comment]
> stills gives me this os error.

Sorry for the inconvenience. I'll put a fix with an option to choose the tls later.

**Comment by chileocat** [comment]
No problem, thanks for helping!

**Comment by chileocat** [comment]
Just for confirmation, I created a new client which connects directly to the Rustdesk Server over 21114 and Azure login works as expected.

**Comment by fufesou** [comment]
Yes, https is the issue.

I've filed an issue here https://github.com/seanmonstar/reqwest/issues/2449

Can I use your server in an example?

**Comment by chileocat** [comment]
Well now it works... dang it! With the intermediate configuration everything works - when I switch to modern without any backward compatibility it breaks.

I make a second server entry, so you can check against TLS1.3 and TLS1.2, I post an update when I'm ready.

**Comment by chileocat** [comment]
Okay so I made a second server:
https://rustdesk.convalere.ch is set up with minTLS 1.2 and so backward compatible, while https://rustdesk2.convalere.ch is min TLS1.3.

Can you verify this?

**Comment by fufesou** [comment]
Yes, it works fine now.

**Comment by fufesou** [comment]
https://rustdesk.convalere.ch/ and https://rustdesk2.convalere.ch/ both do not work now.
It works an hour ago.

**Comment by chileocat** [comment]
Could you check again? Should work now.

**Comment by fufesou** [comment]
Both still the same error. `The message received was unexpected or badly formatted`

https://github.com/sfackler/rust-native-tls/issues/305

But https://rustdesk.convalere.ch/ after you just writing this comment is good. https://github.com/rustdesk/rustdesk-server-pro/issues/417#issuecomment-2415874192

**Comment by fufesou** [comment]
@chileocat Hi, I've tested request `https://rustdesk.convalere.ch/` and `https://rustdesk2.convalere.ch/`.

The first domain works fine, the second goes with the tls failure.

So it is this reason? https://github.com/rustdesk/rustdesk-server-pro/issues/417#issuecomment-2415843704

**Comment by chileocat** [comment]
Sorry I forgot to give you an update. Yes it's about TLS1.3 - when I force to use min TLS1.3 the desktop apps doesn't work anymore. If I switch to TLS1.2 it's all good.
