### ISSUE TITLE
OIDC sign-in method has gone from desktop client

### ISSUE THREAD

**Issue by saidlisad** [rustdesk/rustdesk-server-pro#421]
Hello, just migrated my rustdesk from one to another docker instance. Figured out that oidc azure sign-in has gone from desktop client. 
Sign-in via web works fine.
![image](https://github.com/user-attachments/assets/65f1b500-6e09-4286-90cb-e19bccc5ca11)

**Comment by rustdesk** [comment]
Make sure `API` is set correctly first, https://github.com/rustdesk/rustdesk/wiki/FAQ#failed-to-log-in-with-custom-client-build-or-public-release-with-wrong-api-settings

**Comment by fufesou** [comment]
Please
1. Confirm the api server is still correct.

<img width="500" alt="a" src="https://github.com/user-attachments/assets/b373ce28-20e1-4219-bd5d-b833056b3da7">

2. Start a command line and run `curl <api-server>/api/login-options`

**Comment by saidlisad** [comment]
![image](https://github.com/user-attachments/assets/feb0603e-2cc8-42f7-93e1-5d629a59e79b)
Try to log in with local user

**Comment by fufesou** [comment]
Is the "API Server" empty in your client -> Settings -> Network?

You need to explictly set it if new port is applied/redirected.

**Comment by saidlisad** [comment]
solved
