### ISSUE TITLE
Unable to connect after remote restart (when not using UDP)

### ISSUE THREAD

**Issue by sys-media** [rustdesk/rustdesk-server-pro#423]
Hello,
Rustdesk support recommended that I report here.
We have now created a custom client with UDP disabled for our secure locations.
We are currently testing the operation, but there is a pattern of not being able to reconnect after a remote reboot.

1. installed on the destination computer and performed a remote restart.
![①just_reboot](https://github.com/user-attachments/assets/21be8c81-dbd7-4d1a-b2b4-119be6e4c866)
```
Connection error
Existing connection was forcibly disconnected by the remote host. (os error 10054)
[Close][Connect via relay server][Retry].
```
2. Wait without closing the remote connection window.
3. remotely restart the destination computer. (Wait until it starts and goes to the lock screen.)
4. reconnecting while in the lock screen does not work.
![②after_reboot](https://github.com/user-attachments/assets/cfe3cbc7-dd89-406a-87ca-1afe066deb6a)
``` Connecting...
Connecting...
[Cancel]
```
![③connect_fail](https://github.com/user-attachments/assets/e969f3c1-eb6e-404f-be5a-9a11f2c86364)
```
Connection Error
Could not connect via the rendezvous server. Please try again later.
[Reconnect][OK].
```

I have tried [Reconnect], [Connect via rendezvous server], closing the remote connection window and reconnecting by entering the connection history or ID directly, etc., but all of them give me the error message “Connecting...” followed by “Could not connect via rendezvous server. but all of them show “Connecting...” followed by the error message “Could not connect via rendezvous server”.
Also, in this state, unless you restart the Rustdesk service on the computer you are connecting to, you will not be able to connect to them no matter how long you wait.
The same is true if you right-click on the destination computer from the connection history and force a relay connection.
<https://github.com/rustdesk/rustdesk/wiki/FAQ#force-relay>

However, if the remote connection window is closed immediately after performing a remote restart in “2.”, the connection can be made again.
(You will need to wait a minute or two after the lock screen before you can connect.)
The online status of the destination computer displayed in Rustdesk on the source computer was always lit green if the remote connection window was not closed.
(If the remote connection window was closed, it would turn orange once and then green.)
On the server's Rustdesk console, Devices, it turns red once and then back to green in both cases.
If I install a custom client with UDP enabled, I can reconnect without any problem.

Is this behavior a specification?
Thank you in advance.

Environment
・Rustdesk Server Pro 1.4.4
・Rustdesk Client 1.3.1 (both)
・Source computer: Windows11 23H2
・Destination computer: Windows10 22H2

**Comment by rustdesk** [comment]
Thanks, we have reproduced it, @21pages will fix it.
This happens when one device changes from UDP to TCP, the server still rememer it is UDP, not use TCP instead. Restarting `hbbs` service process can help this.

**Comment by sys-media** [comment]
Understood. Thank you very much.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk-server-pro/releases/tag/1.4.5

**Comment by sys-media** [comment]
Thank you for your response. I am currently working on another matter and am unable to check it, so I will check it as soon as that is finished.

**Comment by sys-media** [comment]
I checked this after I finished dealing with another matter. I was able to reconnect! Thank you very much!
