### ISSUE TITLE
 The nearest relay server is not always preferred

### ISSUE THREAD

**Issue by Rocky-Jinxing** [rustdesk/rustdesk-server-pro#425]
I added 2 relay servers, both of which are valid. When I connect to a controlled device in China, each connection polls to a different relay server. The nearest one is not preferred. 

My version RustDesk Server Pro 1.4.4

![image](https://github.com/user-attachments/assets/a1cd30a1-50a4-4318-ae4f-8c882af54af7)

**Comment by rustdesk** [comment]
https://rustdesk.com/docs/en/self-host/rustdesk-server-pro/relay/#register-and-download-the-geolite2-city-database-file

**Comment by Rocky-Jinxing** [comment]
> https://rustdesk.com/docs/en/self-host/rustdesk-server-pro/relay/#register-and-download-the-geolite2-city-database-file

@rustdesk I have installed GeoLite2 City and added two, the first one is Hangzhou, China, and the second one is Tokyo, Japan, but every time I connect to the controlled device, it still polls to different relay servers, and when I click Reload Geo, no log information appears.

![image](https://github.com/user-attachments/assets/a04b9ed2-cdb0-422e-bbb7-3f08d9fa289a)
![image](https://github.com/user-attachments/assets/201ecacb-0f4d-40bd-9a10-557691b27054)

**Comment by Rocky-Jinxing** [comment]
> > https://rustdesk.com/docs/en/self-host/rustdesk-server-pro/relay/#register-and-download-the-geolite2-city-database-file
> 
> @rustdesk I have installed GeoLite2 City and added two, the first one is Hangzhou, China, and the second one is Tokyo, Japan, but every time I connect to the controlled device, it still polls to different relay servers, and when I click Reload Geo, no log information appears.
> 
> ![image](https://private-user-images.githubusercontent.com/84103483/379521523-a04b9ed2-cdb0-422e-bbb7-3f08d9fa289a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MzcxNTMsIm5iZiI6MTcyOTczNjg1MywicGF0aCI6Ii84NDEwMzQ4My8zNzk1MjE1MjMtYTA0YjllZDItY2RiMC00MjJlLWJiYjctM2YwOGQ5ZmEyODlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDAyMjczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliOTE0ZjExMTRjNDdhZTdkYmNmZWUyYTJmMzE1ODJjNmRiNDFjMmVmMGIzM2Q5OWRmMjRiYzU1Yzk2ZDUzOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MSUgNPlu_HuwJ4VXwk3YCpQgnsaxSY1Nlerlf22Ru6w) ![image](https://private-user-images.githubusercontent.com/84103483/379522024-201ecacb-0f4d-40bd-9a10-557691b27054.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MzcxNTMsIm5iZiI6MTcyOTczNjg1MywicGF0aCI6Ii84NDEwMzQ4My8zNzk1MjIwMjQtMjAxZWNhY2ItMGY0ZC00MGJkLTlhMTAtNTU3NjkxYjI3MDU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDAyMjczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyNzQzODI0Mjg4ODY5NjMyZGUwNzg3MmY4YmRiY2E0NzE4NGM5NmI0NDY0NDVlMjc2MjI1ZDEwMDBiYWUyOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Vl8ulWP_9Rib4eat1pI3R1CNdj6TSO9p5Cxl47_aWRg)



input root@libiao-vm :/usr/bin# RUST_LOG=debug ./ hbbs， In the recorded logs, keywords such as GeoLite2 City, override, relay servers=cannot be found.

**Comment by Rocky-Jinxing** [comment]
@rustdesk Please help to resolve the relay polling issue.

**Comment by rustdesk** [comment]
This quite relies on the data of ip database, as far as I know, many IPs in China are not in this free database.

**Comment by rustdesk** [comment]
There is some log when clicking on "reload geo"

![image](https://github.com/user-attachments/assets/341ba29a-fa16-4bbf-a6d2-2a53d322b623)

**Comment by rustdesk** [comment]
You can also confirm if relays work on your server by running.

`echo rs | netcat 127.0.0.1 21115`

**Comment by Rocky-Jinxing** [comment]
> This quite relies on the data accuracy of ip database, as far as I know, many IPs in China are not in this free database.

@rustdesk I have found the IP data on the official website, and the screenshots below show the IP queries of two relays, namely China and Japan.
![image](https://github.com/user-attachments/assets/62346e81-663f-4468-867e-c77f7f6a67a3)


The screenshot below shows the IP addresses of the controlled end in China that were queried, displaying China.

![image](https://github.com/user-attachments/assets/a72623f9-ae82-4539-a802-ef5452847e42)

Even if it cannot be queried, the polling method should not be used on different relay servers.

**Comment by Rocky-Jinxing** [comment]
> `echo rs | netcat 127.0.0.1 21115`

@rustdesk 
![image](https://github.com/user-attachments/assets/3d4fd241-d49c-4753-90ff-c94fe38f24fc)
It is working.

**Comment by rustdesk** [comment]
random here?

**Comment by rustdesk** [comment]
Are you sure `hbbs` can see you real ip?

**Comment by Rocky-Jinxing** [comment]
> random here?
> 
> ![image](https://private-user-images.githubusercontent.com/71636191/379992268-e21b415a-3888-45ac-a530-bb0f9fed0e7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MjQxMDksIm5iZiI6MTcyOTgyMzgwOSwicGF0aCI6Ii83MTYzNjE5MS8zNzk5OTIyNjgtZTIxYjQxNWEtMzg4OC00NWFjLWE1MzAtYmIwZjlmZWQwZTdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDAyMzY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlNzA2NmY3NTJjNzQ3ZTI3MDU3ODI4YTlkN2I4M2EwYWNjOGE4MmUyNWZmMWM5OGM1NjE4YjI2NDNiYTc2MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WUoejrGz0wVKU5eqH-0WJAyT_KqWfsbVFkkJMJfGCk0)

@rustdesk Please refer to the screenshot.

![image](https://github.com/user-attachments/assets/5554915e-42b7-425d-a2d1-afff8fb9a76e)

**Comment by Rocky-Jinxing** [comment]
> Are you sure `hbbs` can see you real ip?

@rustdesk  Echo rs | netcat 127.0.0.1 21115, the two IPs I am viewing are indeed my real IPs

**Comment by rustdesk** [comment]
Please use different ip

**Comment by Rocky-Jinxing** [comment]
> Please use different ip. You are using the relay ip test the relay, the caculation result is the same for any relay,so it is random. Hope you can understand this simple math.

@rustdesk The controlled IP of the test is indeed from 183.129, but in fact, I tested it by polling. I checked the delay and found that the delay to Japan is usually more than 100ms, and the delay through the relay in China is 20ms.
![image](https://github.com/user-attachments/assets/4de2d8fb-1abe-438a-a8ec-5f9267003f30)

**Comment by rustdesk** [comment]
Sorry, I have no a solution for this yet, https://github.com/rustdesk/rustdesk/discussions/7934.

**Comment by Rocky-Jinxing** [comment]
> Sorry, I have no a solution for this yet, [rustdesk/rustdesk#7934](https://github.com/rustdesk/rustdesk/discussions/7934). I know you will say we should choose a relay with detecting latency. But still sorry, we have no a implementation yet.

@rustdesk It's not a problem with inaccurate maps now, it's normal to test from the web end, but it's not correct in actual use.
---Get Relay Server on the web end is testing the controlled IP in China using a Chinese proxy.
---The actual use does indeed involve polling from relay servers in China and Japan.

**Comment by rustdesk** [comment]
> It's not a problem with inaccurate maps now, it's normal to test from the web end, but it's not correct in actual use.

Sorry, we have no a solution or implementation yet. This is not in our high priority list.

**Comment by Rocky-Jinxing** [comment]
> > It's not a problem with inaccurate maps now, it's normal to test from the web end, but it's not correct in actual use.
> 
> I know all you said, but sorry, we have no a solution or implementation yet. This is not in our high priority list.

@rustdesk So actually, the current relay settings are useless, only one relay server can be used, is that correct?

**Comment by rustdesk** [comment]
<img width="1104" alt="Screenshot 2024-10-25 at 11 03 31 AM" src="https://github.com/user-attachments/assets/70178e4c-b4be-4edd-a552-ebab86490d62">
<img width="1065" alt="Screenshot 2024-10-25 at 11 10 30 AM" src="https://github.com/user-attachments/assets/27ec4b65-e150-4af7-a152-4b0a5cdf9035">

**Comment by Rocky-Jinxing** [comment]
@rustdesk I want to say that there is no problem when I test it from the WEB console.
222.92 is Chinese ip
![image](https://github.com/user-attachments/assets/731d21f1-1046-493e-b8fd-7071bb4ea2f7)
114.177 is Japan ip
![image](https://github.com/user-attachments/assets/57516e23-469d-4c2a-9b73-45f62f3d92b7)

In actual use, as shown in the figure below.
222.92 is Chinese ip, with a latency of 17ms. It is obviously connected from a relay server in China.
![image](https://github.com/user-attachments/assets/f28909d8-19cf-40ea-bfe3-536078774816)

222.92 is Chinese ip, with a delay of 183ms. It is obviously connected from a relay server in Japan.
![image](https://github.com/user-attachments/assets/e427c86e-d22a-4ea9-92e1-8e7c384563cc)

What I mean is that testing from the WEB console is different from actual use, please check this.

**Comment by rustdesk** [comment]
Please show the `hbbr` log.

**Comment by Rocky-Jinxing** [comment]
> Please show your two `hbbr` log. It will tell what really happened.

@rustdesk id=491653892
[hbbs.log](https://github.com/user-attachments/files/17515416/hbbs.log)

**Comment by rustdesk** [comment]
Below all are local ip
``
[2024-10-25 11:40:31.509718 +08:00] INFO [/project/src/rendezvous_server.rs:1129] TCP punch hole response to 192.168.73.251:62802 from 172.30.0.1:10144
[2024-10-25 11:40:32.735827 +08:00] INFO [/project/src/rendezvous_server.rs:939] Request relay 491653892 [::ffff:172.30.0.1]:1154 from 192.168.73.251:62804
[2024-10-25 11:40:58.089184 +08:00] INFO [/project/src/rendezvous_server.rs:1328] Punch hole 208157988 192.168.73.44:65083 request from 192.168.72.217:62596
[2024-10-25 11:40:58.138122 +08:00] INFO [/project/src/rendezvous_server.rs:1129] TCP punch hole response to 192.168.72.217:62596 from 192.168.73.44:56240
```

**Comment by rustdesk** [comment]
Below choose are wrong?

```
[2024-10-25 11:15:05.507672 +08:00] INFO [src/rendezvous_server.rs:1589] Nearest relay server chosen for 183.129.199.211 between 222.92.52.34 and 222.92.52.34
[2024-10-25 11:15:06.168604 +08:00] INFO [src/rendezvous_server.rs:1589] Nearest relay server chosen for 183.129.199.211 between 222.92.52.34 and 222.92.52.34
[2024-10-25 11:15:06.362208 +08:00] INFO [src/rendezvous_server.rs:1589] Nearest relay server chosen for 183.129.199.211 between 222.92.52.34 and 222.92.52.34
[2024-10-25 11:15:10.932771 +08:00] INFO [src/rendezvous_server.rs:1589] Nearest relay server chosen for 183.129.199.211 between 222.92.52.34 and 222.92.52.34
[2024-10-25 11:15:11.325933 +08:00] INFO [src/rendezvous_server.rs:1589] Nearest relay server chosen for 183.129.199.211 between 222.92.52.34 and 222.92.52.34
[2024-10-25 11:15:11.464123 +08:00] INFO [src/rendezvous_server.rs:1589] Nearest relay server chosen for 183.129.199.211 between 222.92.52.34 and 222.92.52.34
[2024-10-25 11:15:15.384827 +08:00] INFO [src/rendezvous_server.rs:1589] Nearest relay server chosen for 183.129.199.211 between 222.92.52.34 and 222.92.52.34
[2024-10-25 11:15:15.881676 +08:00] INFO [src/rendezvous_server.rs:1589] Nearest relay server chosen for 183.129.199.211 between 222.92.52.34 and 222.92.52.34
[2024-10-25 11:15:16.066278 +08:00] INFO [src/rendezvous_server.rs:1589] Nearest relay server chosen for 183.129.199.211 between 222.92.52.34 and 222.92.52.34
[2024-10-25 11:15:16.220926 +08:00] INFO [src/rendezvous_server.rs:1589] Nearest relay server chosen for 183.129.199.211 between 222.92.52.34 and 222.92.52.34
[2024-10-25 11:15:16.378979 +08:00] INFO [src/rendezvous_server.rs:1589] Nearest relay server chosen for 183.129.199.211 between 222.92.52.34 and 222.92.52.34
[2024-10-25 11:15:16.531174 +08:00] INFO [src/rendezvous_server.rs:1589] Nearest relay server chosen for 183.129.199.211 between 222.92.52.34 and 222.92.52.34
[2024-10-25 11:16:27.556317 +08:00] INFO [/project/src/rendezvous_server.rs:1328] Punch hole 30778227 192.168.72.23:63530 request from 192.168.73.157:13878
[2024-10-25 11:16:27.591876 +08:00] INFO [/project/src/rendezvous_server.rs:1129] TCP punch hole response to 192.168.73.157:13878 from 192.168.72.23:60105
[2024-10-25 11:16:55.508032 +08:00] INFO [src/rendezvous_server.rs:1589] Nearest relay server chosen for 34.84.114.184 between 114.177.109.11 and 114.177.109.11
[2024-10-25 11:16:55.742589 +08:00] INFO [src/rendezvous_server.rs:1589] Nearest relay server chosen for 34.84.114.184 between 114.177.109.11 and 114.177.109.11
[2024-10-25 11:16:55.910347 +08:00] INFO [src/rendezvous_server.rs:1589] Nearest relay server chosen for 34.84.114.184 between 114.177.109.11 and 114.177.109.11
[2024-10-25 11:16:56.099186 +08:00] INFO [src/rendezvous_server.rs:1589] Nearest relay server chosen for 34.84.114.184 between 114.177.109.11 and 114.177.109.11
```

**Comment by Rocky-Jinxing** [comment]
> Below all are local ip
> 
> ```
> [2024-10-25 11:40:31.509718 +08:00] INFO [/project/src/rendezvous_server.rs:1129] TCP punch hole response to 192.168.73.251:62802 from 172.30.0.1:10144
> [2024-10-25 11:40:32.735827 +08:00] INFO [/project/src/rendezvous_server.rs:939] Request relay 491653892 [::ffff:172.30.0.1]:1154 from 192.168.73.251:62804
> [2024-10-25 11:40:58.089184 +08:00] INFO [/project/src/rendezvous_server.rs:1328] Punch hole 208157988 192.168.73.44:65083 request from 192.168.72.217:62596
> [2024-10-25 11:40:58.138122 +08:00] INFO [/project/src/rendezvous_server.rs:1129] TCP punch hole response to 192.168.72.217:62596 from 192.168.73.44:56240
> ```
> 
> # That's why I asked this.
> > Are you sure hbbs can see you real ip?

@rustdesk 

![image](https://github.com/user-attachments/assets/abda3736-cf63-4e23-9e2a-df0f6276762b)
Are you saying that the IP from must be a public IP, not a private IP?

**Comment by Rocky-Jinxing** [comment]
@rustdesk 
I found through testing that, as you said, if the device in the web management backend sees a private IP address, it will have polling issues. However, if the information shows a public IP address, it will select a relay server based on the results of the relay test.

![image](https://github.com/user-attachments/assets/4e07c2e8-ee45-44df-a0ae-bc7076dbeb0b)

However, our PRO server is deployed within the company. When connecting to the Rustdesk server from within our company, the backend will definitely display a private network address. So please help solve the problem that the device is a private network address and the relay server will poll.

**Comment by rustdesk** [comment]
There is no way to solve this.

**Comment by Rocky-Jinxing** [comment]
@rustdesk I think you can add an extension option after the relay server settings, which allows you to choose which relay server to enforce the IP addresses of those segments to go to, and users can also set where to go according to their preferences.

**Comment by rustdesk** [comment]
Maybe we can, but sorry, it is not in our high priority.

**Comment by Rocky-Jinxing** [comment]
> Maybe we can, but sorry, it is not in our high priority.

@rustdesk Priority needs to be raised, otherwise servers deployed on the company's intranet cannot use relays.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk-server-pro/releases/tag/1.4.5

**Comment by Rocky-Jinxing** [comment]
> https://github.com/rustdesk/rustdesk-server-pro/releases/tag/1.4.5

@rustdesk Thank you very much, this can solve the problem that the server deployed on the company's intranet cannot use relay.

![image](https://github.com/user-attachments/assets/6774c4a4-0366-48b9-84df-79ee2ef49517)
