### ISSUE TITLE
MacOS Arm TLS Issue

### ISSUE THREAD

**Issue by nebulex77** [rustdesk/rustdesk-server-pro#427]
Hi Team,

I have deployed RD Server on Ubuntu Server and after installing RustDesk client (ARM) on an MacOS if I login with an account setup on the Rust Desk server I get the error below, appreciate your guidance

![image](https://github.com/user-attachments/assets/0c077800-c9bd-4f51-9cc5-45ea4805b1b2)

Handshare error in client OS error: WRONG_VERSIONS(TLS_record.cc:231))

**Comment by rustdesk** [comment]
https://stackoverflow.com/questions/57517116/why-im-getting-wrong-version-number-when-making-a-post-request-to-a-https-serve this one might give some clue

**Comment by nebulex77** [comment]
Thank you very much second link helped fix the issue
