### ISSUE TITLE
DynDNS possible?

### ISSUE THREAD

**Issue by computertechnikberger** [rustdesk/rustdesk-server-pro#429]
Hi,

we get the error message "License already in use by another IP, please follow this link https://rustdesk.com/docs/en/self-host/rustdesk-server-pro/license/#invoices-license-retrieval-and-migration to migrate your license to the new IP."

We don't have a static IP-Adress and use DynDNS. Our IP-Address changes every 24 hours. Is there a way to use it anywhere?

**Comment by rustdesk** [comment]
Or not use docker.

**Comment by computertechnikberger** [comment]
Unfortunately with Docker. What do I have to do if it is installed without Docker.

**Comment by rustdesk** [comment]
https://rustdesk.com/docs/en/self-host/rustdesk-server-pro/installscript/

https://rustdesk.com/docs/en/self-host/rustdesk-server-pro/#migrate-to-new-host-and-backup--restore







---- On Wed, 30 Oct 2024 16:49:43 +0800 computertechnikberger ***@***.***> wrote ---





Unfortunately with Docker. What do I have to do if it is installed without Docker.
