### ISSUE TITLE
Install script not working in France

### ISSUE THREAD

**Issue by ArnaudG-Eyesoft** [rustdesk/rustdesk-server-pro#446]
The `install.sh` script is using the command `dig +short "${RUSTDESK_DOMAIN}" @resolver1.opendns.com` to check the provided domain name. Since OpenDNS is now unavailable in France, we cannot use the `install.sh` script with a Domain name in France. Here is the answer returned by dig when using OpenDNS from France:

> The OpenDNS service is currently unavailable in France and some French territories due to a court order under Article L.333-10 of the French Sport Code. See https://support.opendns.com/hc/en-us

A simple answer is to copy/paste the script, replace `resolver1.opendns.com` with `8.8.8.8` (Or any other public resolver) but that is not as simple as running a single command.

It would be nice to provide a way of switching the DNS server to another when using the script.

Thanks!

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk-server-pro/commit/e478d266b0f36d35980f6bc0f0d75336e0316abe
