### ISSUE TITLE
OIDC custom server (GitLab) - wrong scope

### ISSUE THREAD

**Issue by Peppershade** [rustdesk/rustdesk-server-pro#53]
I came across a small issue which I was able to kinda solve manually.

I tried setting up OpenID connect to GitLab, with no luck in the first try. It said the scope was malformed, after some investigation I found that the scope was by default wrong. The default scope given in the URL is (scope=openid+email+profile+offline_access), however, "offiline_access" is an unknown scope to GitLab and doesn't seem very standard. After modifying the URL myself and removing the "offline_access" scope, I got authenticated successfully and redirected to RustDesk.

I searched in GitLab for the scope, but it doesn't seem to be there.

I think "offline_access" shouldn't be a standard OIDC scope, or at least make the default scope editable.

**Comment by rustdesk** [comment]
@Peppershade Thanks， good point.

**Comment by rustdesk** [comment]
@Peppershade Thanks， good point.

**Comment by fufesou** [comment]
Ref: https://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess

But this scope may not be supported by all oidc/oauth2.0 providers.

Maybe we should add some excludes for this scope. When we find some providers that do not support this scope.

**Comment by fufesou** [comment]
I'll check if Gitlab support another similar scope.

**Comment by fufesou** [comment]
> or at least make the default scope editable

@rustdesk Shall we make "offline_access" editable?

**Comment by rustdesk** [comment]
I do not know OIDC.

**Comment by rustdesk** [comment]
> Maybe we should add some excludes for this scope. When we find some providers that do not support this scope.

This make more sense

**Comment by Peppershade** [comment]
Hi, I was wondering, is there any progress regarding this bug? Today we bought an enterprise license (trial before), and we'd like to use the GitLab authentication for our employees.

**Comment by rustdesk** [comment]
1.1.10
