### ISSUE TITLE
Can't buy rustdesk-pro

### ISSUE THREAD

**Issue by Apashh** [rustdesk/rustdesk-server-pro#6]
Hello,

I have installed rustdesk-server-pro and when i would like to buy licence, i have this error (img)

![image](https://github.com/rustdesk/rustdesk-server-pro/assets/83477029/10c5c681-2015-43bd-8020-aa44fa8f4487)

**Comment by dinger1986** [comment]
Hello, yes the payment portal hasn't been completed yet.

**Comment by rustdesk** [comment]
> Hello,
> 
> I have installed rustdesk-server-pro and when i would like to buy licence, i have this error (img)
> 
> ![image](https://user-images.githubusercontent.com/83477029/251715504-10c5c681-2015-43bd-8020-aa44fa8f4487.png)

The error has tell you all.

**Comment by Apashh** [comment]
Just one more day ? hmmm ;)
