### ISSUE TITLE
[BUG] - Can't connect on device on same group

### ISSUE THREAD

**Issue by Apashh** [rustdesk/rustdesk-server-pro#61]
Hey,

When I have 2 devices on the same group, if I want to login on the second device, I have this:

![image](https://github.com/rustdesk/rustdesk-server-pro/assets/83477029/606ce4ca-0c55-4a4f-b9eb-4fa699fc6f0e)

But if I detach the group from the device I want to connect to (sepecific group to default group), I can connect to it.

Thanks

**Comment by dinger1986** [comment]
Or are you trying to take control of a device? If so you should be logged in

**Comment by Apashh** [comment]
I have 2 devices on same group (A and B)
If A connect to B we have the picture on top this issue.

My config : 
![image](https://github.com/rustdesk/rustdesk-server-pro/assets/83477029/cf7c43df-1dd9-42a0-bc7d-26a71a491ecd)

**Comment by Apashh** [comment]
My devices are connected to SI-ONE

**Comment by dinger1986** [comment]
Are they logged in?

**Comment by Apashh** [comment]
Yep !

![image](https://github.com/rustdesk/rustdesk-server-pro/assets/83477029/cf86cb5c-c715-4093-aeb3-789e33985ba0)
![image](https://github.com/rustdesk/rustdesk-server-pro/assets/83477029/e493a63c-3554-4527-8b2d-283b74f9bed2)

**Comment by rustdesk** [comment]
as local side, you need to login on the client, not from web console, the document emphasised on this.

**Comment by Apashh** [comment]
I'm sorry but i don't understand what i'm doing wrong ? :/

**Comment by rustdesk** [comment]
Login in this way on controlling side.

![image](https://github.com/rustdesk/rustdesk-server-pro/assets/71636191/fcddb2f4-42b7-4fd6-aab8-14c31e3e8724)

**Comment by rustdesk** [comment]
![image](https://github.com/rustdesk/rustdesk-server-pro/assets/71636191/0aa22cd0-6c02-4f36-afe0-2135383bafc5)
