### ISSUE TITLE
[FEATURE] Add to Strategy - Do not allow a user to connect to other computers

### ISSUE THREAD

**Issue by pdifeo** [rustdesk/rustdesk-server-pro#69]
Hi.

It would be useful to have agents that only allow incoming connections.

**Comment by pdifeo** [comment]
@rustdesk , have you considered this feature?

**Comment by rustdesk** [comment]
Let's listen to more voices first.

**Comment by pdifeo** [comment]
OK. From my point of view it is an interesting functionality in an Enterprise environment, where users do not have to do what they want, but where it is the administrator who decides what can and cannot be done.

**Comment by dinger1986** [comment]
I would agree and had been something I have been asked about is restricting certain devices from connecting to others for example in a school.

Maybe if they aren't signed in they can't initiate a connection?

**Comment by TheMatzy** [comment]
I would love that feature! Our employees in homeoffice don't need any connection to other rustdesk clients. We only use rustdesk for support :)

**Comment by rustdesk** [comment]
@21pages let's add this.

**Comment by rustdesk** [comment]
nothing to do with server pro. there are several duplicate issues on this on rustdesk repo.
