### ISSUE TITLE
OIDC Azure AD

### ISSUE THREAD

**Issue by t3ramos** [rustdesk/rustdesk-server-pro#7]
Hey there folks :)
just checked out the pro server, very nice indeed!

I saw that you support github,google & oka as oidc providers.

Planned to add Azure / MS365 too?

**Comment by rustdesk** [comment]
It depends on the feedback from commerical users in the future.

**Comment by dinger1986** [comment]
I think Azure would be useful if its easily enough implemented

**Comment by DaleyKD** [comment]
I haven't had a chance to check out Pro yet (I'm wondering on the cost).

But if I could use my @hotmail.com account, that'd be great.  (I do have business M365 accounts, but don't want to use those for RustDesk.)

**Comment by dinger1986** [comment]
hotmail for OIDC?

pricing is available via rustdesk.com/pricing.html

**Comment by DaleyKD** [comment]
Maybe I'm crazy... (I haven't had my full cup of coffee). Can't you use a Microsoft Account (@hotmail.com/@outlook.com) as an OIDC provider? How is that any different than @gmail.com ?

**Comment by dinger1986** [comment]
> Maybe I'm crazy... (I haven't had my full cup of coffee). Can't you use a Microsoft Account (@hotmail.com/@outlook.com) as an OIDC provider? How is that any different than @gmail.com ?
> 
> EDIT: Thanks for the pricing. $9.90/mo is way too steep for my needs. Good luck.

I have no idea, if an MS account will work, havent tried it, possibly it would.

**Comment by t3ramos** [comment]
For our need it would be mandatory to let users access it with our mfa secured microsoft 365 company accounts. Potential Costumer here ;)

**Comment by dinger1986** [comment]
yeah I am sure theres plenty others, alot of my customers have similar policies

**Comment by rustdesk** [comment]
We are adding this, and support customized OIDC.

**Comment by rustdesk** [comment]
@fufesou add documentation for this.

**Comment by rustdesk** [comment]
added https://rustdesk.com/docs/en/self-host/rustdesk-server-pro/oidc/azure/

**Comment by stephannn** [comment]
Sorry for the maybe dump comment.
Azure App requires to use _localhost_ and not _127.0.0.1_, but when you try Azure Authentication the error is referring to 127.0.0.1:
`AADSTS50011: The redirect URI 'http://127.0.0.1:21114/api/oidc/callback' specified in the request does not match the redirect URIs configured for the application`

**Comment by fufesou** [comment]
@stephannn The redirect URIs are not matched. Please use both `localhost` or `127.0.0.1`.

**Comment by fufesou** [comment]
Thanks for your feedback. I see this restriction.

Maybe you should try HTTPS.

If you just want to test/use on your local machine, you can visit `localhost` as your webconsole address. The callback will follow your current web console domain.

**Comment by stephannn** [comment]
Ah, this works.
Yes, I am just in a small lab and used 127.0.0.1 instead of localhost to reach the console.

Actually to switch to HTTPS I am missing the IIS guide ;) so I am just checking out if it would work in our company environment.
