### ISSUE TITLE
Error messages on bad login

### ISSUE THREAD

**Issue by pdifeo** [rustdesk/rustdesk-server-pro#70]
On web console bad login, a box show without description.

![image](https://github.com/rustdesk/rustdesk-server-pro/assets/8618744/4b60cc78-98ab-4a99-8af1-f4aae283cb1e)

**Comment by rustdesk** [comment]
Yes, this empty warning is annoying, we do not like it either, we failed to find a good way to remove it without modifying depended library. We will readdress this in next releases.

**Comment by pdifeo** [comment]
OK, not a big deal.

However, it is more important to block unauthorised access attempts to avoid a brute force attack. I did a test with more than 30 access attempts and was never blocked.

**Comment by rustdesk** [comment]
> OK, not a big deal.
> 
> However, it is more important to block unauthorised access attempts to avoid a brute force attack. I did a test with more than 30 access attempts and was never blocked.

https://github.com/rustdesk/rustdesk-server-pro/issues/56#issuecomment-1689879026

**Comment by pdifeo** [comment]
As I said in another thread, I am not talking about attempted client accesses. I am talking about access to the webconsole. For me, it is essential to have this type of functionality to guarantee the integrity of the server.

**Comment by rustdesk** [comment]
@21pages please add this, following rustdesk client logic, also report to web console.

**Comment by pdifeo** [comment]
I think that once the block for the webconsole is implemented, it is also activated for account access attempts made on the client. Just now I verified that if I try to access the account with an incorrect password from the client, it does not block.

![image](https://github.com/rustdesk/rustdesk-server-pro/assets/8618744/a346574a-be97-441e-ab93-970615ffa721)

**Comment by rustdesk** [comment]
👍

**Comment by 21pages** [comment]
missed the last bus, will be in next release

![b951828232264a3a1ea072970180607](https://github.com/rustdesk/rustdesk-server-pro/assets/14891774/7eccfd14-cc89-4381-9597-57cb5fc12c54)

![1695594194100](https://github.com/rustdesk/rustdesk-server-pro/assets/14891774/c405f785-338b-4a79-b463-4ffe28cdba39)

![1695594362255](https://github.com/rustdesk/rustdesk-server-pro/assets/14891774/5777d751-3121-4b5b-aff4-ef34565e8086)
