### ISSUE TITLE
Issue with LDAP/Active Directory

### ISSUE THREAD

**Issue by ArnaudL75** [rustdesk/rustdesk-server-pro#74]
### Bug Description

Hello,

I have an issue when I try to connect my Server Pro to my Active Directory.

I provide the following informations: 

- LDAP Host = ad1.mycompany.intra
- LDAP Port = 389
- Base DN = DC=mycompany,DC=INTRA
- Bind DN = CN=Admin_mycompany,CN=Users,DC=mycompany,DC=INTRA

I get the error message:
**Failed to update Ldap: LDAP operation result: rc=49 (invalidCredentials), dn: "", text: "80090308: LdapErr: DSID-0C090434, comment: AcceptSecurityContext error, data 52e, v4f7c"**

I am completely sure of the bind information.

When I try a tail -f /var/log/rustdesk-server/hbbs.log, I get : 
[2023-09-13 18:46:33.591068 +02:00] INFO [src/ldap.rs:133] New LDAP connection: ldap://ad1.mycompany.intra:389

And I see the TCP connection on my FW.

Have you got an idea ?

Thanks a lot for your product !

### How to Reproduce

Bottom

### Expected Behavior

Expected : LDAP connection

### Operating system(s) on local side and remote side

Debian 11

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

![Capture d’écran 2023-09-13 184925](https://github.com/rustdesk/rustdesk/assets/144940033/f95f33fe-9709-4c42-b922-40f2aa2e21fa)

![Capture d’écran 2023-09-13 185023](https://github.com/rustdesk/rustdesk/assets/144940033/0db0d7fd-a922-4721-a60d-bdfa2921240c)

**Comment by rustdesk** [comment]
how about change username to 
```
Base DN = CN=Users,DC=mycompany,DC=INTRA
Bind DN = CN=Admin_mycompany,CN=Users,DC=mycompany,DC=INTRA
```

or 
```
Base DN = CN=Users,DC=mycompany,DC=INTRA
Bind DN = Admin_mycompany
```

**Comment by rustdesk** [comment]
@dinger1986

**Comment by ArnaudL75** [comment]
I just tried it now and unfortunately neither of them works.

Thanks for your support !

**Comment by dinger1986** [comment]
I'll test it out again, what version of AD are you using?

**Comment by dinger1986** [comment]
I cant get it to work, with TLS enabled I get an error on the AD server without I get nothing just 

To check DN etc I use `dsquery user -name adminname` also LDAP server setup as `LDAP://fqdn` I get the same errors as @ArnaudL75 

Also in hbbs logs 

![image](https://github.com/rustdesk/rustdesk-server-pro/assets/7244447/32040e09-a48f-4329-9df6-742ae3e0d51f)

Would it be helpful if I spin up a Windows DC for testing? I can do that tomorrow if needed.

**Comment by rustdesk** [comment]
We will test it ourself on dev side.

**Comment by rustdesk** [comment]
@fufesou

**Comment by ArnaudL75** [comment]
> I'll test it out again, what version of AD are you using?

Hi,

I'm using AD on Windows Server 2022 :)

**Comment by fufesou** [comment]
@ArnaudL75 Hi, can you please try the lower case `DC` and `CN`.

```
LDAP Host = ad1.mycompany.intra
LDAP Port = 389
Base DN = dc=mycompany,dc=INTRA
Bind DN = cn=Admin_mycompany,cn=Users,dc=mycompany,dc=INTRA
```

**Comment by ArnaudL75** [comment]
Yeeahhhhh it works !

Actually, it's work also with 👍 

> LDAP Host = ad1.mycompany.intra
LDAP Port = 389
Base DN = DC=MYCOMPANY,DC=INTRA
Bind DN = cn=Admin_mycompany,CN=Users,DC=MYCOMPANY,DC=INTRA

Just the first "CN" has to be lowercase :)

**Comment by rustdesk** [comment]
'''
Base DN = CN=Users,DC=mycompany,DC=INTRA
Bind DN = Admin_mycompany
'''
This does not work?

**Comment by dinger1986** [comment]
Does that work in testing?

**Comment by dinger1986** [comment]
> ```
> 
> Base DN = CN=Users,DC=mycompany,DC=INTRA
> 
> Bind DN = Admin_mycompany
> 
> ```
> 
> This does not work?

No some are also Organisation units as well

**Comment by ArnaudL75** [comment]
> ```
> Base DN = CN=Users,DC=mycompany,DC=INTRA
> Bind DN = Admin_mycompany
> ```
> 
> This does not work?

It works !

**Comment by ArnaudL75** [comment]
> ```
> Base DN = CN=Users,DC=mycompany,DC=INTRA
> Bind DN = Admin_mycompany
> ```
> 
> This does not work?

Weird, yesterday it seems to not works ... I'll retry

**Comment by fufesou** [comment]
> Does that work in testing? @fufesou

Yes, the key words "cn" should be in lower case. I'll fix this issue.

**Comment by dinger1986** [comment]
lower case is fine, can document it, Ill test it lower, didnt even try that tbh as MS stipulates uppercase

**Comment by dinger1986** [comment]
works fine with containers but doesnt work with organisational units

**Comment by rustdesk** [comment]
> But I believe that the bind user will not look for users anywhere other than the root of the Base DN.

Yes, only search on the root of the Base DN.

It is possible there are duplicate names?
```
cn=abc,OU=PON,OU=Utilisateurs,OU=MYCOMPANY,DC=LPL,DC=INTRA
cn=abc,OU= MMT,OU=Utilisateurs,OU=MYCOMPANY,DC=LPL,DC=INTRA
```

**Comment by ArnaudL75** [comment]
OK I understand the thinking!

But it is not possible to have the same username twice in different OUs. AD forbids it, I just tried it.
Usernames are unique.

**Comment by dinger1986** [comment]
So I can use the domain admin to create the connection but it needs to be "administrator", Ill check the groups on that, but can get any other users to log in

**Comment by dinger1986** [comment]
Ill spin up a new server today, I am thinking could be an issues as this domain started as an sbs 2011 domain and has just been upgraded over time

**Comment by rustdesk** [comment]
@fufesou let's add "scope"  options as below when you fix case senstive issue, also add attributes, we search `cn=<name>` and `uid=<cname>` both.

this https://www.ezeelogin.com/kb/article/error-could-not-bind-to-any-ldap-server-80090308-ldaperr-dsid-0c090453-comment-acceptsecuritycontext-error-data-52e-v3839-396.html is a good example, but we do not need to complex like this.

> Do you have the requirement to search within the subtree of the base DN?
> 
> > To perform a search within a subtree in LDAP and set the parameters, you need to specify the following:
> > 
> > 1. Base DN: Specify the starting point of the search. It is an LDAP path that identifies the location from which the search should begin.
> > 2. Scope: Specify the scope of the search. There are three options:
> >    
> >    * "base": Search only the base DN itself.
> >    * "one" (or "onelevel"): Search only the immediate children of the base DN.
> >    * "sub" (or "subtree"): Search the entire subtree, including the base DN and all its descendants.
> > 3. Filter: Define the filter criteria for the search. It specifies the attributes and conditions that need to be matched.
> > 4. Attributes: Specify the list of attributes to be returned, limiting the attributes included in the search result.
> > 
> > The specific method to set up a search within a subtree may vary depending on the LDAP library, tool, or programming language you are using. Here's an example Python code snippet using LDAP search operation to search within a subtree:
> > ```python
> > import ldap
> > 
> > # Set LDAP server connection parameters
> > ldap_server = 'ldap://ldap.example.com'
> > bind_dn = 'cn=admin,dc=example,dc=com'
> > bind_password = 'password'
> > 
> > # Create LDAP connection
> > conn = ldap.initialize(ldap_server)
> > conn.simple_bind_s(bind_dn, bind_password)
> > 
> > # Set search parameters
> > base_dn = 'ou=users,dc=example,dc=com'
> > scope = ldap.SCOPE_SUBTREE
> > filter = '(objectClass=person)'
> > attributes = ['cn', 'mail']
> > 
> > # Perform the search
> > result = conn.search_s(base_dn, scope, filter, attributes)
> > 
> > # Process the search result
> > for dn, entry in result:
> >     print('DN:', dn)
> >     print('CN:', entry['cn'][0])
> >     print('Email:', entry['mail'][0])
> > 
> > # Close the LDAP connection
> > conn.unbind()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please refer to the documentation of the specific LDAP library or tool you are using to set up a search within a subtree.

**Comment by fufesou** [comment]
> OU=MMT,OU=Utilisateurs,OU=MYCOMPANY,DC=LPL,DC=INTRA

@ArnaudL75 This type of user works for me.


https://github.com/rustdesk/rustdesk-server-pro/assets/13586388/2148c630-0992-42f3-a832-35b348fb8d16

**Comment by ArnaudL75** [comment]
Hello,

In this case, it works for me too ;)

I have two problems:

**--###### THE FIRST #####--**
With these settings:
```
Base DN: OU=Utilisateurs, OU=MYCOMPANY, DC=LPL, DC=INTRA
Bind DN : Admin_mycompany
```

Connection is OK if my user "Admin_mycompany" is inside my OU named Utilisateurs.

BUT the system cannot find users in lower OU like OU=MMT,OU=Utilisateurs,OU=MYCOMPANY,DC=LPL,DC=INTRA
It cannot search in subtree.
But it seems to be soon repaired, with the option "--scope".



**--###### THE SECOND PROBLEM #####--**
With these settings:
```
Base DN: OU=Utilisateurs, OU=MYCOMPANY, DC=LPL, DC=INTRA
Bind DN : cn=Admin_mycompany, OU=Users, DC=LPL, DC=INTRA
```

The connection to LDAP is wrong because the Bind DN does not end with Base DN.
My user "Admin_mycompany" is outside the Base DN, not in the Base DN subtree :)

**Comment by rustdesk** [comment]
We will handle the first problem. The second problem does not make sense.

**Comment by rustdesk** [comment]
As for the second problem.

binddn/password is not required, you can left blank.

**Comment by rustdesk** [comment]
@fufesou take care above two problems, As for second problem, let us have clever check, checking the root dn rather than the whole base dn.

**Comment by rustdesk** [comment]
Maybe some extra filter.

**Comment by rustdesk** [comment]
> Maybe some extra custom filter.

Not very important, just making scope work first.

**Comment by fufesou** [comment]
> For ["scope"](https://en.wikipedia.org/wiki/Lightweight_Directory_Access_Protocol#:~:text=to%20be%20performed.-,scope,-What%20elements%20below)

> The only usage is to search whether "uid" and "user password" exist, so that the login operation can be much simpler.
But the uniqueness of uid seems not guaranteed.

We need to bind when configuring ldap. So the "scope" should not be used at this time.

> https://github.com/rustdesk/rustdesk-server-pro/issues/74#issuecomment-1719542044

The first problem should not be considered on configuring.

We can extract the uid when login, and then search the "uid&userPassword".

**Comment by rustdesk** [comment]
do not use search the "uid&userPassword". use old bind way.

**Comment by fufesou** [comment]
> https://github.com/rustdesk/rustdesk-server-pro/issues/74#issuecomment-1719542044

The second problem.

I've added a `merge_bind_base_dn` method to handle this case.
But I'm not very sure about it.

In the following code, the base dn and bind dn are first normalized to ensure the keywords match and the blank chars are removed.

```rust
    #[test]
    fn test_merge_bind_base_dn() {
        let normalized_base_dn = "";
        let normalized_bind_dn = "cn=aBc,ou=ou2";
        let merged_bind_dn = "cn=aBc,ou=ou2";
        assert_eq!(
            LdapConfig::merge_bind_base_dn(normalized_base_dn, normalized_bind_dn.to_string())
                .unwrap(),
            merged_bind_dn
        );

        let normalized_base_dn = "dc=example,dc=com";
        let normalized_bind_dn = "cn=aBc,ou=ou2,dc=example,dc=com";
        let merged_bind_dn = "cn=aBc,ou=ou2,dc=example,dc=com";
        assert_eq!(
            LdapConfig::merge_bind_base_dn(normalized_base_dn, normalized_bind_dn.to_string())
                .unwrap(),
            merged_bind_dn
        );

        let normalized_base_dn = "dc=example,dc=com";
        let normalized_bind_dn = "cn=aBc,ou=ou2";
        let merged_bind_dn = "cn=aBc,ou=ou2,dc=example,dc=com";
        assert_eq!(
            LdapConfig::merge_bind_base_dn(normalized_base_dn, normalized_bind_dn.to_string())
                .unwrap(),
            merged_bind_dn
        );

        let normalized_base_dn = "ou=ou1,dc=example,dc=com";
        let normalized_bind_dn = "cn=aBc,ou=ou2";
        let merged_bind_dn = "cn=aBc,ou=ou2,ou=ou1,dc=example,dc=com";
        assert_eq!(
            LdapConfig::merge_bind_base_dn(normalized_base_dn, normalized_bind_dn.to_string())
                .unwrap(),
            merged_bind_dn
        );

        let normalized_base_dn = "ou=ou1,dc=example,dc=com";
        let normalized_bind_dn = "cn=aBc,ou=ou2";
        let merged_bind_dn = "cn=aBc,ou=ou2,ou=ou1,dc=example,dc=com";
        assert_eq!(
            LdapConfig::merge_bind_base_dn(normalized_base_dn, normalized_bind_dn.to_string())
                .unwrap(),
            merged_bind_dn
        );

        let normalized_base_dn = "ou=ou1,dc=example,dc=com";
        let normalized_bind_dn = "cn=aBc,ou=ou2,dc=example,dc=com";
        let merged_bind_dn = "cn=aBc,ou=ou2,dc=example,dc=com";
        assert_eq!(
            LdapConfig::merge_bind_base_dn(normalized_base_dn, normalized_bind_dn.to_string())
                .unwrap(),
            merged_bind_dn
        );

        let normalized_base_dn = "ou=ou1,dc=ss,dc=example,dc=com";
        let normalized_bind_dn = "cn=aBc,ou=ou2,dc=example,dc=com";
        assert!(
            LdapConfig::merge_bind_base_dn(normalized_base_dn, normalized_bind_dn.to_string())
                .is_err()
        );

        let normalized_base_dn = "ou=ou1,dc=example,dc=com";
        let normalized_bind_dn = "cn=aBc,ou=ou2,dc=ss,dc=example,dc=com";
        let merged_bind_dn = "cn=aBc,ou=ou2,dc=ss,dc=example,dc=com";
        assert_eq!(
            LdapConfig::merge_bind_base_dn(normalized_base_dn, normalized_bind_dn.to_string())
                .unwrap(),
            merged_bind_dn
        );
    }
```

**Comment by rustdesk** [comment]
1.1.10
