### ISSUE TITLE
SMTP Error: Failed to check STMP: Connection error: Connection error: tls handshake eof

### ISSUE THREAD

**Issue by CLU91** [rustdesk/rustdesk-server-pro#75]
### Bug Description

I was setting up the newest version of Rustdesk Pro on an Ubuntu 22.04.3 LTS Cloud Server. When i try to configure SMTP on the Webinterface i receive the error: **_Failed to check STMP: Connection error: Connection error: tls handshake eof_**

### How to Reproduce

Setting up SMTP in Webinterface

### Expected Behavior

Setting up SMTP without errors or warnings

### Operating system(s) on local side and remote side

Ubuntu Server 22.04.3 LTS

### RustDesk Version(s) on local side and remote side

Server Pro 1.1.9

### Screenshots

![](https://i.imgur.com/uCm4e9x.jpeg)

**Comment by dinger1986** [comment]
what email system are you trying to make it work with? need more info

**Comment by CLU91** [comment]
We are using Microsoft Exchange. We already use it with other Linux Servers on Port 587. It works. Ports are open on each side. I did a openssl s_client -starttls smtp mail.company.com:587 from the Rustdesk Server and it returns successfully our Certificate as expected.

**Comment by CLU91** [comment]
Nope, because the Rustdesk Server is not even trying to establish a connection to the exchange. Our firewall isn't showing any try.

**Comment by CLU91** [comment]
In the meantime i figured out, that there is a bug in NGINX Version 1.18. This version is delivered natively with Ubuntu Server 22.04 still, even there is newer versions of NGINX. The problem is, when i upgrade NGINX to 1.24 for example, it's not working anymore and the Webinterface isn't available anymore. I also tried to install NGINX beforehand and then run the installer script but then i have an half empty rustdesk.conf file. Seems like Rustdesk installation script is not made for other version then 1.18.....

**Comment by dinger1986** [comment]
shall check the upgrade to newer nginx and fix it

**Comment by CLU91** [comment]
New nginx version 1.24 still not working. I manually updated the package and its dependencies and copied all settings. Still the same error.

**Comment by dinger1986** [comment]
yes looking

**Comment by dinger1986** [comment]
> New nginx version 1.24 still not working. I manually updated the package and its dependencies and copied all settings. Still the same error.

The new version of nginx.conf changes settings, this needs replaced with the old version, or compare and see what the differences are which I will do as soon as I can but wont be before the weekend.

Original nginx.conf
```
user www-data;
worker_processes auto;
pid /run/nginx.pid;
error_log /var/log/nginx/error.log;
include /etc/nginx/modules-enabled/*.conf;

events {
        worker_connections 768;
        # multi_accept on;
}

http {

        ##
        # Basic Settings
        ##

        sendfile on;
        tcp_nopush on;
        types_hash_max_size 2048;
        # server_tokens off;

        # server_names_hash_bucket_size 64;
        # server_name_in_redirect off;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        ##
        # SSL Settings
        ##

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
        ssl_prefer_server_ciphers on;

        ##
        # Logging Settings
        ##

        access_log /var/log/nginx/access.log;

        ##
        # Gzip Settings
        ##

        gzip on;

        # gzip_vary on;
        # gzip_proxied any;
        # gzip_comp_level 6;
        # gzip_buffers 16 8k;
        # gzip_http_version 1.1;
        # gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

        ##
        # Virtual Host Configs
        ##

        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}


#mail {
#       # See sample authentication script at:
#       # http://wiki.nginx.org/ImapAuthenticateWithApachePhpScript
#
#       # auth_http localhost/auth.php;
#       # pop3_capabilities "TOP" "USER";
#       # imap_capabilities "IMAP4rev1" "UIDPLUS";
#
#       server {
#               listen     localhost:110;
#               protocol   pop3;
#               proxy      on;
#       }
#
#       server {
#               listen     localhost:143;
#               protocol   imap;
#               proxy      on;
#       }
#}
```

**Comment by CLU91** [comment]
My nginx.conf file already looks like this... only difference is server_tokesn off; is active. In your example there is a # in front....

**Comment by dinger1986** [comment]
Contact support@rustdesk.com and I'll take a look

**Comment by enoch85** [comment]
We could use Nginx own repos in the installation... Don't know if it would make any difference though.
