### ISSUE TITLE
Missing file in Windows Setup

### ISSUE THREAD

**Issue by TobiLanger** [rustdesk/rustdesk-server-pro#8]
Hi,

I tried to install Rustdesk-Server-Pro for Windows.
The setup process runs fine, but after installation is complete,
the file "rustdesk_server.exe" is missing in the install folder "C:\Program Files\RustDeskServer"

Any help would be nice :-)

**Comment by dinger1986** [comment]
hello, we can look into that, currently the payment portal isnt setup for getting licences also

**Comment by dinger1986** [comment]
I can confirm the program is missing, the opensource version works fine https://github.com/rustdesk/rustdesk-server/releases/download/1.1.8/rustdesk-server-windows-x86_64.zip

**Comment by TobiLanger** [comment]
Thanks dinger,
the installation works fine. Can you now tell me how to get the Web Console working?
There is no open port 21114.
Is there a possibility to get a test license for rustdesk server pro?

**Comment by dinger1986** [comment]
which version is working fine?

**Comment by TobiLanger** [comment]
I installed the opensource version - with the other version the file "rustdesk_server.exe" was missing.
How can we test the pro version if there isn't a test license available?

**Comment by dinger1986** [comment]
the opensource version doesnt have the API or port 21114.

The pro version works the same as the opensource version with more features

**Comment by TobiLanger** [comment]
Okay, so at the moment there isn't a possibility to test for example the webconsole, managed devices (like host version with teamviewer...)

**Comment by dinger1986** [comment]
yes that is correct

**Comment by TobiLanger** [comment]
okay thanks, would be nice in the future ;-)

**Comment by dinger1986** [comment]
I will make sure I discuss it with the team

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk-server-pro/releases/download/1.1.8/rustdesk-server-windows-x86_64.zip updated

**Comment by dinger1986** [comment]
Thanks @TobiLanger please close this

**Comment by TobiLanger** [comment]
Everything is fine now - please consider to give a trial license for the pro version ;-)
