### ISSUE TITLE
Get rustdesk ID no longer working with 1.2.2

### ISSUE THREAD

**Issue by RichardBurt65** [rustdesk/rustdesk-server-pro#80]
"How can I get RustDesk IDs from agents on my network or using an RMM type system?"

This [powershell script](https://rustdesk.com/docs/en/self-host/rustdesk-server-pro/faq/#how-can-i-get-rustdesk-ids-from-agents-on-my-network-or-using-an-rmm-type-system) no longer extracts $rustdesk_id for v 1.2.2

**Comment by dinger1986** [comment]
I forgtot hat was there, thanks for pointing it out, will actually remove it from the FAQs as its all available here https://rustdesk.com/docs/en/self-host/client-deployment/
