### ISSUE TITLE
Console under nginx reverse proxy

### ISSUE THREAD

**Issue by pdifeo** [rustdesk/rustdesk-server-pro#85]
The correct way to set nginx as a reverse proxy is as follows

        location / {
           proxy_set_header        X-Real-IP       $remote_addr;
           proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;

           proxy_pass http://127.0.0.1:21114/;
           }

Otherwise, in the list of connected devices, the IP address is 127.0.0.1

This was before the change

![image](https://github.com/rustdesk/rustdesk-server-pro/assets/8618744/b9352729-48a0-44e6-a1b0-498960c5d37a)

and this after

![image](https://github.com/rustdesk/rustdesk-server-pro/assets/8618744/601ef66c-63a2-435e-b200-546c200f2fc1)

The installation script should be updated

Regards
Pasquale

**Comment by dinger1986** [comment]
just replied in other thread, ill test and implement

**Comment by rustdesk** [comment]
Fixed?

**Comment by rustdesk** [comment]
There will cause a lot of problem without real ip.

**Comment by pdifeo** [comment]
In my installation no problem with IPs, indeed it was before

This is the config

```
http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    # Load modular configuration files from the /etc/nginx/conf.d directory.
    # See http://nginx.org/en/docs/ngx_core_module.html#include
    # for more information.
    include /etc/nginx/conf.d/*.conf;

    server {
        listen       80 default_server;
        listen       [::]:80 default_server;
        server_name  _;
        root         /usr/share/nginx/html;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

#        location / {
#        }

        location / {
           proxy_set_header        X-Real-IP       $remote_addr;
           proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;

           proxy_pass http://127.0.0.1:21114/;
           }

        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }

        listen 443 ssl;

        # RSA certificate
        ssl_certificate /etc/letsencrypt/live/<my-server-name>/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/<my-server-name>/privkey.pem; # managed by Certbot

        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot

```
In the interests of intellectual honesty, this is not a configuration made with the script. I did it by hand. The distribution is RockyLinux 8.8

Pasquale

**Comment by rustdesk** [comment]
@dinger1986

**Comment by dinger1986** [comment]
tested working, hadnt pushed the changes, shall do that now.

**Comment by dinger1986** [comment]
added in 
```
       proxy_set_header        X-Real-IP       $remote_addr;
       proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
```

**Comment by rustdesk** [comment]
Make sure `-net=host` when running docker

> I tried this, but I does not work. Maybe it’s a problem of Nginx Proxy Manager. I added the headers in “Advanced” Tab and also tried it with Custom Locations Tab in NginxProxyManager. But in den Rustdeskconsole “Logs” Tab I only see the Addresses of the Containers.
