### ISSUE TITLE
Groups accessing themselves  

### ISSUE THREAD

**Issue by stephannn** [rustdesk/rustdesk-server-pro#87]
Not sure if this is even a real use case or I am just overthinking.

For my lab I created two groups:
-	Users
-	IT Admins
I also set up that Users are not allowed to connect to anywhere, but IT Admis can access Users. However, a user object can only be in one group and a group cannot be pointing to itself. So the issue I see is that IT Admins cannot support other IT Admins, am I right?

Also is there a way to define a default group for users? Currently it is Default, but this cannot be edited in the way who can connect etc.

**Comment by 21pages** [comment]
1. Users within the same group can access each other.
2. By setting https://rustdesk.com/docs/en/self-host/rustdesk-server-pro/permissions/, inter-group access is allowed.
3. Users can access unbinded devices. 
4. Disabled users and devices are not allowed to access others, nor can they be accessed by others. 

These can be validated through the client's group peer tab.

**Comment by stephannn** [comment]
ah, yes, I see. Quote: "However, this may cause some confusion" ;)

Did I also oversee the point about default groups where users fall into?

**Comment by stephannn** [comment]
thats way too easy. 

Ok, sorry, but I have one last one. I have my azure user in the default group, but he is able to login to the website and can see other devices. How can I restrict access to the website for the default user group?

**Comment by rustdesk** [comment]
@stephannn this is a bug, the normal use should see the device you can access only. Give us one hour to fix this. @21pages 



> How can I restrict access to the website for the default user group?

We have no this yet. we may consider, let's listen to more voice for this before taking action.

**Comment by rustdesk** [comment]
in 1.1.9， for normal user, can see its devices only.

**Comment by rustdesk** [comment]
@stephannn https://github.com/rustdesk/rustdesk-server-pro/releases/tag/1.1.10-2
