### ISSUE TITLE
Update script different from install script on get lastest version

### ISSUE THREAD

**Issue by pdifeo** [rustdesk/rustdesk-server-pro#90]
Hi

into install script there is

`RDLATEST=$(curl https://api.github.com/repos/rustdesk/rustdesk-server-pro/releases/latest -s | grep "tag_name"| awk '{print substr($2, 2, length($2)-3) }')`

into update script there is

`RDLATEST=$(curl https://api.github.com/repos/rustdesk/rustdesk-server-pro/releases/latest -s | grep "tag_name"| awk '{print substr($2, 2, length($2)-3) }' **| sed 's/-.*//'**)`

So, in this moment, update.sh never update to current release 1.1.10-3

Regards
Pasquale

**Comment by dinger1986** [comment]
I'll add a bit for pre release

**Comment by dinger1986** [comment]
These are pre releases if @rustdesk wants me to include them I will

**Comment by rustdesk** [comment]
not pre-release any more

**Comment by pdifeo** [comment]
Sorry. Is 1.1.10-3 a pre-release?

**Comment by dinger1986** [comment]
yes

**Comment by pdifeo** [comment]
So **install.sh** must not allow a pre-release to be installed. It now allows it.

**Comment by rustdesk** [comment]
> not pre-release any more
> 
> ![image](https://user-images.githubusercontent.com/71636191/271509241-0c0bfda4-99bb-4481-829e-b1ef16bd26af.png)

It is release, not pre-release, please fix this.

**Comment by dinger1986** [comment]
releases work, its just prereleases that dont, but I will make the update script and install script match

**Comment by dinger1986** [comment]
The issue is that the binary only recognises itself as 1.1.10 

![image](https://github.com/rustdesk/rustdesk-server-pro/assets/7244447/340f7a79-6c04-4412-9345-0114367eeba8)

so still get this

![image](https://github.com/rustdesk/rustdesk-server-pro/assets/7244447/283ac77a-8dca-4ffa-825b-2e0753ab2466)

**Comment by dinger1986** [comment]
PR on its way, sorry for the confusion! https://github.com/rustdesk/rustdesk-server-pro/pull/95

**Comment by pdifeo** [comment]
> releases work, its just prereleases that dont, but I will make the update script and install script match, I see now, it wasnt getting the -version at the end, updated the script and testing now

Sorry if I was not clear in my explanation. That was what I was saying in the opening of the thread.

**Comment by dinger1986** [comment]
Yeah I know sorry about that
