### ISSUE TITLE
SMTP ERROR, Could not Connect to SMTP Host

### ISSUE THREAD

**Issue by omarfarooq4u2c** [rustdesk/rustdesk-server-pro#97]
I'am facing this problem when using PHPMailer, Guyz please help.

2023-10-02 11:28:44 SMTP ERROR: Failed to connect to server: (0)
SMTP Error: Could not connect to SMTP host. Failed to connect to server
Message could not be sent. Mailer Error: SMTP Error: Could not connect to SMTP host. Failed to connect to serverSMTP server error: Failed to connect to server

**Comment by rustdesk** [comment]
check your port
